
INCLUDE("${PROJECT_SOURCE_DIR}/Config.cmake")

SET(CMAKE_CXX_STANDARD 14)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)
SET(CMAKE_EXPORT_COMPILE_COMMANDS OFF)

UNSET(COMPILE_OPTIONS)

INCLUDE_DIRECTORIES("${PROJECT_SOURCE_DIR}/Test")

FIND_PACKAGE(GTest CONFIG REQUIRED)
INCLUDE(GoogleTest)
ENABLE_TESTING()

FUNCTION(CREATE_TEST TEST SOURCES)
    ADD_EXECUTABLE(${TEST} ${SOURCES} "${PROJECT_SOURCE_DIR}/Test/lib/Printer.h")
    TARGET_LINK_LIBRARIES(${TEST} Core-24 GTest::gtest GTest::gmock GTest::gtest_main)
ENDFUNCTION()
