CMAKE_MINIMUM_REQUIRED(VERSION 3.10)

PROJECT("CORE-24"
        VERSION 2024.01.2025.03
        DESCRIPTION "MY FUTURE VISION FOR C++ LANGUAGE (POINTER TO PURE REFERENCE)"
        LANGUAGES ASM C CXX)

SET(CMAKE_C_STANDARD 99)
SET(CMAKE_CXX_STANDARD 11)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)
SET(CMAKE_EXPORT_COMPILE_COMMANDS ON)

#IF (NOT CYGWIN AND NOT MSYS AND NOT ${CMAKE_SYSTEM_NAME} STREQUAL QNX)
#    SET(CMAKE_CXX_EXTENSIONS OFF)
#ENDIF ()

ENABLE_TESTING()

IF (WIN32)
    SET(SYSTEM "Win32")
ELSE ()
    SET(SYSTEM "Unix")
ENDIF (WIN32)

INCLUDE(CMakeDependentOption)
INCLUDE(GNUInstallDirs)

INCLUDE_DIRECTORIES("${CMAKE_CURRENT_SOURCE_DIR}/Lib")
INCLUDE_DIRECTORIES("${CMAKE_CURRENT_SOURCE_DIR}/Internal/${SYSTEM}")

OPTION(BUILD_SHARED "Use shared (DLL) run-time lib even when Google Test is built as static lib." ON)
OPTION(BUILD_TESTS "Build Test subproject" ON)
OPTION(BUILD_SAMPLES "Build Sample subproject" ON)
OPTION(INSTALL_CORE24 "Enable installation of CORE 24. (Projects embedding CORE 24 may want to turn this OFF.)" ON)

ADD_SUBDIRECTORY("${CMAKE_CURRENT_SOURCE_DIR}/Lib")

IF (BUILD_TESTS)
    ADD_SUBDIRECTORY("${CMAKE_CURRENT_SOURCE_DIR}/Test")
ENDIF ()

IF (BUILD_SAMPLES)
    ADD_SUBDIRECTORY("${CMAKE_CURRENT_SOURCE_DIR}/Src")
ENDIF ()


INCLUDE_DIRECTORIES("${CMAKE_CURRENT_SOURCE_DIR}/Lib")

MESSAGE(NOTICE ${CMAKE_CURRENT_SOURCE_DIR} <<)