CMAKE_MINIMUM_REQUIRED(VERSION 3.16)

PROJECT(Core24
        VERSION 2024.01.2025.03
        DESCRIPTION "MY FUTURE VISION FOR C++ LANGUAGE (POINTER TO PURE REFERENCE)"
        LANGUAGES ASM C CXX)

SET(CMAKE_C_STANDARD 99)
SET(CMAKE_CXX_STANDARD 20)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)
SET(CMAKE_EXPORT_COMPILE_COMMANDS OFF)

ADD_SUBDIRECTORY("${PROJECT_SOURCE_DIR}/Test")

IF (WIN32)
    SET(SYSTEM "Win32")
ELSE ()
    SET(SYSTEM "Unix")
ENDIF (WIN32)

FILE(GLOB ALL
        "Lib/**/*.h" "Lib/**/*.cpp"
        "Lib/**/*/*.h" "Lib/**/*/*.cpp"
        "Lib/**/*/*/*.h" "Lib/**/*/*/*.cpp"
        "Lib/**/*/*/*/*.h" "Lib/**/*/*/*/*.cpp"
)
FILE(GLOB SYS
        "Internal/${SYSTEM}/**/*.h" "Internal/${SYSTEM}/**/*.cpp"
        "Internal/${SYSTEM}/**/**/*.h" "Internal/${SYSTEM}/**/**/*.cpp"
)

SET(ANY ${ALL} ${SYS})

INCLUDE(GNUInstallDirs)

INCLUDE_DIRECTORIES("${PROJECT_SOURCE_DIR}/Lib")
INCLUDE_DIRECTORIES("${PROJECT_SOURCE_DIR}/Internal/${SYSTEM}")

ADD_LIBRARY(Core-24 SHARED ${ANY})
ADD_EXECUTABLE(Main "${PROJECT_SOURCE_DIR}/Src/Main.cpp")

TARGET_LINK_LIBRARIES(Main PRIVATE Core-24)

#INSTALL(TARGETS Core24
#        EXPORT Core24Core
#        LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
#        ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
#        RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
#        INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
