
#ifndef CORE24_CLDR_LIKELYSUBTAG
#define CORE24_CLDR_LIKELYSUBTAG

#include <core/lang/Object.h>
    
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

    
namespace core {
    namespace locales {
    
        /*
         * Utility used to find likely subtag for specified locale
         */
        class LikelySubtag final : public Object {
        public:
            CORE_IMPLICIT LikelySubtag() = default;
            
            /**
             * Return the likely subtag corresponding with specified locale
             */
            static IntArray resolve(gint language, gint script, gint region);
            
            /**
             * Return the list of locale in compact format: 
             * language << 32 | script << 16 | region
             */
            static LongArray availableLocales();
        };
    
    }
}
    
#endif
            