
#include "LikelySubtag.h"
#include <core/IntArray.h>
#include <core/LongArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    namespace locales {
    
        IntArray LikelySubtag::resolve(gint language, gint script, gint region) {
            switch(language) {
				case 0: return IntArray::of(0, 92, 106);
				case 1: return IntArray::of(1, 31, 118);
				case 2: return IntArray::of(2, 92, 141);
				case 3: return IntArray::of(3, 92, 273);
				case 4: return IntArray::of(4, 92, 121);
				case 5: return IntArray::of(5, 31, 232);
				case 6: return IntArray::of(6, 8, 148);
				case 7: return IntArray::of(7, 4, 265);
				case 8: return IntArray::of(8, 92, 294);
				case 10: return IntArray::of(10, 92, 79);
				case 13: return IntArray::of(13, 92, 121);
				case 14: return IntArray::of(14, 198, 147);
				case 17: return IntArray::of(17, 92, 290);
				case 18: return IntArray::of(18, 31, 232);
				case 19: return IntArray::of(19, 43, 106);
				case 20: return IntArray::of(20, 92, 105);
				case 22: return IntArray::of(22, 92, 204);
				case 24: return IntArray::of(24, 4, 253);
				case 25: return IntArray::of(25, 4, 102);
				case 26: 
					if (script == 135) return IntArray::of(26, 135, 253);
					if (script == 122) return IntArray::of(26, 122, 153);
					if (script == 62) return IntArray::of(26, 62, 147);
					return IntArray::of(26, 6, 148);
				case 27: return IntArray::of(27, 92, 78);
				case 28: return IntArray::of(28, 92, 60);
				case 30: return IntArray::of(30, 4, 98);
				case 31: return IntArray::of(31, 4, 234);
				case 33: return IntArray::of(33, 4, 177);
				case 34: return IntArray::of(34, 4, 102);
				case 35: return IntArray::of(35, 13, 145);
				case 36: return IntArray::of(36, 92, 271);
				case 37: return IntArray::of(37, 154, 276);
				case 38: return IntArray::of(38, 92, 105);
				case 39: return IntArray::of(39, 92, 70);
				case 40: return IntArray::of(40, 31, 232);
				case 42: return IntArray::of(42, 33, 145);
				case 43: return IntArray::of(43, 92, 60);
				case 44: 
					if (script == 4) return IntArray::of(44, 4, 148);
					if (region == 232) return IntArray::of(44, 31, 232);
					if (region == 148) return IntArray::of(44, 4, 148);
					if (region == 147) return IntArray::of(44, 4, 147);
					return IntArray::of(44, 92, 47);
				case 45: return IntArray::of(45, 31, 232);
				case 46: return IntArray::of(46, 4, 218);
				case 47: return IntArray::of(47, 92, 141);
				case 48: return IntArray::of(48, 92, 43);
				case 49: return IntArray::of(49, 92, 79);
				case 50: return IntArray::of(50, 10, 79);
				case 51: return IntArray::of(51, 92, 141);
				case 52: return IntArray::of(52, 92, 79);
				case 53: return IntArray::of(53, 31, 68);
				case 54: return IntArray::of(54, 4, 237);
				case 55: return IntArray::of(55, 92, 295);
				case 56: return IntArray::of(56, 92, 141);
				case 57: return IntArray::of(57, 92, 271);
				case 58: return IntArray::of(58, 92, 79);
				case 59: return IntArray::of(59, 175, 145);
				case 60: return IntArray::of(60, 31, 53);
				case 61: return IntArray::of(61, 33, 145);
				case 62: return IntArray::of(62, 4, 218);
				case 64: return IntArray::of(64, 33, 145);
				case 65: return IntArray::of(65, 92, 285);
				case 66: return IntArray::of(66, 92, 217);
				case 67: return IntArray::of(67, 92, 204);
				case 68: return IntArray::of(68, 92, 141);
				case 69: return IntArray::of(69, 92, 79);
				case 70: return IntArray::of(70, 92, 70);
				case 71: return IntArray::of(71, 92, 56);
				case 72: return IntArray::of(72, 177, 284);
				case 73: return IntArray::of(73, 92, 185);
				case 74: return IntArray::of(74, 13, 50);
				case 75: return IntArray::of(75, 184, 80);
				case 76: return IntArray::of(76, 13, 145);
				case 77: return IntArray::of(77, 4, 148);
				case 78: return IntArray::of(78, 92, 114);
				case 79: return IntArray::of(79, 33, 145);
				case 80: return IntArray::of(80, 4, 218);
				case 81: return IntArray::of(81, 33, 145);
				case 82: return IntArray::of(82, 92, 48);
				case 83: return IntArray::of(83, 92, 79);
				case 84: return IntArray::of(84, 31, 232);
				case 85: return IntArray::of(85, 92, 141);
				case 86: return IntArray::of(86, 92, 79);
				case 87: return IntArray::of(87, 43, 104);
				case 88: return IntArray::of(88, 92, 79);
				case 89: return IntArray::of(89, 92, 105);
				case 90: return IntArray::of(90, 92, 276);
				case 93: return IntArray::of(93, 92, 204);
				case 94: return IntArray::of(94, 21, 50);
				case 95: return IntArray::of(95, 31, 232);
				case 96: return IntArray::of(96, 92, 217);
				case 97: return IntArray::of(97, 92, 273);
				case 98: return IntArray::of(98, 92, 131);
				case 101: return IntArray::of(101, 92, 112);
				case 102: return IntArray::of(102, 31, 232);
				case 104: return IntArray::of(104, 92, 276);
				case 105: return IntArray::of(105, 92, 70);
				case 106: return IntArray::of(106, 25, 276);
				case 108: return IntArray::of(108, 92, 276);
				case 109: return IntArray::of(109, 4, 147);
				case 110: return IntArray::of(110, 92, 70);
				case 111: return IntArray::of(111, 92, 114);
				case 112: return IntArray::of(112, 28, 102);
				case 113: return IntArray::of(113, 92, 217);
				case 114: return IntArray::of(114, 22, 70);
				case 115: return IntArray::of(115, 92, 70);
				case 116: return IntArray::of(116, 31, 272);
				case 118: return IntArray::of(118, 22, 70);
				case 119: return IntArray::of(119, 22, 70);
				case 122: return IntArray::of(122, 92, 236);
				case 123: return IntArray::of(123, 92, 90);
				case 124: return IntArray::of(124, 92, 219);
				case 125: return IntArray::of(125, 22, 70);
				case 126: 
					if (script == 47) return IntArray::of(126, 47, 53);
					return IntArray::of(126, 31, 232);
				case 127: return IntArray::of(127, 31, 232);
				case 129: return IntArray::of(129, 92, 116);
				case 130: return IntArray::of(130, 92, 95);
				case 131: return IntArray::of(131, 92, 276);
				case 132: return IntArray::of(132, 31, 232);
				case 133: return IntArray::of(133, 92, 155);
				case 134: return IntArray::of(134, 92, 92);
				case 136: return IntArray::of(136, 92, 70);
				case 137: return IntArray::of(137, 92, 70);
				case 139: return IntArray::of(139, 92, 202);
				case 140: return IntArray::of(140, 33, 145);
				case 141: return IntArray::of(141, 92, 92);
				case 142: return IntArray::of(142, 92, 198);
				case 143: return IntArray::of(143, 92, 79);
				case 145: return IntArray::of(145, 182, 195);
				case 146: return IntArray::of(146, 92, 246);
				case 147: return IntArray::of(147, 92, 52);
				case 148: return IntArray::of(148, 184, 64);
				case 150: return IntArray::of(150, 92, 155);
				case 151: return IntArray::of(151, 92, 121);
				case 152: return IntArray::of(152, 92, 204);
				case 153: return IntArray::of(153, 92, 150);
				case 154: return IntArray::of(154, 40, 102);
				case 156: return IntArray::of(156, 52, 128);
				case 158: 
					if (script == 155) return IntArray::of(158, 155, 116);
					return IntArray::of(158, 92, 276);
				case 160: return IntArray::of(160, 92, 0);
				case 161: return IntArray::of(161, 92, 105);
				case 162: return IntArray::of(162, 92, 276);
				case 163: return IntArray::of(163, 92, 101);
				case 164: return IntArray::of(164, 92, 105);
				case 165: return IntArray::of(165, 92, 79);
				case 166: return IntArray::of(166, 92, 105);
				case 167: return IntArray::of(167, 4, 148);
				case 168: return IntArray::of(168, 92, 127);
				case 170: 
					if (script == 0) return IntArray::of(170, 0, 125);
					return IntArray::of(170, 92, 246);
				case 171: return IntArray::of(171, 92, 109);
				case 172: return IntArray::of(172, 92, 217);
				case 173: return IntArray::of(173, 92, 238);
				case 174: return IntArray::of(174, 92, 110);
				case 175: return IntArray::of(175, 92, 113);
				case 176: return IntArray::of(176, 92, 56);
				case 177: return IntArray::of(177, 92, 114);
				case 178: return IntArray::of(178, 92, 276);
				case 181: return IntArray::of(181, 92, 114);
				case 182: return IntArray::of(182, 92, 92);
				case 183: return IntArray::of(183, 92, 92);
				case 184: return IntArray::of(184, 92, 150);
				case 185: return IntArray::of(185, 92, 206);
				case 186: return IntArray::of(186, 92, 142);
				case 187: return IntArray::of(187, 92, 121);
				case 188: return IntArray::of(188, 92, 179);
				case 189: return IntArray::of(189, 60, 80);
				case 190: return IntArray::of(190, 92, 141);
				case 192: return IntArray::of(192, 4, 148);
				case 193: return IntArray::of(193, 92, 116);
				case 194: return IntArray::of(194, 43, 106);
				case 195: return IntArray::of(195, 92, 158);
				case 196: return IntArray::of(196, 92, 105);
				case 197: return IntArray::of(197, 4, 148);
				case 199: return IntArray::of(199, 92, 226);
				case 201: return IntArray::of(201, 33, 145);
				case 202: return IntArray::of(202, 92, 141);
				case 203: return IntArray::of(203, 50, 272);
				case 205: 
					if (script == 96) return IntArray::of(205, 96, 128);
					return IntArray::of(205, 30, 89);
				case 206: return IntArray::of(206, 92, 75);
				case 207: return IntArray::of(207, 53, 145);
				case 208: return IntArray::of(208, 92, 81);
				case 209: return IntArray::of(209, 92, 121);
				case 210: return IntArray::of(210, 92, 155);
				case 211: return IntArray::of(211, 92, 144);
				case 212: return IntArray::of(212, 92, 70);
				case 213: 
					if (region == 237) return IntArray::of(213, 4, 237);
					if (region == 79) return IntArray::of(213, 4, 79);
					return IntArray::of(213, 92, 204);
				case 215: return IntArray::of(215, 60, 80);
				case 216: return IntArray::of(216, 92, 276);
				case 219: return IntArray::of(219, 63, 143);
				case 220: return IntArray::of(220, 33, 145);
				case 221: return IntArray::of(221, 33, 110);
				case 222: return IntArray::of(222, 92, 217);
				case 225: 
					if (script == 66) return IntArray::of(225, 66, 166);
					return IntArray::of(225, 67, 276);
				case 226: return IntArray::of(226, 92, 216);
				case 227: return IntArray::of(227, 92, 137);
				case 228: return IntArray::of(228, 92, 92);
				case 229: return IntArray::of(229, 60, 80);
				case 230: return IntArray::of(230, 92, 138);
				case 231: return IntArray::of(231, 92, 139);
				case 233: return IntArray::of(233, 92, 70);
				case 234: return IntArray::of(234, 7, 38);
				case 235: return IntArray::of(235, 92, 200);
				case 236: return IntArray::of(236, 92, 0);
				case 237: return IntArray::of(237, 92, 198);
				case 238: return IntArray::of(238, 92, 204);
				case 239: return IntArray::of(239, 92, 141);
				case 240: return IntArray::of(240, 92, 101);
				case 241: return IntArray::of(241, 92, 204);
				case 242: return IntArray::of(242, 200, 80);
				case 243: return IntArray::of(243, 92, 276);
				case 246: return IntArray::of(246, 92, 217);
				case 247: return IntArray::of(247, 92, 141);
				case 248: return IntArray::of(248, 31, 232);
				case 249: return IntArray::of(249, 92, 0);
				case 250: return IntArray::of(250, 92, 149);
				case 251: return IntArray::of(251, 92, 150);
				case 252: return IntArray::of(252, 22, 70);
				case 253: return IntArray::of(253, 63, 143);
				case 254: return IntArray::of(254, 92, 232);
				case 255: return IntArray::of(255, 74, 154);
				case 256: return IntArray::of(256, 92, 152);
				case 257: return IntArray::of(257, 92, 0);
				case 258: return IntArray::of(258, 92, 79);
				case 259: return IntArray::of(259, 63, 272);
				case 260: return IntArray::of(260, 92, 271);
				case 263: return IntArray::of(263, 92, 95);
				case 264: return IntArray::of(264, 92, 141);
				case 265: return IntArray::of(265, 46, 118);
				case 266: return IntArray::of(266, 31, 278);
				case 267: return IntArray::of(267, 92, 98);
				case 268: return IntArray::of(268, 92, 186);
				case 269: return IntArray::of(269, 92, 204);
				case 270: return IntArray::of(270, 92, 155);
				case 271: return IntArray::of(271, 78, 141);
				case 272: return IntArray::of(272, 31, 232);
				case 274: return IntArray::of(274, 92, 204);
				case 275: return IntArray::of(275, 92, 271);
				case 276: return IntArray::of(276, 92, 86);
				case 277: return IntArray::of(277, 92, 79);
				case 278: return IntArray::of(278, 92, 76);
				case 279: return IntArray::of(279, 92, 72);
				case 280: return IntArray::of(280, 92, 62);
				case 281: return IntArray::of(281, 92, 145);
				case 283: return IntArray::of(283, 92, 185);
				case 284: return IntArray::of(284, 4, 218);
				case 285: return IntArray::of(285, 92, 155);
				case 286: return IntArray::of(286, 92, 267);
				case 287: return IntArray::of(287, 92, 200);
				case 288: 
					if (script == 4) return IntArray::of(288, 4, 80);
					if (region == 187) return IntArray::of(288, 4, 187);
					if (region == 148) return IntArray::of(288, 4, 148);
					if (region == 80) return IntArray::of(288, 4, 80);
					if (region == 34) return IntArray::of(288, 4, 34);
					return IntArray::of(288, 31, 165);
				case 289: return IntArray::of(289, 92, 79);
				case 290: return IntArray::of(290, 92, 123);
				case 291: return IntArray::of(291, 92, 155);
				case 292: return IntArray::of(292, 80, 157);
				case 293: return IntArray::of(293, 92, 39);
				case 294: return IntArray::of(294, 83, 145);
				case 295: return IntArray::of(295, 84, 162);
				case 296: return IntArray::of(296, 31, 232);
				case 297: return IntArray::of(297, 33, 145);
				case 298: return IntArray::of(298, 92, 112);
				case 299: return IntArray::of(299, 92, 171);
				case 301: return IntArray::of(301, 31, 232);
				case 302: return IntArray::of(302, 92, 244);
				case 303: return IntArray::of(303, 92, 217);
				case 304: return IntArray::of(304, 92, 232);
				case 305: return IntArray::of(305, 33, 145);
				case 306: return IntArray::of(306, 4, 145);
				case 307: return IntArray::of(307, 92, 271);
				case 308: return IntArray::of(308, 92, 79);
				case 309: return IntArray::of(309, 92, 92);
				case 310: 
					if (script == 199) return IntArray::of(310, 199, 118);
					if (script == 4) return IntArray::of(310, 4, 147);
					if (region == 167) return IntArray::of(310, 4, 167);
					return IntArray::of(310, 92, 267);
				case 311: return IntArray::of(311, 31, 232);
				case 313: return IntArray::of(313, 31, 232);
				case 314: return IntArray::of(314, 92, 116);
				case 315: return IntArray::of(315, 92, 70);
				case 316: return IntArray::of(316, 92, 145);
				case 317: 
					if (script == 92) return IntArray::of(317, 92, 267);
					if (script == 4) return IntArray::of(317, 4, 80);
					if (region == 267) return IntArray::of(317, 92, 267);
					if (region == 80) return IntArray::of(317, 4, 80);
					return IntArray::of(317, 31, 156);
				case 318: return IntArray::of(318, 92, 279);
				case 319: return IntArray::of(319, 63, 143);
				case 320: return IntArray::of(320, 92, 271);
				case 321: return IntArray::of(321, 4, 218);
				case 323: return IntArray::of(323, 92, 174);
				case 324: return IntArray::of(324, 31, 232);
				case 326: return IntArray::of(326, 92, 273);
				case 327: return IntArray::of(327, 92, 206);
				case 328: return IntArray::of(328, 92, 150);
				case 329: return IntArray::of(329, 92, 70);
				case 331: return IntArray::of(331, 92, 276);
				case 332: return IntArray::of(332, 92, 150);
				case 333: return IntArray::of(333, 92, 150);
				case 334: return IntArray::of(334, 92, 72);
				case 335: return IntArray::of(335, 89, 166);
				case 336: return IntArray::of(336, 92, 72);
				case 338: return IntArray::of(338, 92, 295);
				case 339: return IntArray::of(339, 4, 148);
				case 341: return IntArray::of(341, 92, 173);
				case 342: return IntArray::of(342, 92, 175);
				case 343: return IntArray::of(343, 92, 72);
				case 344: return IntArray::of(344, 92, 72);
				case 347: return IntArray::of(347, 92, 155);
				case 349: return IntArray::of(349, 92, 155);
				case 350: return IntArray::of(350, 92, 175);
				case 351: return IntArray::of(351, 60, 80);
				case 352: return IntArray::of(352, 92, 267);
				case 353: return IntArray::of(353, 92, 141);
				case 354: return IntArray::of(354, 92, 79);
				case 355: return IntArray::of(355, 33, 145);
				case 356: return IntArray::of(356, 33, 145);
				case 357: return IntArray::of(357, 92, 141);
				case 358: 
					if (script == 125) return IntArray::of(358, 125, 125);
					if (region == 125) return IntArray::of(358, 125, 125);
					return IntArray::of(358, 92, 124);
				case 359: return IntArray::of(359, 92, 155);
				case 361: return IntArray::of(361, 31, 232);
				case 362: return IntArray::of(362, 92, 141);
				case 363: return IntArray::of(363, 92, 244);
				case 364: return IntArray::of(364, 92, 155);
				case 365: return IntArray::of(365, 92, 194);
				case 366: return IntArray::of(366, 92, 182);
				case 368: return IntArray::of(368, 92, 199);
				case 369: return IntArray::of(369, 92, 79);
				case 370: return IntArray::of(370, 92, 183);
				case 371: return IntArray::of(371, 92, 150);
				case 372: return IntArray::of(372, 92, 211);
				case 373: return IntArray::of(373, 92, 70);
				case 374: return IntArray::of(374, 92, 141);
				case 375: return IntArray::of(375, 31, 184);
				case 376: return IntArray::of(376, 111, 145);
				case 377: 
					if (script == 113) return IntArray::of(377, 113, 80);
					if (region == 80) return IntArray::of(377, 113, 80);
					return IntArray::of(377, 31, 187);
				case 379: return IntArray::of(379, 13, 145);
				case 380: return IntArray::of(380, 92, 70);
				case 381: return IntArray::of(381, 92, 70);
				case 382: return IntArray::of(382, 92, 52);
				case 383: return IntArray::of(383, 33, 145);
				case 384: return IntArray::of(384, 31, 232);
				case 385: 
					if (region == 71) return IntArray::of(385, 4, 71);
					return IntArray::of(385, 92, 198);
				case 386: return IntArray::of(386, 92, 193);
				case 387: return IntArray::of(387, 92, 79);
				case 389: return IntArray::of(389, 92, 276);
				case 391: return IntArray::of(391, 33, 145);
				case 392: return IntArray::of(392, 92, 141);
				case 393: return IntArray::of(393, 118, 186);
				case 395: return IntArray::of(395, 31, 232);
				case 396: return IntArray::of(396, 4, 148);
				case 397: return IntArray::of(397, 92, 209);
				case 398: return IntArray::of(398, 60, 80);
				case 399: return IntArray::of(399, 92, 150);
				case 400: return IntArray::of(400, 92, 200);
				case 401: return IntArray::of(401, 92, 207);
				case 402: return IntArray::of(402, 92, 296);
				case 403: return IntArray::of(403, 92, 92);
				case 404: return IntArray::of(404, 33, 208);
				case 405: return IntArray::of(405, 33, 208);
				case 406: return IntArray::of(406, 92, 200);
				case 408: return IntArray::of(408, 92, 210);
				case 409: return IntArray::of(409, 92, 145);
				case 410: return IntArray::of(410, 92, 206);
				case 411: return IntArray::of(411, 92, 79);
				case 412: return IntArray::of(412, 92, 207);
				case 413: return IntArray::of(413, 92, 79);
				case 414: return IntArray::of(414, 92, 207);
				case 416: return IntArray::of(416, 149, 238);
				case 418: return IntArray::of(418, 125, 125);
				case 419: return IntArray::of(419, 92, 294);
				case 420: return IntArray::of(420, 92, 294);
				case 421: return IntArray::of(421, 92, 249);
				case 422: return IntArray::of(422, 92, 276);
				case 424: return IntArray::of(424, 92, 196);
				case 425: return IntArray::of(425, 92, 271);
				case 426: return IntArray::of(426, 92, 273);
				case 428: return IntArray::of(428, 92, 121);
				case 429: return IntArray::of(429, 92, 114);
				case 430: return IntArray::of(430, 22, 70);
				case 434: return IntArray::of(434, 22, 70);
				case 436: return IntArray::of(436, 92, 70);
				case 437: return IntArray::of(437, 92, 106);
				case 438: return IntArray::of(438, 131, 145);
				case 439: return IntArray::of(439, 31, 118);
				case 440: return IntArray::of(440, 132, 276);
				case 442: 
					if (script == 4) return IntArray::of(442, 4, 218);
					if (region == 218) return IntArray::of(442, 4, 218);
					return IntArray::of(442, 55, 145);
				case 443: return IntArray::of(443, 92, 217);
				case 444: 
					if (script == 140) return IntArray::of(444, 140, 80);
					return IntArray::of(444, 139, 148);
				case 445: return IntArray::of(445, 92, 217);
				case 446: return IntArray::of(446, 92, 87);
				case 447: return IntArray::of(447, 92, 225);
				case 448: return IntArray::of(448, 92, 114);
				case 449: return IntArray::of(449, 92, 204);
				case 450: return IntArray::of(450, 92, 276);
				case 451: return IntArray::of(451, 92, 70);
				case 452: return IntArray::of(452, 197, 148);
				case 453: return IntArray::of(453, 92, 92);
				case 454: return IntArray::of(454, 142, 167);
				case 456: return IntArray::of(456, 92, 235);
				case 457: return IntArray::of(457, 92, 219);
				case 458: return IntArray::of(458, 92, 150);
				case 459: return IntArray::of(459, 52, 128);
				case 460: return IntArray::of(460, 92, 112);
				case 461: return IntArray::of(461, 92, 70);
				case 462: return IntArray::of(462, 92, 219);
				case 464: return IntArray::of(464, 4, 34);
				case 465: return IntArray::of(465, 92, 62);
				case 466: return IntArray::of(466, 92, 214);
				case 467: return IntArray::of(467, 92, 130);
				case 468: return IntArray::of(468, 92, 100);
				case 469: return IntArray::of(469, 33, 145);
				case 472: return IntArray::of(472, 92, 150);
				case 473: return IntArray::of(473, 147, 186);
				case 474: return IntArray::of(474, 92, 177);
				case 475: return IntArray::of(475, 92, 75);
				case 476: return IntArray::of(476, 92, 55);
				case 477: return IntArray::of(477, 92, 230);
				case 478: return IntArray::of(478, 92, 271);
				case 481: return IntArray::of(481, 92, 110);
				case 482: return IntArray::of(482, 31, 232);
				case 483: return IntArray::of(483, 31, 272);
				case 484: return IntArray::of(484, 92, 235);
				case 486: return IntArray::of(486, 92, 233);
				case 487: return IntArray::of(487, 92, 271);
				case 488: return IntArray::of(488, 33, 145);
				case 490: return IntArray::of(490, 31, 232);
				case 492: return IntArray::of(492, 92, 155);
				case 493: return IntArray::of(493, 92, 141);
				case 494: return IntArray::of(494, 128, 145);
				case 495: return IntArray::of(495, 153, 145);
				case 497: return IntArray::of(497, 92, 271);
				case 498: return IntArray::of(498, 92, 150);
				case 499: return IntArray::of(499, 92, 150);
				case 500: return IntArray::of(500, 92, 116);
				case 501: 
					if (script == 158) return IntArray::of(501, 158, 145);
					if (script == 81) return IntArray::of(501, 81, 145);
					if (script == 33) return IntArray::of(501, 33, 145);
					if (region == 145) return IntArray::of(501, 33, 145);
					return IntArray::of(501, 4, 218);
				case 502: return IntArray::of(502, 92, 150);
				case 503: return IntArray::of(503, 4, 148);
				case 504: return IntArray::of(504, 92, 207);
				case 506: return IntArray::of(506, 92, 199);
				case 507: return IntArray::of(507, 92, 197);
				case 509: return IntArray::of(509, 92, 185);
				case 510: return IntArray::of(510, 92, 73);
				case 511: return IntArray::of(511, 127, 142);
				case 512: return IntArray::of(512, 92, 173);
				case 514: return IntArray::of(514, 180, 177);
				case 515: return IntArray::of(515, 118, 186);
				case 517: return IntArray::of(517, 159, 170);
				case 518: return IntArray::of(518, 92, 106);
				case 519: return IntArray::of(519, 92, 243);
				case 520: return IntArray::of(520, 4, 218);
				case 521: return IntArray::of(521, 92, 241);
				case 523: return IntArray::of(523, 92, 219);
				case 524: return IntArray::of(524, 92, 141);
				case 525: return IntArray::of(525, 92, 287);
				case 526: return IntArray::of(526, 92, 238);
				case 527: return IntArray::of(527, 92, 238);
				case 528: return IntArray::of(528, 92, 109);
				case 529: return IntArray::of(529, 92, 109);
				case 530: return IntArray::of(530, 92, 296);
				case 531: return IntArray::of(531, 92, 185);
				case 532: return IntArray::of(532, 92, 247);
				case 533: return IntArray::of(533, 160, 278);
				case 534: return IntArray::of(534, 92, 37);
				case 535: 
					if (region == 267) return IntArray::of(535, 92, 267);
					if (region == 232) return IntArray::of(535, 92, 232);
					if (region == 230) return IntArray::of(535, 92, 230);
					if (region == 180) return IntArray::of(535, 92, 180);
					return IntArray::of(535, 31, 231);
				case 536: return IntArray::of(536, 92, 248);
				case 537: return IntArray::of(537, 92, 246);
				case 538: return IntArray::of(538, 92, 294);
				case 539: return IntArray::of(539, 92, 104);
				case 540: return IntArray::of(540, 92, 294);
				case 541: return IntArray::of(541, 92, 92);
				case 543: return IntArray::of(543, 92, 141);
				case 544: return IntArray::of(544, 92, 271);
				case 545: return IntArray::of(545, 92, 125);
				case 547: return IntArray::of(547, 92, 238);
				case 548: return IntArray::of(548, 92, 271);
				case 549: return IntArray::of(549, 4, 292);
				case 551: return IntArray::of(551, 167, 147);
				case 552: return IntArray::of(552, 92, 219);
				case 553: return IntArray::of(553, 175, 145);
				case 555: return IntArray::of(555, 83, 145);
				case 556: return IntArray::of(556, 178, 145);
				case 557: return IntArray::of(557, 92, 244);
				case 558: return IntArray::of(558, 92, 273);
				case 560: return IntArray::of(560, 92, 263);
				case 561: 
					if (script == 4) return IntArray::of(561, 4, 218);
					if (region == 218) return IntArray::of(561, 4, 218);
					return IntArray::of(561, 31, 261);
				case 563: return IntArray::of(563, 183, 260);
				case 565: return IntArray::of(565, 43, 106);
				case 566: return IntArray::of(566, 43, 104);
				case 567: return IntArray::of(567, 92, 204);
				case 568: return IntArray::of(568, 92, 264);
				case 569: return IntArray::of(569, 92, 262);
				case 570: return IntArray::of(570, 92, 47);
				case 571: return IntArray::of(571, 92, 217);
				case 574: return IntArray::of(574, 92, 47);
				case 575: return IntArray::of(575, 92, 202);
				case 576: return IntArray::of(576, 92, 294);
				case 577: return IntArray::of(577, 92, 266);
				case 578: return IntArray::of(578, 92, 196);
				case 579: return IntArray::of(579, 92, 0);
				case 580: return IntArray::of(580, 92, 216);
				case 581: return IntArray::of(581, 92, 267);
				case 582: return IntArray::of(582, 92, 267);
				case 583: return IntArray::of(583, 92, 270);
				case 584: return IntArray::of(584, 4, 218);
				case 585: return IntArray::of(585, 92, 294);
				case 586: return IntArray::of(586, 52, 128);
				case 588: return IntArray::of(588, 31, 232);
				case 590: return IntArray::of(590, 92, 47);
				case 591: return IntArray::of(591, 92, 196);
				case 592: return IntArray::of(592, 92, 269);
				case 594: return IntArray::of(594, 92, 202);
				case 595: return IntArray::of(595, 92, 215);
				case 596: return IntArray::of(596, 31, 232);
				case 597: return IntArray::of(597, 92, 177);
				case 598: return IntArray::of(598, 31, 232);
				case 599: 
					if (script == 31) return IntArray::of(599, 31, 165);
					if (region == 187) return IntArray::of(599, 31, 187);
					if (region == 165) return IntArray::of(599, 31, 165);
					return IntArray::of(599, 4, 80);
				case 600: return IntArray::of(600, 190, 253);
				case 601: return IntArray::of(601, 31, 272);
				case 602: return IntArray::of(602, 92, 39);
				case 604: return IntArray::of(604, 4, 218);
				case 605: 
					if (script == 4) return IntArray::of(605, 4, 34);
					if (region == 80) return IntArray::of(605, 31, 80);
					if (region == 34) return IntArray::of(605, 4, 34);
					return IntArray::of(605, 92, 278);
				case 606: return IntArray::of(606, 191, 171);
				case 607: return IntArray::of(607, 92, 294);
				case 608: return IntArray::of(608, 92, 150);
				case 609: return IntArray::of(609, 92, 232);
				case 610: return IntArray::of(610, 92, 284);
				case 611: return IntArray::of(611, 92, 51);
				case 612: return IntArray::of(612, 92, 92);
				case 613: return IntArray::of(613, 92, 199);
				case 614: return IntArray::of(614, 92, 0);
				case 615: return IntArray::of(615, 92, 232);
				case 616: return IntArray::of(616, 92, 101);
				case 617: return IntArray::of(617, 92, 271);
				case 618: return IntArray::of(618, 92, 51);
				case 619: return IntArray::of(619, 92, 75);
				case 620: return IntArray::of(620, 43, 106);
				case 621: return IntArray::of(621, 92, 217);
				case 623: return IntArray::of(623, 92, 44);
				case 624: return IntArray::of(624, 92, 246);
				case 625: return IntArray::of(625, 60, 80);
				case 627: return IntArray::of(627, 92, 294);
				case 628: return IntArray::of(628, 46, 118);
				case 629: return IntArray::of(629, 33, 145);
				case 630: return IntArray::of(630, 92, 273);
				case 631: return IntArray::of(631, 92, 199);
				case 632: return IntArray::of(632, 92, 112);
				case 633: return IntArray::of(633, 92, 79);
				case 634: return IntArray::of(634, 92, 79);
				case 635: return IntArray::of(635, 63, 272);
				case 636: return IntArray::of(636, 92, 204);
				case 637: return IntArray::of(637, 92, 62);
				case 638: 
					if (script == 60) return IntArray::of(638, 60, 80);
					if (region == 80) return IntArray::of(638, 60, 80);
					return IntArray::of(638, 61, 134);
				case 639: return IntArray::of(639, 92, 80);
				case 642: return IntArray::of(642, 92, 206);
				case 644: return IntArray::of(644, 180, 177);
				case 645: 
					if (script == 61) return IntArray::of(645, 61, 270);
					if (script == 56) return IntArray::of(645, 56, 270);
					if (script == 16) return IntArray::of(645, 16, 270);
					if (region == 284) return IntArray::of(645, 61, 284);
					if (region == 276) return IntArray::of(645, 61, 276);
					if (region == 270) return IntArray::of(645, 61, 270);
					if (region == 260) return IntArray::of(645, 61, 260);
					if (region == 248) return IntArray::of(645, 61, 248);
					if (region == 217) return IntArray::of(645, 61, 217);
					if (region == 215) return IntArray::of(645, 61, 215);
					if (region == 213) return IntArray::of(645, 61, 213);
					if (region == 188) return IntArray::of(645, 61, 188);
					if (region == 141) return IntArray::of(645, 61, 141);
					if (region == 134) return IntArray::of(645, 61, 134);
					if (region == 119) return IntArray::of(645, 61, 119);
					if (region == 116) return IntArray::of(645, 61, 116);
					if (region == 59) return IntArray::of(645, 61, 59);
					if (region == 44) return IntArray::of(645, 61, 44);
					return IntArray::of(645, 60, 80);
				case 646: return IntArray::of(646, 92, 294);
				case 649: return IntArray::of(649, 92, 267);
				case 603: 
					if (script == 200) return IntArray::of(242, 200, 80);
					if (script == 199) return IntArray::of(310, 199, 118);
					if (script == 198) return IntArray::of(14, 198, 147);
					if (script == 197) return IntArray::of(452, 197, 148);
					if (script == 193) return IntArray::of(534, 193, 37);
					if (script == 191) return IntArray::of(606, 191, 171);
					if (script == 190) return IntArray::of(600, 190, 253);
					if (script == 189) return IntArray::of(488, 189, 145);
					if (script == 187) return IntArray::of(534, 187, 37);
					if (script == 185) return IntArray::of(356, 185, 145);
					if (script == 184 && region == 64) return IntArray::of(148, 184, 64);
					if (script == 184) return IntArray::of(75, 184, 80);
					if (script == 183) return IntArray::of(563, 183, 260);
					if (script == 182) return IntArray::of(145, 182, 195);
					if (script == 181) return IntArray::of(172, 181, 217);
					if (script == 180) return IntArray::of(644, 180, 177);
					if (script == 178) return IntArray::of(556, 178, 145);
					if (script == 177) return IntArray::of(72, 177, 284);
					if (script == 175) return IntArray::of(553, 175, 145);
					if (script == 172) return IntArray::of(140, 172, 145);
					if (script == 167) return IntArray::of(551, 167, 147);
					if (script == 164) return IntArray::of(543, 164, 141);
					if (script == 161) return IntArray::of(533, 161, 278);
					if (script == 160) return IntArray::of(533, 160, 278);
					if (script == 159) return IntArray::of(517, 159, 170);
					if (script == 158) return IntArray::of(501, 158, 145);
					if (script == 157) return IntArray::of(488, 157, 145);
					if (script == 156) return IntArray::of(488, 156, 145);
					if (script == 155) return IntArray::of(158, 155, 116);
					if (script == 154) return IntArray::of(37, 154, 276);
					if (script == 153) return IntArray::of(495, 153, 145);
					if (script == 149) return IntArray::of(416, 149, 238);
					if (script == 147) return IntArray::of(473, 147, 186);
					if (script == 142) return IntArray::of(454, 142, 167);
					if (script == 140) return IntArray::of(444, 140, 80);
					if (script == 139) return IntArray::of(444, 139, 148);
					if (script == 138) return IntArray::of(351, 138, 80);
					if (script == 137) return IntArray::of(313, 137, 232);
					if (script == 135) return IntArray::of(26, 135, 253);
					if (script == 133) return IntArray::of(532, 133, 247);
					if (script == 132) return IntArray::of(440, 132, 276);
					if (script == 131) return IntArray::of(438, 131, 145);
					if (script == 128) return IntArray::of(494, 128, 145);
					if (script == 127) return IntArray::of(511, 127, 142);
					if (script == 125 && region == 185) return IntArray::of(73, 125, 185);
					if (script == 125) return IntArray::of(358, 125, 125);
					if (script == 123) return IntArray::of(405, 123, 208);
					if (script == 122) return IntArray::of(26, 122, 153);
					if (script == 120) return IntArray::of(488, 120, 145);
					if (script == 118) return IntArray::of(393, 118, 186);
					if (script == 117) return IntArray::of(520, 117, 218);
					if (script == 116) return IntArray::of(379, 116, 145);
					if (script == 113) return IntArray::of(377, 113, 80);
					if (script == 112) return IntArray::of(383, 112, 145);
					if (script == 111) return IntArray::of(376, 111, 145);
					if (script == 108) return IntArray::of(363, 108, 244);
					if (script == 105) return IntArray::of(75, 105, 80);
					if (script == 102) return IntArray::of(357, 102, 141);
					if (script == 101) return IntArray::of(220, 101, 145);
					if (script == 96) return IntArray::of(205, 96, 128);
					if (script == 92 && region == 295) return IntArray::of(158, 92, 295);
					if (script == 92 && region == 291) return IntArray::of(158, 92, 291);
					if (script == 92 && region == 272) return IntArray::of(457, 92, 272);
					if (script == 92 && region == 270) return IntArray::of(583, 92, 270);
					if (script == 92 && region == 265) return IntArray::of(177, 92, 265);
					if (script == 92 && region == 262) return IntArray::of(158, 92, 262);
					if (script == 92 && region == 260) return IntArray::of(158, 92, 260);
					if (script == 92 && region == 253) return IntArray::of(177, 92, 253);
					if (script == 92 && region == 249) return IntArray::of(158, 92, 249);
					if (script == 92 && region == 244) return IntArray::of(158, 92, 244);
					if (script == 92 && region == 237) return IntArray::of(158, 92, 237);
					if (script == 92 && region == 232) return IntArray::of(304, 92, 232);
					if (script == 92 && region == 218) return IntArray::of(158, 92, 218);
					if (script == 92 && region == 208) return IntArray::of(158, 92, 208);
					if (script == 92 && region == 195) return IntArray::of(158, 92, 195);
					if (script == 92 && region == 194) return IntArray::of(158, 92, 194);
					if (script == 92 && region == 191) return IntArray::of(177, 92, 191);
					if (script == 92 && region == 188) return IntArray::of(465, 92, 188);
					if (script == 92 && region == 186) return IntArray::of(268, 92, 186);
					if (script == 92 && region == 184) return IntArray::of(534, 92, 184);
					if (script == 92 && region == 177) return IntArray::of(177, 92, 177);
					if (script == 92 && region == 170) return IntArray::of(158, 92, 170);
					if (script == 92 && region == 167) return IntArray::of(158, 92, 167);
					if (script == 92 && region == 165) return IntArray::of(158, 92, 165);
					if (script == 92 && region == 159) return IntArray::of(177, 92, 159);
					if (script == 92 && region == 153) return IntArray::of(158, 92, 153);
					if (script == 92 && region == 148) return IntArray::of(568, 92, 148);
					if (script == 92 && region == 147) return IntArray::of(158, 92, 147);
					if (script == 92 && region == 145) return IntArray::of(158, 92, 145);
					if (script == 92 && region == 143) return IntArray::of(158, 92, 143);
					if (script == 92 && region == 134) return IntArray::of(158, 92, 134);
					if (script == 92 && region == 128) return IntArray::of(158, 92, 128);
					if (script == 92 && region == 118) return IntArray::of(310, 92, 118);
					if (script == 92 && region == 106) return IntArray::of(158, 92, 106);
					if (script == 92 && region == 104) return IntArray::of(158, 92, 104);
					if (script == 92 && region == 102) return IntArray::of(158, 92, 102);
					if (script == 92 && region == 98) return IntArray::of(177, 92, 98);
					if (script == 92 && region == 89) return IntArray::of(581, 92, 89);
					if (script == 92 && region == 80) return IntArray::of(639, 92, 80);
					if (script == 92 && region == 71) return IntArray::of(158, 92, 71);
					if (script == 92 && region == 64) return IntArray::of(158, 92, 64);
					if (script == 92 && region == 53) return IntArray::of(158, 92, 53);
					if (script == 92 && region == 50) return IntArray::of(158, 92, 50);
					if (script == 92 && region == 38) return IntArray::of(310, 92, 38);
					if (script == 92 && region == 34) return IntArray::of(568, 92, 34);
					if (script == 92 && region == 33) return IntArray::of(158, 92, 33);
					if (script == 92 && region == 0) return IntArray::of(158, 92, 276);
					if (script == 89) return IntArray::of(335, 89, 166);
					if (script == 87) return IntArray::of(64, 87, 145);
					if (script == 84) return IntArray::of(295, 84, 162);
					if (script == 83) return IntArray::of(294, 83, 145);
					if (script == 81) return IntArray::of(501, 81, 145);
					if (script == 80) return IntArray::of(292, 80, 157);
					if (script == 78) return IntArray::of(271, 78, 141);
					if (script == 77) return IntArray::of(255, 77, 154);
					if (script == 74) return IntArray::of(255, 74, 154);
					if (script == 73) return IntArray::of(264, 73, 141);
					if (script == 72) return IntArray::of(295, 72, 162);
					if (script == 69) return IntArray::of(231, 69, 139);
					if (script == 67) return IntArray::of(225, 67, 276);
					if (script == 66) return IntArray::of(225, 66, 166);
					if (script == 64) return IntArray::of(255, 64, 154);
					if (script == 63 && region == 276) return IntArray::of(635, 63, 276);
					if (script == 63 && region == 272) return IntArray::of(635, 63, 272);
					if (script == 63 && region == 238) return IntArray::of(635, 63, 238);
					if (script == 63) return IntArray::of(219, 63, 143);
					if (script == 62) return IntArray::of(26, 62, 147);
					if (script == 61 && region == 80) return IntArray::of(638, 61, 80);
					if (script == 61 && region == 70) return IntArray::of(638, 61, 70);
					if (script == 61) return IntArray::of(645, 61, 270);
					if (script == 60) return IntArray::of(645, 60, 80);
					if (script == 58) return IntArray::of(645, 58, 80);
					if (script == 57) return IntArray::of(295, 57, 162);
					if (script == 56) return IntArray::of(645, 56, 270);
					if (script == 55) return IntArray::of(442, 55, 145);
					if (script == 53) return IntArray::of(207, 53, 145);
					if (script == 52) return IntArray::of(156, 52, 128);
					if (script == 51) return IntArray::of(488, 51, 145);
					if (script == 50) return IntArray::of(203, 50, 272);
					if (script == 47) return IntArray::of(126, 47, 53);
					if (script == 46) return IntArray::of(265, 46, 118);
					if (script == 44) return IntArray::of(624, 44, 246);
					if (script == 43 && region == 104) return IntArray::of(565, 43, 104);
					if (script == 43) return IntArray::of(19, 43, 106);
					if (script == 42) return IntArray::of(26, 42, 148);
					if (script == 41) return IntArray::of(534, 41, 37);
					if (script == 40) return IntArray::of(154, 40, 102);
					if (script == 37) return IntArray::of(177, 37, 114);
					if (script == 35) return IntArray::of(140, 35, 145);
					if (script == 34) return IntArray::of(145, 34, 195);
					if (script == 33 && region == 208) return IntArray::of(404, 33, 208);
					if (script == 33 && region == 194) return IntArray::of(64, 33, 194);
					if (script == 33 && region == 110) return IntArray::of(221, 33, 110);
					if (script == 33 && region == 64) return IntArray::of(404, 33, 64);
					if (script == 33) return IntArray::of(220, 33, 145);
					if (script == 31 && region == 290) return IntArray::of(535, 31, 290);
					if (script == 31 && region == 278) return IntArray::of(605, 31, 278);
					if (script == 31 && region == 272) return IntArray::of(601, 31, 272);
					if (script == 31 && region == 267) return IntArray::of(272, 31, 267);
					if (script == 31 && region == 261) return IntArray::of(561, 31, 261);
					if (script == 31 && region == 243) return IntArray::of(601, 31, 243);
					if (script == 31 && region == 231) return IntArray::of(535, 31, 231);
					if (script == 31 && region == 230) return IntArray::of(60, 31, 230);
					if (script == 31 && region == 187) return IntArray::of(377, 31, 187);
					if (script == 31 && region == 184) return IntArray::of(375, 31, 184);
					if (script == 31 && region == 180) return IntArray::of(535, 31, 180);
					if (script == 31 && region == 179) return IntArray::of(601, 31, 179);
					if (script == 31 && region == 156) return IntArray::of(317, 31, 156);
					if (script == 31 && region == 148) return IntArray::of(266, 31, 148);
					if (script == 31 && region == 128) return IntArray::of(375, 31, 128);
					if (script == 31 && region == 118) return IntArray::of(1, 31, 118);
					if (script == 31 && region == 68) return IntArray::of(53, 31, 68);
					if (script == 31 && region == 53) return IntArray::of(60, 31, 53);
					if (script == 31 && region == 48) return IntArray::of(535, 31, 48);
					if (script == 31 && region == 47) return IntArray::of(44, 31, 47);
					if (script == 31 && region == 37) return IntArray::of(375, 31, 37);
					if (script == 31 && region == 34) return IntArray::of(266, 31, 34);
					if (script == 31) return IntArray::of(482, 31, 232);
					if (script == 30) return IntArray::of(205, 30, 89);
					if (script == 29) return IntArray::of(603, 29, 89);
					if (script == 28) return IntArray::of(112, 28, 102);
					if (script == 25) return IntArray::of(106, 25, 276);
					if (script == 22) return IntArray::of(252, 22, 70);
					if (script == 21) return IntArray::of(94, 21, 50);
					if (script == 19) return IntArray::of(85, 19, 141);
					if (script == 18) return IntArray::of(177, 18, 114);
					if (script == 16) return IntArray::of(645, 16, 270);
					if (script == 14) return IntArray::of(488, 14, 145);
					if (script == 13) return IntArray::of(74, 13, 50);
					if (script == 12) return IntArray::of(51, 12, 141);
					if (script == 10) return IntArray::of(50, 10, 79);
					if (script == 9) return IntArray::of(47, 9, 141);
					if (script == 8) return IntArray::of(6, 8, 148);
					if (script == 7) return IntArray::of(234, 7, 38);
					if (script == 6) return IntArray::of(26, 6, 148);
					if (script == 4 && region == 292) return IntArray::of(549, 4, 292);
					if (script == 4 && region == 267) return IntArray::of(24, 4, 267);
					if (script == 4 && region == 261) return IntArray::of(167, 4, 261);
					if (script == 4 && region == 218) return IntArray::of(604, 4, 218);
					if (script == 4 && region == 204) return IntArray::of(213, 4, 204);
					if (script == 4 && region == 194) return IntArray::of(604, 4, 194);
					if (script == 4 && region == 187) return IntArray::of(288, 4, 187);
					if (script == 4 && region == 186) return IntArray::of(473, 4, 186);
					if (script == 4 && region == 148) return IntArray::of(167, 4, 148);
					if (script == 4 && region == 145) return IntArray::of(604, 4, 145);
					if (script == 4 && region == 141) return IntArray::of(385, 4, 141);
					if (script == 4 && region == 116) return IntArray::of(604, 4, 116);
					if (script == 4 && region == 80) return IntArray::of(599, 4, 80);
					if (script == 4 && region == 71) return IntArray::of(385, 4, 71);
					if (script == 4 && region == 59) return IntArray::of(385, 4, 59);
					if (script == 4 && region == 34) return IntArray::of(167, 4, 34);
					if (script == 4) return IntArray::of(25, 4, 102);
					if (script == 0) return IntArray::of(170, 0, 125);
					if (region == 296) return IntArray::of(530, 92, 296);
					if (region == 295) return IntArray::of(55, 92, 295);
					if (region == 292) return IntArray::of(177, 92, 292);
					if (region == 291) return IntArray::of(25, 4, 291);
					if (region == 290) return IntArray::of(534, 92, 290);
					if (region == 287) return IntArray::of(525, 92, 287);
					if (region == 286) return IntArray::of(177, 92, 286);
					if (region == 285) return IntArray::of(65, 92, 285);
					if (region == 284) return IntArray::of(610, 92, 284);
					if (region == 281) return IntArray::of(161, 92, 281);
					if (region == 279) return IntArray::of(251, 92, 279);
					if (region == 278) return IntArray::of(605, 92, 278);
					if (region == 277) return IntArray::of(161, 92, 277);
					if (region == 273) return IntArray::of(548, 92, 273);
					if (region == 272) return IntArray::of(601, 31, 272);
					if (region == 271) return IntArray::of(548, 92, 271);
					if (region == 270) return IntArray::of(645, 61, 270);
					if (region == 269) return IntArray::of(592, 92, 269);
					if (region == 267) return IntArray::of(581, 92, 267);
					if (region == 266) return IntArray::of(577, 92, 266);
					if (region == 265) return IntArray::of(25, 4, 265);
					if (region == 264) return IntArray::of(568, 92, 264);
					if (region == 263) return IntArray::of(465, 92, 263);
					if (region == 262) return IntArray::of(569, 92, 262);
					if (region == 261) return IntArray::of(561, 31, 261);
					if (region == 260) return IntArray::of(563, 183, 260);
					if (region == 259) return IntArray::of(177, 92, 259);
					if (region == 258) return IntArray::of(177, 92, 258);
					if (region == 257) return IntArray::of(177, 92, 257);
					if (region == 253) return IntArray::of(25, 4, 253);
					if (region == 251) return IntArray::of(161, 92, 251);
					if (region == 250) return IntArray::of(465, 92, 250);
					if (region == 249) return IntArray::of(25, 4, 249);
					if (region == 248) return IntArray::of(410, 92, 248);
					if (region == 247) return IntArray::of(532, 92, 247);
					if (region == 246) return IntArray::of(177, 92, 246);
					if (region == 245) return IntArray::of(251, 92, 245);
					if (region == 244) return IntArray::of(302, 92, 244);
					if (region == 243) return IntArray::of(519, 92, 243);
					if (region == 242) return IntArray::of(401, 92, 242);
					if (region == 241) return IntArray::of(521, 92, 241);
					if (region == 238) return IntArray::of(547, 92, 238);
					if (region == 237) return IntArray::of(25, 4, 237);
					if (region == 236) return IntArray::of(177, 92, 236);
					if (region == 234) return IntArray::of(25, 4, 234);
					if (region == 233) return IntArray::of(486, 92, 233);
					if (region == 232) return IntArray::of(482, 31, 232);
					if (region == 231) return IntArray::of(535, 31, 231);
					if (region == 230) return IntArray::of(477, 92, 230);
					if (region == 229) return IntArray::of(177, 92, 229);
					if (region == 227) return IntArray::of(25, 4, 227);
					if (region == 226) return IntArray::of(199, 92, 226);
					if (region == 225) return IntArray::of(447, 92, 225);
					if (region == 224) return IntArray::of(465, 92, 224);
					if (region == 223) return IntArray::of(25, 4, 223);
					if (region == 222) return IntArray::of(161, 92, 222);
					if (region == 220) return IntArray::of(177, 92, 220);
					if (region == 219) return IntArray::of(457, 92, 219);
					if (region == 218) return IntArray::of(604, 4, 218);
					if (region == 217) return IntArray::of(172, 92, 217);
					if (region == 216) return IntArray::of(580, 92, 216);
					if (region == 215) return IntArray::of(177, 92, 215);
					if (region == 214) return IntArray::of(161, 92, 214);
					if (region == 213) return IntArray::of(161, 92, 213);
					if (region == 212) return IntArray::of(25, 4, 212);
					if (region == 208) return IntArray::of(404, 33, 208);
					if (region == 207) return IntArray::of(401, 92, 207);
					if (region == 206) return IntArray::of(410, 92, 206);
					if (region == 205) return IntArray::of(161, 92, 205);
					if (region == 202) return IntArray::of(213, 92, 202);
					if (region == 201) return IntArray::of(177, 92, 201);
					if (region == 200) return IntArray::of(8, 92, 200);
					if (region == 199) return IntArray::of(465, 92, 199);
					if (region == 198) return IntArray::of(385, 92, 198);
					if (region == 197) return IntArray::of(161, 92, 197);
					if (region == 195) return IntArray::of(145, 182, 195);
					if (region == 194) return IntArray::of(365, 92, 194);
					if (region == 193) return IntArray::of(386, 92, 193);
					if (region == 191) return IntArray::of(25, 4, 191);
					if (region == 190) return IntArray::of(177, 92, 190);
					if (region == 188) return IntArray::of(645, 61, 188);
					if (region == 187) return IntArray::of(377, 31, 187);
					if (region == 186) return IntArray::of(393, 118, 186);
					if (region == 185) return IntArray::of(73, 92, 185);
					if (region == 184) return IntArray::of(375, 31, 184);
					if (region == 182) return IntArray::of(366, 92, 182);
					if (region == 181) return IntArray::of(177, 92, 181);
					if (region == 180) return IntArray::of(535, 92, 180);
					if (region == 179) return IntArray::of(477, 92, 179);
					if (region == 178) return IntArray::of(177, 92, 178);
					if (region == 177) return IntArray::of(25, 4, 177);
					if (region == 176) return IntArray::of(25, 4, 176);
					if (region == 175) return IntArray::of(350, 92, 175);
					if (region == 174) return IntArray::of(177, 92, 174);
					if (region == 173) return IntArray::of(341, 92, 173);
					if (region == 172) return IntArray::of(540, 92, 172);
					if (region == 170) return IntArray::of(517, 159, 170);
					if (region == 169) return IntArray::of(134, 92, 169);
					if (region == 167) return IntArray::of(25, 4, 167);
					if (region == 166) return IntArray::of(335, 89, 166);
					if (region == 165) return IntArray::of(482, 31, 165);
					if (region == 163) return IntArray::of(25, 4, 163);
					if (region == 162) return IntArray::of(295, 84, 162);
					if (region == 161) return IntArray::of(295, 84, 161);
					if (region == 159) return IntArray::of(25, 4, 159);
					if (region == 157) return IntArray::of(292, 80, 157);
					if (region == 156) return IntArray::of(317, 31, 156);
					if (region == 155) return IntArray::of(548, 92, 155);
					if (region == 154) return IntArray::of(255, 74, 154);
					if (region == 153) return IntArray::of(25, 4, 153);
					if (region == 150) return IntArray::of(251, 92, 150);
					if (region == 149) return IntArray::of(250, 92, 149);
					if (region == 148) return IntArray::of(167, 4, 148);
					if (region == 147) return IntArray::of(25, 4, 147);
					if (region == 145) return IntArray::of(220, 33, 145);
					if (region == 143) return IntArray::of(219, 63, 143);
					if (region == 141) return IntArray::of(239, 92, 141);
					if (region == 140) return IntArray::of(161, 92, 140);
					if (region == 139) return IntArray::of(231, 92, 139);
					if (region == 138) return IntArray::of(230, 92, 138);
					if (region == 137) return IntArray::of(227, 92, 137);
					if (region == 136) return IntArray::of(161, 92, 136);
					if (region == 134) return IntArray::of(645, 61, 134);
					if (region == 132) return IntArray::of(465, 92, 132);
					if (region == 130) return IntArray::of(161, 92, 130);
					if (region == 128) return IntArray::of(156, 52, 128);
					if (region == 127) return IntArray::of(161, 92, 127);
					if (region == 126) return IntArray::of(177, 92, 126);
					if (region == 125) return IntArray::of(177, 92, 125);
					if (region == 123) return IntArray::of(290, 92, 123);
					if (region == 121) return IntArray::of(13, 92, 121);
					if (region == 119) return IntArray::of(177, 92, 119);
					if (region == 118) return IntArray::of(265, 46, 118);
					if (region == 115) return IntArray::of(177, 92, 115);
					if (region == 114) return IntArray::of(177, 92, 114);
					if (region == 113) return IntArray::of(175, 92, 113);
					if (region == 109) return IntArray::of(171, 92, 109);
					if (region == 106) return IntArray::of(19, 43, 106);
					if (region == 105) return IntArray::of(161, 92, 105);
					if (region == 104) return IntArray::of(565, 43, 104);
					if (region == 103) return IntArray::of(25, 4, 103);
					if (region == 102) return IntArray::of(25, 4, 102);
					if (region == 101) return IntArray::of(163, 92, 101);
					if (region == 100) return IntArray::of(161, 92, 100);
					if (region == 99) return IntArray::of(161, 92, 99);
					if (region == 98) return IntArray::of(25, 4, 98);
					if (region == 97) return IntArray::of(161, 92, 97);
					if (region == 95) return IntArray::of(130, 92, 95);
					if (region == 94) return IntArray::of(0, 92, 94);
					if (region == 92) return IntArray::of(134, 92, 92);
					if (region == 90) return IntArray::of(123, 92, 90);
					if (region == 89) return IntArray::of(156, 52, 89);
					if (region == 87) return IntArray::of(446, 92, 87);
					if (region == 86) return IntArray::of(465, 92, 86);
					if (region == 85) return IntArray::of(161, 92, 85);
					if (region == 84) return IntArray::of(161, 92, 84);
					if (region == 81) return IntArray::of(161, 92, 81);
					if (region == 80) return IntArray::of(645, 60, 80);
					if (region == 79) return IntArray::of(177, 92, 79);
					if (region == 78) return IntArray::of(161, 92, 78);
					if (region == 76) return IntArray::of(177, 92, 76);
					if (region == 75) return IntArray::of(134, 92, 75);
					if (region == 74) return IntArray::of(177, 92, 74);
					if (region == 73) return IntArray::of(177, 92, 73);
					if (region == 72) return IntArray::of(548, 92, 72);
					if (region == 71) return IntArray::of(385, 4, 71);
					if (region == 68) return IntArray::of(53, 31, 68);
					if (region == 64) return IntArray::of(148, 184, 64);
					if (region == 62) return IntArray::of(465, 92, 62);
					if (region == 61) return IntArray::of(446, 92, 61);
					if (region == 60) return IntArray::of(161, 92, 60);
					if (region == 59) return IntArray::of(385, 92, 59);
					if (region == 57) return IntArray::of(177, 92, 57);
					if (region == 56) return IntArray::of(177, 92, 56);
					if (region == 55) return IntArray::of(476, 92, 55);
					if (region == 54) return IntArray::of(25, 4, 54);
					if (region == 53) return IntArray::of(60, 31, 53);
					if (region == 52) return IntArray::of(177, 92, 52);
					if (region == 51) return IntArray::of(410, 92, 51);
					if (region == 50) return IntArray::of(74, 13, 50);
					if (region == 48) return IntArray::of(82, 92, 48);
					if (region == 47) return IntArray::of(44, 92, 47);
					if (region == 46) return IntArray::of(547, 92, 46);
					if (region == 45) return IntArray::of(410, 92, 45);
					if (region == 43) return IntArray::of(134, 92, 43);
					if (region == 42) return IntArray::of(525, 92, 42);
					if (region == 41) return IntArray::of(161, 92, 41);
					if (region == 39) return IntArray::of(465, 92, 39);
					if (region == 38) return IntArray::of(234, 7, 38);
					if (region == 37) return IntArray::of(534, 92, 37);
					if (region == 34) return IntArray::of(167, 4, 34);
					if (region == 33) return IntArray::of(25, 4, 33);
					if (region == 32) return IntArray::of(89, 92, 32);
					if (region == 30) return IntArray::of(161, 92, 30);
					if (region == 0) return IntArray::of(158, 92, 276);
					return IntArray::of(158, 92, 276);
				case 9: return IntArray::of(9, 92, 121);
				case 11: return IntArray::of(11, 77, 154);
				case 15: return IntArray::of(15, 92, 276);
				case 16: return IntArray::of(16, 92, 276);
				case 21: return IntArray::of(21, 92, 116);
				case 23: return IntArray::of(23, 33, 145);
				case 29: return IntArray::of(29, 92, 276);
				case 32: return IntArray::of(32, 92, 248);
				case 41: return IntArray::of(41, 92, 0);
				case 91: return IntArray::of(91, 92, 281);
				case 92: return IntArray::of(92, 92, 70);
				case 99: return IntArray::of(99, 92, 81);
				case 100: return IntArray::of(100, 4, 264);
				case 103: return IntArray::of(103, 92, 276);
				case 107: return IntArray::of(107, 92, 276);
				case 117: return IntArray::of(117, 22, 70);
				case 120: return IntArray::of(120, 22, 70);
				case 135: return IntArray::of(135, 92, 276);
				case 138: return IntArray::of(138, 92, 249);
				case 144: return IntArray::of(144, 92, 206);
				case 149: return IntArray::of(149, 92, 257);
				case 155: return IntArray::of(155, 92, 204);
				case 159: return IntArray::of(159, 92, 116);
				case 179: return IntArray::of(179, 92, 114);
				case 180: return IntArray::of(180, 92, 114);
				case 191: return IntArray::of(191, 92, 73);
				case 198: return IntArray::of(198, 92, 92);
				case 200: return IntArray::of(200, 92, 92);
				case 204: return IntArray::of(204, 92, 171);
				case 214: return IntArray::of(214, 92, 70);
				case 217: return IntArray::of(217, 92, 70);
				case 223: return IntArray::of(223, 198, 267);
				case 224: return IntArray::of(224, 92, 80);
				case 232: return IntArray::of(232, 92, 276);
				case 245: return IntArray::of(245, 92, 70);
				case 261: return IntArray::of(261, 63, 143);
				case 262: return IntArray::of(262, 63, 143);
				case 273: return IntArray::of(273, 92, 257);
				case 282: return IntArray::of(282, 17, 148);
				case 300: return IntArray::of(300, 92, 204);
				case 312: return IntArray::of(312, 92, 70);
				case 322: return IntArray::of(322, 92, 295);
				case 325: return IntArray::of(325, 92, 0);
				case 330: return IntArray::of(330, 92, 175);
				case 337: return IntArray::of(337, 92, 276);
				case 340: return IntArray::of(340, 92, 273);
				case 345: return IntArray::of(345, 92, 276);
				case 346: return IntArray::of(346, 92, 295);
				case 348: return IntArray::of(348, 92, 145);
				case 360: return IntArray::of(360, 4, 257);
				case 367: return IntArray::of(367, 91, 142);
				case 378: return IntArray::of(378, 113, 80);
				case 390: return IntArray::of(390, 92, 224);
				case 394: return IntArray::of(394, 92, 115);
				case 407: return IntArray::of(407, 92, 141);
				case 415: return IntArray::of(415, 31, 232);
				case 417: return IntArray::of(417, 92, 0);
				case 423: return IntArray::of(423, 123, 208);
				case 427: return IntArray::of(427, 92, 273);
				case 431: return IntArray::of(431, 92, 70);
				case 432: return IntArray::of(432, 92, 70);
				case 435: return IntArray::of(435, 92, 70);
				case 441: return IntArray::of(441, 4, 267);
				case 455: return IntArray::of(455, 159, 145);
				case 463: return IntArray::of(463, 92, 114);
				case 470: return IntArray::of(470, 92, 78);
				case 471: return IntArray::of(471, 92, 77);
				case 479: return IntArray::of(479, 92, 230);
				case 485: return IntArray::of(485, 92, 230);
				case 489: return IntArray::of(489, 92, 271);
				case 491: return IntArray::of(491, 150, 223);
				case 496: return IntArray::of(496, 92, 257);
				case 505: return IntArray::of(505, 92, 276);
				case 508: return IntArray::of(508, 31, 232);
				case 516: return IntArray::of(516, 4, 257);
				case 522: return IntArray::of(522, 92, 276);
				case 542: return IntArray::of(542, 92, 70);
				case 550: return IntArray::of(550, 167, 267);
				case 554: return IntArray::of(554, 92, 70);
				case 559: return IntArray::of(559, 92, 62);
				case 562: return IntArray::of(562, 92, 70);
				case 564: return IntArray::of(564, 92, 70);
				case 573: return IntArray::of(573, 92, 276);
				case 587: return IntArray::of(587, 92, 70);
				case 589: return IntArray::of(589, 92, 70);
				case 622: return IntArray::of(622, 92, 276);
				case 626: return IntArray::of(626, 31, 232);
				case 640: return IntArray::of(640, 92, 197);
				case 643: return IntArray::of(643, 180, 191);
				case 647: return IntArray::of(647, 92, 276);
            default: break;
            }
            return IntArray();
        }
        
        LongArray LikelySubtag::availableLocales() {
            return {
				6029406, 6029418, 4296999030, 8595964045, 
				12890931473, 17185898617, 21476868328, 25770328212, 
				30065033481, 34365767880, 34365767974, 38660735097, 
				42955702351, 47249686682, 55840604281, 60142518419, 
				64430539028, 68725506324, 73020473634, 77311443176, 
				81607196778, 85905375337, 90200342644, 94495310028, 
				98786410641, 103079477501, 103079477515, 107374444577, 
				107374444598, 107374444642, 107374444646, 107374444647, 
				107374444691, 107374444697, 107374444703, 107374444707, 
				107374444711, 107374444720, 107374444721, 107374444735, 
				107374444756, 107374444767, 107374444771, 107374444778, 
				107374444781, 107374444793, 107374444797, 107374444809, 
				107374444835, 111669543060, 111671902356, 111673213075, 
				111677145241, 111677997309, 115970146382, 120265113660, 
				124560081172, 128849281122, 133144248554, 137444983032, 
				141734183089, 146029150310, 150324707473, 154624852239, 
				158923882772, 163214786665, 167509753926, 171800723688, 
				176099688448, 180390789265, 184689623100, 188978823315, 
				188978823316, 188980592687, 188980592872, 188984590383, 
				193275560168, 197568757978, 201864052877, 201869492365, 
				206164459563, 210459426895, 214749020239, 219044118669, 
				219049361549, 223344328783, 227635298372, 231928496365, 
				236229230887, 240524198029, 244819165455, 249114132559, 
				253414539409, 257700069429, 257700069606, 261995167889, 
				266288234714, 274880069777, 274880069826, 274883608721, 
				279178903837, 283473871065, 287768838348, 292063805581, 
				296358772815, 300653740102, 304948707384, 309249245468, 
				313538642105, 313540804793, 317828431922, 322129428560, 
				322134605904, 326418366609, 330712744084, 335013478514, 
				339304579217, 343597646042, 347894513809, 352193347632, 
				356488314959, 360779284712, 365073465485, 365078249613, 
				369373216847, 373664972904, 377963151439, 382258118688, 
				382258118761, 386553086228, 390848053529, 395143020614, 
				399437988044, 403728302130, 408023924968, 412322889945, 
				416617857297, 420912824451, 425207791697, 429496992008, 
				433797726320, 438088696040, 442387661076, 446682628372, 
				450977595462, 455268172052, 459567530260, 463862497556, 
				468151697555, 472452431942, 476747399282, 481038172262, 
				485337333977, 489627713606, 493927268422, 498218238224, 
				502512615494, 506807582790, 511102550086, 515397517382, 
				523992039660, 528287006810, 532581974235, 536872353862, 
				541167911144, 541168959541, 545462878440, 554056810612, 
				558351777887, 562646745364, 566937714920, 571236679835, 
				575531647019, 575531647051, 575531647068, 575531647145, 
				579826614548, 584121581638, 588416548934, 592711516409, 
				597006483658, 601297584273, 601297715345, 601306693777, 
				605596418140, 609891385542, 614186352719, 618481320142, 
				622772486339, 622782185667, 627071254774, 631366221876, 
				635667218496, 639956156673, 644251123867, 648546091129, 
				652841058508, 657136025750, 661427585126, 665725960396, 
				670018306137, 670018306176, 678610862113, 678610862130, 
				678610862133, 678610862144, 678610862151, 678610862182, 
				678610862184, 678610862186, 678610862208, 678610862214, 
				678610862223, 678610862225, 678610862227, 678610862233, 
				678610862245, 678610862247, 678610862250, 678610862274, 
				678610862275, 678610862288, 678610862298, 678610862317, 
				678610862324, 678610862329, 678610862340, 678610862342, 
				678610862356, 678610862371, 678610862375, 678614990964, 
				682905829492, 687200796672, 691495763998, 691495764009, 
				691495764028, 691495764046, 691495764049, 691495764052, 
				691495764053, 691495764065, 691495764067, 691495764068, 
				691495764073, 691495764095, 691495764098, 691495764104, 
				691495764108, 691495764165, 691495764173, 691495764181, 
				691495764182, 691495764190, 691495764219, 691495764245, 
				691495764249, 695790731540, 700085698661, 704380665961, 
				708675633231, 712970600553, 717259800610, 717259800724, 
				717259800837, 721560535167, 730144440445, 730150469878, 
				734445437037, 738740404441, 738746237145, 743035371758, 
				747330338926, 751625306225, 755920273464, 760210391154, 
				760211636338, 760215240756, 760215240760, 760215240761, 
				760215240777, 760215240778, 760215240780, 760215240783, 
				760215240802, 760215240818, 760215240819, 760215240823, 
				760215240829, 760215240830, 760215240863, 760215240878, 
				760215240881, 760215240882, 760215240885, 760215240894, 
				760215240895, 760215240905, 760215240919, 760215240924, 
				760215240933, 760215240940, 760215240950, 760215240957, 
				760215240961, 760215240962, 760215240963, 760215240969, 
				760215240990, 760215240996, 764510208276, 768805175410, 
				773100142706, 777395110002, 781690077276, 785985044572, 
				790280011926, 794574979278, 798869946510, 803164913785, 
				807459881139, 811752751184, 816049815693, 820344782921, 
				824633983124, 828934717556, 833226473578, 837524652190, 
				841819619433, 846108819604, 850409554012, 854704521442, 
				858999488604, 863290589329, 867589423245, 871881638160, 
				876179357867, 880470261849, 880474587264, 884769292363, 
				889061703825, 893359226961, 897654194297, 901949161627, 
				906244128912, 910539096134, 914828296271, 914828296396, 
				914828296429, 914834063562, 914834063564, 919129030726, 
				923421900880, 927718965524, 932013932614, 940601966735, 
				944894967953, 944899424401, 949189935214, 953488769241, 
				957790683403, 962078703696, 966371967142, 966372032788, 
				970668638424, 974963605641, 979258572892, 983551443024, 
				987848507530, 992141967499, 992143474827, 996438442260, 
				1000733409350, 1005022806054, 1009323344072, 1013618311168, 
				1017913278662, 1022208245964, 1026503213197, 1030798180453, 
				1035093147852, 1039395192912, 1043683082516, 1052273016902, 
				1056567984345, 1060862951565, 1065153921256, 1069452886016, 
				1073747853461, 1078042820758, 1078042820853, 1078042820887, 
				1082333200454, 1086630854799, 1090927722728, 1095220854938, 
				1095221510298, 1095221706906, 1099517657240, 1103812624384, 
				1108107591759, 1112400658704, 1116697526543, 1120990593167, 
				1125285560463, 1129582428255, 1133876150413, 1133877395597, 
				1138169348214, 1142463332386, 1142463332500, 1142463332630, 
				1146762297442, 1151057264826, 1155352232140, 1159647199387, 
				1163941249165, 1168233136360, 1168233136395, 1172532101377, 
				1176827068620, 1181122035983, 1185417003094, 1189711970383, 
				1194006937676, 1198301904968, 1202596872254, 1206891839633, 
				1211181891732, 1215481774265, 1219770974426, 1224071708827, 
				1228366676235, 1232661643464, 1236950843426, 1236950843472, 
				1236950843540, 1236950843579, 1236952613029, 1241251577935, 
				1245546545275, 1249841512603, 1254135693469, 1258431447079, 
				1262725824657, 1267019088034, 1267020071074, 1267020857505, 
				1267020857506, 1271312351464, 1275607449745, 1279906283632, 
				1284201250987, 1288496218316, 1292787187944, 1297086152948, 
				1301381120217, 1305676087528, 1309967188113, 1314260254865, 
				1318560989455, 1322855956559, 1327150923868, 1331440124051, 
				1331440124071, 1331445891110, 1331445891190, 1331445891339, 
				1331452903542, 1335736860904, 1340035825734, 1344326795496, 
				1344333742312, 1348625760372, 1352920727622, 1357215694993, 
				1361504895056, 1361506664604, 1361510662411, 1365805629719, 
				1370098696335, 1374395564303, 1378684764378, 1382985498919, 
				1387280466094, 1391571435752, 1395870400512, 1400165368081, 
				1404460335310, 1408755302550, 1413050269766, 1417345237167, 
				1421640204564, 1425935171734, 1430230139030, 1434525106248, 
				1438819877030, 1443115040840, 1447410008340, 1451704975655, 
				1455994175636, 1460294910225, 1464589877421, 1468884844719, 
				1473179811912, 1477474779208, 1481769746708, 1486064714023, 
				1490359681179, 1494654648465, 1498949615771, 1503244583087, 
				1507537453136, 1507542564944, 1511834517771, 1516129484941, 
				1520424452175, 1524715552913, 1529010520209, 1529020481681, 
				1533309354125, 1533310009485, 1537604321404, 1537606484093, 
				1541899288731, 1546188488961, 1550485225704, 1554784190605, 
				1559079158004, 1559080206580, 1563374125211, 1567669092546, 
				1571964059830, 1576258961550, 1580553994439, 1584848961615, 
				1589143929015, 1593438896278, 1597733863635, 1602028830790, 
				1606323798157, 1610614767653, 1610614767744, 1610614767800, 
				1614914977937, 1619204702395, 1619210076240, 1623505043536, 
				1627793457297, 1627800207505, 1632093601862, 1636388569158, 
				1640683536436, 1644974637201, 1644979814545, 1649269473512, 
				1653562671163, 1653562671175, 1653562671245, 1653568438331, 
				1653568438470, 1657863405761, 1662158372943, 1670748307732, 
				1675043274976, 1679334375569, 1683633209485, 1687929880762, 
				1692223144051, 1696514113768, 1700807311508, 1705108046033, 
				1709400916048, 1713697980566, 1717992947912, 1722287915215, 
				1722287915250, 1726582882600, 1730877849692, 1735168950336, 
				1735168950480, 1739463917776, 1739469816016, 1743762751688, 
				1748057718925, 1752352686290, 1756647653521, 1760942620717, 
				1760942620723, 1760942620878, 1760942620920, 1765237588047, 
				1769532555471, 1773827522639, 1778122490063, 1782413459688, 
				1786716160238, 1791007391744, 1795304521853, 1799597326630, 
				1803892293926, 1808187261177, 1812482228500, 1816779227344, 
				1821072163012, 1825367130383, 1829662097681, 1833957064977, 
				1838252032121, 1842546999410, 1846837379142, 1851136933958, 
				1855431901254, 1864017248326, 1868316803142, 1872611770438, 
				1876906737770, 1881204261009, 1885492674678, 1889794261268, 
				1894080839947, 1898375807194, 1898379149457, 1902676541657, 
				1906974589076, 1906974654544, 1911266476249, 1915561443389, 
				1915561443415, 1919856410849, 1924151378034, 1928446345420, 
				1932741312788, 1937036279878, 1941338128532, 1945626214492, 
				1949924458663, 1954220540049, 1958511116523, 1962806083803, 
				1962806083856, 1967101051030, 1971393396864, 1975690985584, 
				1979985952838, 1984280920283, 1988575887474, 1992865087522, 
				1997165821991, 1997165822014, 1997165822038, 1997165822084, 
				1997165822140, 1997165822151, 1997165822176, 1997165822202, 
				1997165822215, 2001460789462, 2005755756674, 2010050723940, 
				2014341824657, 2018640658510, 2022935625805, 2027230593174, 
				2031519793338, 2031529164986, 2035820527793, 2040115494987, 
				2044410462263, 2048705429683, 2048705429734, 2053000397071, 
				2057295364326, 2065885298798, 2070176268453, 2070176268520, 
				2074471235856, 2078770200811, 2083065168102, 2087360135401, 
				2091655102735, 2095944958097, 2095946203281, 2095947382929, 
				2095951904913, 2095954264209, 2095954329745, 2095956426897, 
				2100245037327, 2104536006888, 2108838772959, 2113129939099, 
				2117424906381, 2121722232977, 2126018838673, 2130309808385, 
				2134604775695, 2138899742870, 2143194710166, 2147489677428, 
				2151778877658, 2151780778129, 2151783923857, 2151788970129, 
				2156079612054, 2160368812180, 2164669546703, 2168964514068, 
				2173259481287, 2177554448581, 2181845418216, 2186144383161, 
				2190439350345, 2194736611470, 2199029285037, 2207624986801, 
				2211915890874, 2216203387137, 2220508512426, 2224799088746, 
				2229094056179, 2233383256282, 2233390661850, 2237683990769, 
				2241978958100, 2246273925339, 2250568892557, 2254863859754, 
				2254863859999, 2259158827246, 2263453794542, 2267748761709, 
				2272043729005, 2276338696488, 2280633663673, 2284928631031, 
				2284931318007, 2289228054806, 2289228120342, 2293515223077, 
				2293518565413, 2293518565560, 2293518565666, 2293524791333, 
				2293525184549, 2297809535024, 2297809535156, 2297809535207, 
				2297809535266, 2297813532852, 2297813532902, 2297813532904, 
				2297813532939, 2302108500216, 2306403467510, 2310698434854, 
				2314993401960, 2319288369324, 2319288369446, 2323583336540, 
				2327878303814, 2332173271181, 2332177989773, 2336468238607, 
				2340763205757, 2349353140270, 2349353140462, 2353648107592, 
				2353648107675, 2353648107791, 2353648107793, 2357937307940, 
				2362242957579, 2366537924755, 2370827976923, 2375128383633, 
				2379417911366, 2383712288913, 2388013482129, 2392302813428, 
				2396597780753, 2400892747838, 2405187715335, 2409476915418, 
				2409478684933, 2413777649734, 2418078580996, 2422367584326, 
				2426659340392, 2426659340394, 2430954307688, 2435252486348, 
				2439547453474, 2439547453588, 2439547453704, 2443842420998, 
				2448137388079, 2452432355545, 2461022290196, 2465317257263, 
				2469612224714, 2473907192102, 2478202159370, 2482497126596, 
				2486792093696, 2491087061208, 2495382028377, 2495382028555, 
				2499676995851, 2503971963150, 2508261163226, 2512561897766, 
				2516854243456, 2521151832134, 2525442801896, 2529741766726, 
				2534036733999, 2538331701444, 2542626668813, 2551216603338, 
				2555511570647, 2559802540264, 2564101505201, 2568392474856, 
				2572685672528, 2572687442085, 2572687442107, 2576992829693, 
				2581277376691, 2581277376755, 2581277376784, 2585576341543, 
				2589867180121, 2594160509044, 2594160509073, 2594160509122, 
				2594160509146, 2598455476258, 2598457245776, 2598457245974, 
				2598461243670, 2602762698923, 2607051178278, 2611346145430, 
				2615641112808, 2619936080156, 2624231047219, 2628526014556, 
				2632820981959, 2637115949056, 2641410916584, 2645705883749, 
				2650000851215, 2654295818291, 2658590785611, 2662882541674, 
				2667180720345, 2671475687700, 2675770654764, 2680062476534, 
				2680065622262, 2684358492240, 2688651559144, 2692950524198, 
				2697242476662, 2701536592017, 2705835426065, 2710130393287, 
				2714425360496, 2718720327759, 2723015295055, 2727308361966, 
				2727308362000, 2727308362004, 2731605229772, 2735900196926, 
				2740193067088, 2740193132614, 2740193132624, 2740193132678, 
				2744490131536, 2748785098949, 2757375033550, 2761675767999, 
				2765970735281, 2770254954766, 2770257576206, 2770257707088, 
				2770257838160, 2770257903660, 2770257903675, 2770257903732, 
				2770257903735, 2770257903750, 2770257903757, 2770257903804, 
				2770257903829, 2770257903831, 2770257903833, 2770257903864, 
				2770257903876, 2770257903886, 2770257903892, 2770257903900, 
				2774554902822, 2778849870100, 2787439804683, 
            };
        }
        
    }
}
            