//
// Created by brunshweeck on 20 août 2024.
//

#ifndef CORE24_L128X128MIXRANDOM_H
#define CORE24_L128X128MIXRANDOM_H

#include <core/random/RandomGenerator.h>

namespace core {
    namespace random {
        /**
         * A "splittable" pseudorandom number generator (PRNG) whose period
         * is roughly 2<sup>256</sup>.  Class @b L128X128MixRandom implements
         * interfaces @b RandomGenerator and @b SplittableGenerator,
         * and therefore supports methods for producing pseudorandomly chosen
         * values of type @c int, @c long, @c float, @c double,
         * and @c boolean (and for producing streams of pseudorandomly chosen
         * numbers of type @c int, @c long, and @c double),
         * as well as methods for creating new split-off @b L128X128MixRandom
         * objects or streams of such objects.
         *
         * <p>
         * The @b L128X128MixRandom algorithm is a specific member of
         * the LXM family of algorithms for pseudorandom number generators;
         * for more information, see the documentation for namespace
         * @b random.  Each instance of @b L128X128MixRandom
         * has 256 bits of state plus one 128-bit instance-specific parameter.
         * </p>
         * <p>
         * If two instances of @b L128X128MixRandom are created with
         * the same seed within the same program execution, and the same
         * sequence of method calls is made for each, they will generate and
         * return identical sequences of values.
         * </p>
         * <p>
         * As with @b java.util.SplittableRandom, instances of
         * @b L128X128MixRandom are <em>not</em> thread-safe.  They are
         * designed to be split, not shared, across threads (see the @b split
         * method).
         * </p>
         * <p>
         * This class provides additional methods for generating random
         * streams, that employ the above techniques when used in
         * @c stream.parallel() mode.
         * </p>
         */
        class L128X128MixRandom final : public RandomGenerator {
            /*
             * Implementation Overview.
             *
             * The split operation uses the current generator to choose four new 64-bit
             * long values that are then used to initialize the parameter `a` and the
             * state variables `s`, `x0`, and `x1` for a newly constructed generator.
             *
             * With extremely high probability, no two generators so chosen
             * will have the same `a` parameter, and testing has indicated
             * that the values generated by two instances of @b L128X128MixRandom
             * will be (approximately) independent if have different values for `a`.
             *
             * The default (no-argument) constructor, in essence, uses
             * "defaultGen" to generate four new 64-bit values for the same
             * purpose.  Multiple generators created in this way will certainly
             * differ in their `a` parameters.  The defaultGen state must be accessed
             * in a thread-safe manner, so we use an AtomicLong to represent
             * this state.  To bootstrap the defaultGen, we start off using a
             * seed based on current time unless the
             * java.util.secureRandomSeed property is set. This serves as a
             * slimmed-down (and insecure) variant of SecureRandom that also
             * avoids stalls that may occur when using /dev/random.
             *
             * File organization: First static fields, then instance
             * fields, then constructors, then instance methods.
             */


            /* ---------------- static fields ---------------- */

            /**
             * The seed generator for default constructors.
             */
            static atomic::AtomicLong DEFAULT_GENERATOR;

            /*
             * Low half of multiplier used in the LCG portion of the algorithm;
             * the overall multiplier is (2**64 + ML).
             * Chosen based on research by Sebastiano Vigna and Guy Steele (2019).
             * The spectral scores for dimensions 2 through 8 for the multiplier 0x1d605bbb58c8abbfdLL
             * are [0.991889, 0.907938, 0.830964, 0.837980, 0.780378, 0.797464, 0.761493].
             */
            static CORE_FAST glong ML = CORE_CAST(glong, 0xD605BBB58C8ABBFD);

            /* ---------------- instance fields ---------------- */

            /**
             * The parameter that is used as an additive constant for the LCG.
             * Must be odd (therefore al must be odd).
             */
            glong ah = 0, al = 0;

            /**
             * The per-instance state: sh and sl for the LCG; the array x for the XBG;
             * At least one of the 2 elements of the array x must be nonzero.
             */
            glong mutable sh = 0, sl = 0, x[2] = {};

        public:
            /* ---------------- constructors ---------------- */

            /**
             * Basic constructor that initializes all fields from parameters.
             * It then adjusts the field values if necessary to ensure that
             * all constraints on the values of fields are met.
             *
             * @param ah high half of the additive parameter for the LCG
             * @param al low half of the additive parameter for the LCG
             * @param sh high half of the initial state for the LCG
             * @param sl low half of the initial state for the LCG
             * @param x0 first word of the initial state for the XBG
             * @param x1 second word of the initial state for the XBG
             */
            CORE_EXPLICIT L128X128MixRandom(glong ah, glong al, glong sh, glong sl, glong x0, glong x1);

            /**
             * Creates a new instance of @b L128X128MixRandom using the
             * specified @c long value as the initial seed. Instances of
             * @b L128X128MixRandom created with the same seed in the same
             * program generate identical sequences of values.
             *
             * @param seed the initial seed
             */
            CORE_EXPLICIT L128X128MixRandom(glong seed);

            /**
             * Creates a new instance of @b L128X128MixRandom that is likely to
             * generate sequences of values that are statistically independent
             * of those of any other instances in the current program execution,
             * but may, and typically does, vary across program invocations.
             */
            CORE_IMPLICIT L128X128MixRandom();

            /**
             * Creates a new instance of @b L128X128MixRandom using the specified array of
             * initial seed bytes. Instances of @b L128X128MixRandom created with the same
             * seed array in the same program execution generate identical sequences of values.
             *
             * @param seed the initial seed
             */
            CORE_EXPLICIT L128X128MixRandom(ByteArray const &seed);

            glong nextLong() const override;

            gbool isDeprecated() const override;

            RandomGeneratorProperties properties() const override;

            void setSeed(glong seed) override;
        };
    } // random
} // core

#endif //CORE24_L128X128MIXRANDOM_H
