//
// Created by brunshweeck on 20 août 2024.
//

#ifndef CORE24_L32X64MIXRANDOM_H
#define CORE24_L32X64MIXRANDOM_H

#include <core/random/RandomGenerator.h>

namespace core {
    namespace random {
        /**
         * A "splittable" pseudorandom number generator (PRNG) whose period
         * is roughly 2<sup>96</sup>.  Class @b L32X64MixRandom implements
         * interfaces @b RandomGenerator and @b SplittableGenerator,
         * and therefore supports methods for producing pseudorandomly chosen
         * values of type @c int, @c long, @c float, @c double,
         * and @c boolean (and for producing streams of pseudorandomly chosen
         * numbers of type @c int, @c long, and @c double),
         * as well as methods for creating new split-off @b L32X64MixRandom
         * objects or streams of such objects.
         *
         * <p>
         * The @b L32X64MixRandom algorithm is a specific member of
         * the LXM family of algorithms for pseudorandom number generators;
         * Each instance of @b L32X64MixRandom
         * has 96 bits of state plus one 32-bit instance-specific parameter.
         * </p>
         * <p>
         * If two instances of @b L32X64MixRandom are created with
         * the same seed within the same program execution, and the same
         * sequence of method calls is made for each, they will generate and
         * return identical sequences of values.
         * </p>
         * <p>
         * As with @b random::SplittableRandom, instances of
         * @b L32X64MixRandom are <em>not</em> thread-safe.  They are
         * designed to be split, not shared, across threads (see the @b split
         * method).
         * </p>
         * <p>This class provides additional methods for generating random
         * streams, that employ the above techniques when used in
         * @c stream.parallel() mode.
         * </p>
         * <p>
         * Instances of @b L32X64MixRandom are not cryptographically
         * secure.
         */
        class L32X64MixRandom final : public RandomGenerator {
            /*
             * Implementation Overview.
             *
             * The split operation uses the current generator to choose four new 32-bit
             * int values that are then used to initialize the parameter `a` and the
             * state variables `s`, `x0`, and `x1` for a newly constructed generator.
             *
             * With high probability, no two generators so chosen will have the same
             * `a` parameter, and testing has indicated that the values generated by
             * two instances of @b L32X64MixRandom will be (approximately)
             * independent if the two instances have different values for `a`.
             *
             * The default (no-argument) constructor, in essence, uses
             * "defaultGen" to generate four new 32-bit values for the same
             * purpose.  Multiple generators created in this way will certainly
             * differ in their `a` parameters.  The defaultGen state must be accessed
             * in a thread-safe manner, so we use an AtomicLong to represent
             * this state.  To bootstrap the defaultGen, we start off using a
             * seed based on current time unless the
             * java.util.secureRandomSeed property is set. This serves as a
             * slimmed-down (and insecure) variant of SecureRandom that also
             * avoids stalls that may occur when using /dev/random.
             *
             * File organization: First static fields, then instance
             * fields, then constructors, then instance methods.
            */

            /* ---------------- static fields ---------------- */

            /**
             * The seed generator for default constructors.
             */
            static atomic::AtomicLong DEFAULT_GENERATOR;

            /*
             * Multiplier used in the LCG portion of the algorithm.
             * Chosen based on research by Sebastiano Vigna and Guy Steele (2019).
             * The spectral scores for dimensions 2 through 8 for the multiplier 0xadb4a92d
             * are [0.975884, 0.936244, 0.755793, 0.877642, 0.751300, 0.789333, 0.728869].
             */
            static CORE_FAST gint M = CORE_CAST(gint, 0xADB4A92D);

            /* ---------------- instance fields ---------------- */

            /**
             * The parameter that is used as an additive constant for the LCG.
             * Must be odd.
             */
            gint a = 0;

            /**
             * The per-instance state: s for the LCG; the array x for the XBG;
             * At least one of the 2 elements of the array x must be nonzero.
             */
            gint mutable s = 0, x[2] = {};

        public:
            /* ---------------- constructors ---------------- */

            /**
             * Basic constructor that initializes all fields from parameters.
             * It then adjusts the field values if necessary to ensure that
             * all constraints on the values of fields are met.
             *
             * @param a additive parameter for the LCG
             * @param s initial state for the LCG
             * @param x0 first word of the initial state for the XBG
             * @param x1 second word of the initial state for the XBG
             */
            CORE_EXPLICIT L32X64MixRandom(gint a, gint s, gint x0, gint x1);

            /**
             * Creates a new instance of @b L32X64MixRandom using the
             * specified @c long value as the initial seed. Instances of
             * @b L32X64MixRandom created with the same seed in the same
             * program generate identical sequences of values.
             *
             * @param seed the initial seed
             */
            CORE_EXPLICIT L32X64MixRandom(glong seed);

            /**
             * Creates a new instance of @b L32X64MixRandom that is likely to
             * generate sequences of values that are statistically independent
             * of those of any other instances in the current program execution,
             * but may, and typically does, vary across program invocations.
             */
            CORE_IMPLICIT L32X64MixRandom();

            /**
             * Creates a new instance of @b L32X64MixRandom using the specified array of
             * initial seed bytes. Instances of @b L32X64MixRandom created with the same
             * seed array in the same program execution generate identical sequences of values.
             *
             * @param seed the initial seed
             */
            CORE_EXPLICIT L32X64MixRandom(ByteArray const &seed);

            /* ---------------- public methods ---------------- */

            /**
             * See RandomGenerator::nextInt() for docs.
             */
            gint nextInt() const override;

            /**
             * See RandomGenerator::nextLong() for docs.
             */
            glong nextLong() const override;

            gbool isDeprecated() const override;

            RandomGeneratorProperties properties() const override;

            void setSeed(glong seed) override;
        };
    } // random
} // core

#endif //CORE24_L32X64MIXRANDOM_H
