//
// Created by brunshweeck on 20 août 2024.
//

#ifndef CORE24_L64X256MIXRANDOM_H
#define CORE24_L64X256MIXRANDOM_H

#include <core/random/RandomGenerator.h>

namespace core {
    namespace random {
        /**
         * A "splittable" pseudorandom number generator (PRNG) whose period
         * is roughly 2<sup>320</sup>.  Class @b L64X256MixRandom implements
         * interfaces @b RandomGenerator and @b SplittableGenerator,
         * and therefore supports methods for producing pseudorandomly chosen
         * values of type @c int, @c long, @c float, @c double,
         * and @c boolean (and for producing streams of pseudorandomly chosen
         * numbers of type @c int, @c long, and @c double),
         * as well as methods for creating new split-off @b L64X256MixRandom
         * objects or streams of such objects.
         *
         * <p>
         * The @b L64X256MixRandom algorithm is a specific member of
         * the LXM family of algorithms for pseudorandom number generators;
         * for more information, see the documentation for namespace
         * @b random.  Each instance of @b L64X256MixRandom
         * has 320 bits of state plus one 64-bit instance-specific parameter.
         * </p>
         * <p>
         * If two instances of @b L64X256MixRandom are created with
         * the same seed within the same program execution, and the same
         * sequence of method calls is made for each, they will generate and
         * return identical sequences of values.
         * </p>
         * <p>
         * As with @b java.util.SplittableRandom, instances of
         * @b L64X256MixRandom are <em>not</em> thread-safe.  They are
         * designed to be split, not shared, across threads (see the @b split
         * method).
         * </p>
         *
         * <p>This class provides additional methods for generating random
         * streams, that employ the above techniques when used in
         * @c stream.parallel() mode.
         * </p>
         */
        class L64X256MixRandom final : public RandomGenerator {
            /*
             * Implementation Overview.
             *
             * The split operation uses the current generator to choose six new 64-bit
             * long values that are then used to initialize the parameter `a` and the
             * state variables `s`, `x0`, `x1`, `x2`, and `x3` for a newly constructed
             * generator.
             *
             * With extremely high probability, no two generators so chosen
             * will have the same `a` parameter, and testing has indicated
             * that the values generated by two instances of @b L64X256MixRandom
             * will be (approximately) independent if have different values for `a`.
             *
             * The default (no-argument) constructor, in essence, uses
             * "defaultGen" to generate six new 64-bit values for the same
             * purpose.  Multiple generators created in this way will certainly
             * differ in their `a` parameters.  The defaultGen state must be accessed
             * in a thread-safe manner, so we use an AtomicLong to represent
             * this state.  To bootstrap the defaultGen, we start off using a
             * seed based on current time unless the
             * java.util.secureRandomSeed property is set. This serves as a
             * slimmed-down (and insecure) variant of SecureRandom that also
             * avoids stalls that may occur when using /dev/random.
             *
             * File organization: First static fields, then instance
             * fields, then constructors, then instance methods.
             */


            /* ---------------- static fields ---------------- */

            /**
             * The seed generator for default constructors.
             */
            static atomic::AtomicLong DEFAULT_GENERATOR;

            /*
             * Multiplier used in the LCG portion of the algorithm.
             * Chosen based on research by Sebastiano Vigna and Guy Steele (2019).
             * The spectral scores for dimensions 2 through 8 for the multiplier 0xd1342543de82ef95
             * are [0.958602, 0.937479, 0.870757, 0.822326, 0.820405, 0.813065, 0.760215].
             */
            static CORE_FAST glong M = CORE_CAST(glong, 0xD1342543DE82EF95);

            /* ---------------- instance fields ---------------- */

            /**
             * The parameter that is used as an additive constant for the LCG.
             * Must be odd.
             */
            glong a = 0;

            /**
             * The per-instance state: s for the LCG; the array x for the XBG;
             * At least one of the 4 elements of the array x must be nonzero.
             */
            glong mutable s = 0, x[4] = {};

        public:
            /* ---------------- constructors ---------------- */

            /**
             * Basic constructor that initializes all fields from parameters.
             * It then adjusts the field values if necessary to ensure that
             * all constraints on the values of fields are met.
             *
             * @param a additive parameter for the LCG
             * @param s initial state for the LCG
             * @param x0 first word of the initial state for the XBG
             * @param x1 second word of the initial state for the XBG
             * @param x2 third word of the initial state for the XBG
             * @param x3 fourth word of the initial state for the XBG
             */
            CORE_EXPLICIT L64X256MixRandom(glong a, glong s, glong x0, glong x1, glong x2, glong x3);

            /**
             * Creates a new instance of @b L64X256MixRandom using the
             * specified @c long value as the initial seed. Instances of
             * @b L64X256MixRandom created with the same seed in the same
             * program generate identical sequences of values.
             *
             * @param seed the initial seed
             */
            CORE_EXPLICIT L64X256MixRandom(glong seed);

            /**
             * Creates a new instance of @b L64X256MixRandom that is likely to
             * generate sequences of values that are statistically independent
             * of those of any other instances in the current program execution,
             * but may, and typically does, vary across program invocations.
             */
            CORE_IMPLICIT L64X256MixRandom();

            /**
             * Creates a new instance of @b L64X256MixRandom using the specified array of
             * initial seed bytes. Instances of @b L64X256MixRandom created with the same
             * seed array in the same program execution generate identical sequences of values.
             *
             * @param seed the initial seed
             */
            CORE_EXPLICIT L64X256MixRandom(ByteArray const &seed);

            glong nextLong() const override;

            gbool isDeprecated() const override;

            RandomGeneratorProperties properties() const override;

            void setSeed(glong seed) override;
        };
    } // random
} // core

#endif //CORE24_L64X256MIXRANDOM_H
