
#include "ar_DZ.h"
#include <core/lang/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Ar_Dz::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String Ar_Dz::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Ar_Dz::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String Ar_Dz::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Ar_Dz::hasVariant() const {
            return false;
        }
        
        gbool Ar_Dz::hasRegion() const {
            return true;
        }
        
        gbool Ar_Dz::hasScript() const {
            return false;
        }
            
        String Ar_Dz::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Ar_Dz::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ar_Dz::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ar_Dz::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ar_Dz::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
            
        String Ar_Dz::quotationStart(gbool alt) const {
            return String();
        }
            
        String Ar_Dz::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Ar_Dz::decimalSeparator() const {
            return String(CharArray::of(0x2C));
        }
            
        String Ar_Dz::groupSeparator() const {
            return String(CharArray::of(0x2E));
        }
            
        String Ar_Dz::listSeparator() const {
            return String();
        }
            
        String Ar_Dz::plusSign() const {
            return String();
        }
            
        String Ar_Dz::minusSign() const {
            return String();
        }
            
        String Ar_Dz::exponential() const {
            return String();
        }
            
        String Ar_Dz::perMill() const {
            return String();
        }
            
        String Ar_Dz::percent() const {
            return String();
        }
            
        String Ar_Dz::infinity() const {
            return String();
        }
            
        String Ar_Dz::nan() const {
            return String();
        }
            
        String Ar_Dz::superScriptingExponent() const {
            return String();
        }
           
        String Ar_Dz::decimalPattern() const {
            return String();
        }
            
        String Ar_Dz::scientificPattern() const {
            return String();
        }
            
        String Ar_Dz::percentPattern() const {
            return String();
        }
            
        String Ar_Dz::currencyPattern() const {
            return String();
        }

        String Ar_Dz::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Ar_Dz::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Ar_Dz::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray Ar_Dz::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ar_Dz::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 0: return StringArray::of(String(CharArray::of(0x062C, 0x0627, 0x0646, 0x0641, 0x064A)), String(CharArray::of(0x0641, 0x064A, 0x0641, 0x0631, 0x064A)), String(), String(CharArray::of(0x0623, 0x0641, 0x0631, 0x064A, 0x0644)), String(CharArray::of(0x0645, 0x0627, 0x064A)), String(CharArray::of(0x062C, 0x0648, 0x0627, 0x0646)), String(CharArray::of(0x062C, 0x0648, 0x064A, 0x0644, 0x064A, 0x0629)), String(CharArray::of(0x0623, 0x0648, 0x062A)), String(), String(), String(), String());
                default: break;
                }
            } else {
                switch(style) {
				case 2: return StringArray::of(String(CharArray::of(0x062C)), String(), String(), String(), String(CharArray::of(0x0645)), String(CharArray::of(0x062C)), String(CharArray::of(0x062C)), String(CharArray::of(0x0623)), String(), String(CharArray::of(0x0623)), String(CharArray::of(0x0646)), String());
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ar_Dz::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ar_Dz::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ar_Dz::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Ar_Dz::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ar_Dz::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ar_Dz::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ar_Dz::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ar_Dz::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ar_Dz::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        