
#include "ar_IL.h"
#include <core/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Ar_Il::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String Ar_Il::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Ar_Il::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String Ar_Il::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Ar_Il::hasVariant() const {
            return false;
        }
        
        gbool Ar_Il::hasRegion() const {
            return true;
        }
        
        gbool Ar_Il::hasScript() const {
            return false;
        }
            
        String Ar_Il::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Ar_Il::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ar_Il::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ar_Il::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ar_Il::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
            
        String Ar_Il::quotationStart(gbool alt) const {
            return String();
        }
            
        String Ar_Il::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Ar_Il::decimalSeparator() const {
            return String();
        }
            
        String Ar_Il::groupSeparator() const {
            return String();
        }
            
        String Ar_Il::listSeparator() const {
            return String();
        }
            
        String Ar_Il::plusSign() const {
            return String();
        }
            
        String Ar_Il::minusSign() const {
            return String();
        }
            
        String Ar_Il::exponential() const {
            return String();
        }
            
        String Ar_Il::perMill() const {
            return String();
        }
            
        String Ar_Il::percent() const {
            return String();
        }
            
        String Ar_Il::infinity() const {
            return String();
        }
            
        String Ar_Il::nan() const {
            return String();
        }
            
        String Ar_Il::superScriptingExponent() const {
            return String();
        }
           
        String Ar_Il::decimalPattern() const {
            return String();
        }
            
        String Ar_Il::scientificPattern() const {
            return String();
        }
            
        String Ar_Il::percentPattern() const {
            return String();
        }
            
        String Ar_Il::currencyPattern() const {
            return String();
        }

        String Ar_Il::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Ar_Il::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Ar_Il::digits() const {
            return CharArray::of(1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641);
        }
        
        StringArray Ar_Il::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ar_Il::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ar_Il::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ar_Il::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ar_Il::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Ar_Il::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ar_Il::timePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x48, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x20, 0x7A, 0x7A, 0x7A, 0x7A));
				case 1: return String(CharArray::of(0x48, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x20, 0x7A));
				case 2: return String(CharArray::of(0x48, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73));
				case 3: return String(CharArray::of(0x48, 0x3A, 0x6D, 0x6D));
            default: break;
            }
            return String();
        }
        
        String Ar_Il::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ar_Il::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ar_Il::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ar_Il::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        