
#include "ar_SD.h"
#include <core/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Ar_Sd::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String Ar_Sd::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Ar_Sd::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String Ar_Sd::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Ar_Sd::hasVariant() const {
            return false;
        }
        
        gbool Ar_Sd::hasRegion() const {
            return true;
        }
        
        gbool Ar_Sd::hasScript() const {
            return false;
        }
            
        String Ar_Sd::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Ar_Sd::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ar_Sd::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ar_Sd::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ar_Sd::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
            
        String Ar_Sd::quotationStart(gbool alt) const {
            return String();
        }
            
        String Ar_Sd::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Ar_Sd::decimalSeparator() const {
            return String();
        }
            
        String Ar_Sd::groupSeparator() const {
            return String();
        }
            
        String Ar_Sd::listSeparator() const {
            return String();
        }
            
        String Ar_Sd::plusSign() const {
            return String();
        }
            
        String Ar_Sd::minusSign() const {
            return String();
        }
            
        String Ar_Sd::exponential() const {
            return String();
        }
            
        String Ar_Sd::perMill() const {
            return String();
        }
            
        String Ar_Sd::percent() const {
            return String();
        }
            
        String Ar_Sd::infinity() const {
            return String();
        }
            
        String Ar_Sd::nan() const {
            return String();
        }
            
        String Ar_Sd::superScriptingExponent() const {
            return String();
        }
           
        String Ar_Sd::decimalPattern() const {
            return String();
        }
            
        String Ar_Sd::scientificPattern() const {
            return String();
        }
            
        String Ar_Sd::percentPattern() const {
            return String();
        }
            
        String Ar_Sd::currencyPattern() const {
            return String();
        }

        String Ar_Sd::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Ar_Sd::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Ar_Sd::digits() const {
            return CharArray::of(1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641);
        }
        
        StringArray Ar_Sd::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ar_Sd::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ar_Sd::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ar_Sd::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ar_Sd::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Ar_Sd::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ar_Sd::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ar_Sd::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ar_Sd::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ar_Sd::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ar_Sd::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        