
#include "ar_TN.h"
#include <core/lang/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Ar_Tn::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String Ar_Tn::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Ar_Tn::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String Ar_Tn::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Ar_Tn::hasVariant() const {
            return false;
        }
        
        gbool Ar_Tn::hasRegion() const {
            return true;
        }
        
        gbool Ar_Tn::hasScript() const {
            return false;
        }
            
        String Ar_Tn::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Ar_Tn::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ar_Tn::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ar_Tn::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ar_Tn::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
            
        String Ar_Tn::quotationStart(gbool alt) const {
            return String();
        }
            
        String Ar_Tn::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Ar_Tn::decimalSeparator() const {
            return String(CharArray::of(0x2C));
        }
            
        String Ar_Tn::groupSeparator() const {
            return String(CharArray::of(0x2E));
        }
            
        String Ar_Tn::listSeparator() const {
            return String();
        }
            
        String Ar_Tn::plusSign() const {
            return String();
        }
            
        String Ar_Tn::minusSign() const {
            return String();
        }
            
        String Ar_Tn::exponential() const {
            return String();
        }
            
        String Ar_Tn::perMill() const {
            return String();
        }
            
        String Ar_Tn::percent() const {
            return String();
        }
            
        String Ar_Tn::infinity() const {
            return String();
        }
            
        String Ar_Tn::nan() const {
            return String();
        }
            
        String Ar_Tn::superScriptingExponent() const {
            return String();
        }
           
        String Ar_Tn::decimalPattern() const {
            return String();
        }
            
        String Ar_Tn::scientificPattern() const {
            return String();
        }
            
        String Ar_Tn::percentPattern() const {
            return String();
        }
            
        String Ar_Tn::currencyPattern() const {
            return String();
        }

        String Ar_Tn::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Ar_Tn::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Ar_Tn::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray Ar_Tn::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ar_Tn::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 0: return StringArray::of(String(CharArray::of(0x062C, 0x0627, 0x0646, 0x0641, 0x064A)), String(CharArray::of(0x0641, 0x064A, 0x0641, 0x0631, 0x064A)), String(), String(CharArray::of(0x0623, 0x0641, 0x0631, 0x064A, 0x0644)), String(CharArray::of(0x0645, 0x0627, 0x064A)), String(CharArray::of(0x062C, 0x0648, 0x0627, 0x0646)), String(CharArray::of(0x062C, 0x0648, 0x064A, 0x0644, 0x064A, 0x0629)), String(CharArray::of(0x0623, 0x0648, 0x062A)), String(), String(), String(), String());
                default: break;
                }
            } else {
                switch(style) {
				case 2: return StringArray::of(String(CharArray::of(0x062C)), String(), String(), String(), String(CharArray::of(0x0645)), String(CharArray::of(0x062C)), String(CharArray::of(0x062C)), String(CharArray::of(0x0623)), String(), String(CharArray::of(0x0623)), String(CharArray::of(0x0646)), String());
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ar_Tn::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ar_Tn::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ar_Tn::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Ar_Tn::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ar_Tn::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ar_Tn::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ar_Tn::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ar_Tn::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ar_Tn::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        