
#include "bho.h"
#include <core/lang/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Bho::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
				case 64: return String(CharArray::of(0x092D, 0x094B, 0x091C, 0x092A, 0x0941, 0x0930, 0x0940));
				case 158: return String(CharArray::of(0x0905, 0x0902, 0x0917, 0x0930, 0x0947, 0x091C, 0x0940));
            default: break;
            }
            return String();
        }
        
        String Bho::displayScript(gint script) const {
            switch(script) {
				case 33: return String(CharArray::of(0x0926, 0x0947, 0x0935, 0x093E, 0x0928, 0x093E, 0x0917, 0x093E, 0x0930, 0x0940));
            default: break;
            }
            return String();
        }
        
        String Bho::displayCountry(gint region) const {
            switch(region) {

				case 145: return String(CharArray::of(0x092D, 0x093E, 0x0930, 0x0924));

				case 297: return String(CharArray::of(0x0905, 0x0928, 0x091C, 0x093E, 0x0928, 0x20, 0x0907, 0x0932, 0x093E, 0x0915, 0x093E));
            default: break;
            }
            return String();
        }
        
        String Bho::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Bho::hasVariant() const {
            return false;
        }
        
        gbool Bho::hasRegion() const {
            return false;
        }
        
        gbool Bho::hasScript() const {
            return false;
        }
            
        String Bho::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Bho::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Bho::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Bho::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Bho::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
            
        String Bho::quotationStart(gbool alt) const {
            return (alt) ? String() : String() ;
        }
            
        String Bho::quotationEnd(gbool alt) const {
            return (alt) ? String() : String() ;
        }
            
        String Bho::decimalSeparator() const {
            return String();
        }
            
        String Bho::groupSeparator() const {
            return String();
        }
            
        String Bho::listSeparator() const {
            return String();
        }
            
        String Bho::plusSign() const {
            return String();
        }
            
        String Bho::minusSign() const {
            return String();
        }
            
        String Bho::exponential() const {
            return String();
        }
            
        String Bho::perMill() const {
            return String();
        }
            
        String Bho::percent() const {
            return String();
        }
            
        String Bho::infinity() const {
            return String();
        }
            
        String Bho::nan() const {
            return String();
        }
            
        String Bho::superScriptingExponent() const {
            return String();
        }
           
        String Bho::decimalPattern() const {
            return String();
        }
            
        String Bho::scientificPattern() const {
            return String();
        }
            
        String Bho::percentPattern() const {
            return String();
        }
            
        String Bho::currencyPattern() const {
            return String();
        }

        String Bho::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Bho::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Bho::digits() const {
            return CharArray::of(2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, 2414, 2415);
        }
        
        StringArray Bho::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 0: return StringArray::of(String(CharArray::of(0x0938, 0x094B, 0x092E, 0x092C, 0x093E, 0x0930)), String(CharArray::of(0x092E, 0x0902, 0x0917, 0x0932, 0x092C, 0x093E, 0x0930)), String(CharArray::of(0x092C, 0x0941, 0x0927, 0x092C, 0x093E, 0x0930)), String(CharArray::of(0x092C, 0x0943, 0x0939, 0x0938, 0x094D, 0x092A, 0x0924, 0x093F, 0x092C, 0x093E, 0x0930)), String(CharArray::of(0x0936, 0x0941, 0x0915, 0x094D, 0x0930, 0x092C, 0x093E, 0x0930)), String(CharArray::of(0x0938, 0x0928, 0x0940, 0x091A, 0x0930)), String(CharArray::of(0x0930, 0x092C, 0x0940, 0x092C, 0x093E, 0x0930)));
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Bho::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 0: return StringArray::of(String(CharArray::of(0x091C, 0x0928, 0x0935, 0x0930, 0x0940)), String(CharArray::of(0x092B, 0x0930, 0x0935, 0x0930, 0x0940)), String(CharArray::of(0x092E, 0x093E, 0x0930, 0x094D, 0x091A)), String(CharArray::of(0x0905, 0x092A, 0x094D, 0x0930, 0x0948, 0x0932)), String(CharArray::of(0x092E, 0x0908)), String(CharArray::of(0x091C, 0x0942, 0x0928)), String(CharArray::of(0x091C, 0x0941, 0x0932, 0x093E, 0x0908)), String(CharArray::of(0x0905, 0x0917, 0x0938, 0x094D, 0x0924)), String(CharArray::of(0x0938, 0x093F, 0x0924, 0x092E, 0x094D, 0x092C, 0x0930)), String(CharArray::of(0x0905, 0x0915, 0x094D, 0x091F, 0x0942, 0x092C, 0x0930)), String(CharArray::of(0x0928, 0x0935, 0x0902, 0x092C, 0x0930)), String(CharArray::of(0x0926, 0x093F, 0x0938, 0x0902, 0x092C, 0x0930)));
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Bho::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Bho::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 0: return StringArray::of(String(), String(CharArray::of(0x092D, 0x094B, 0x0930)), String(), String(CharArray::of(0x0938, 0x093E, 0x0902, 0x091D)), String(), String(), String(), String());
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Bho::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Bho::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Bho::timePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x20, 0x61, 0x20, 0x7A, 0x7A, 0x7A, 0x7A));
				case 1: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x20, 0x61, 0x20, 0x7A));
				case 2: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x20, 0x61));
				case 3: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x20, 0x61));
            default: break;
            }
            return String();
        }
        
        String Bho::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Bho::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Bho::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
				case 58: 
				if (style == 1) return String(CharArray::of(0x0917, 0x094D, 0x0930, 0x0940, 0x0928, 0x0935, 0x093F, 0x091A, 0x20, 0x092E, 0x0940, 0x0928, 0x20, 0x091F, 0x093E, 0x0907, 0x092E));
					break;
            default: break;
            }
            return String();
        }
        
        String Bho::timezonePattern(gint type) const {
            switch(type){
				case 3: return String(CharArray::of(0x7B, 0x30, 0x7D, 0x20, 0x091F, 0x093E, 0x0907, 0x092E));
            default: break;
            }
            return String();
        }
    }
}
        