
#include "bo_IN.h"
#include <core/lang/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Bo_In::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String Bo_In::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Bo_In::displayCountry(gint region) const {
            switch(region) {

				case 4: return String(CharArray::of(0x0F68, 0x0F7C, 0x0F64, 0x0F72, 0x0F0B, 0x0F61, 0x0F71, 0x0F53, 0x0F0B, 0x0F53, 0x0F0D));
            default: break;
            }
            return String();
        }
        
        String Bo_In::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Bo_In::hasVariant() const {
            return false;
        }
        
        gbool Bo_In::hasRegion() const {
            return true;
        }
        
        gbool Bo_In::hasScript() const {
            return false;
        }
            
        String Bo_In::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Bo_In::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Bo_In::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Bo_In::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Bo_In::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 67: return String(CharArray::of(0x43, 0x4E, 0xA5));
            default: break;
            }
            return String();
        }
            
        String Bo_In::quotationStart(gbool alt) const {
            return String();
        }
            
        String Bo_In::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Bo_In::decimalSeparator() const {
            return String();
        }
            
        String Bo_In::groupSeparator() const {
            return String();
        }
            
        String Bo_In::listSeparator() const {
            return String();
        }
            
        String Bo_In::plusSign() const {
            return String();
        }
            
        String Bo_In::minusSign() const {
            return String();
        }
            
        String Bo_In::exponential() const {
            return String();
        }
            
        String Bo_In::perMill() const {
            return String();
        }
            
        String Bo_In::percent() const {
            return String();
        }
            
        String Bo_In::infinity() const {
            return String();
        }
            
        String Bo_In::nan() const {
            return String();
        }
            
        String Bo_In::superScriptingExponent() const {
            return String();
        }
           
        String Bo_In::decimalPattern() const {
            return String();
        }
            
        String Bo_In::scientificPattern() const {
            return String();
        }
            
        String Bo_In::percentPattern() const {
            return String();
        }
            
        String Bo_In::currencyPattern() const {
            return String();
        }

        String Bo_In::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Bo_In::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Bo_In::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray Bo_In::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Bo_In::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Bo_In::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Bo_In::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Bo_In::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Bo_In::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Bo_In::timePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x20, 0x61, 0x20, 0x7A, 0x7A, 0x7A, 0x7A));
				case 1: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x20, 0x61, 0x20, 0x7A));
				case 2: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x20, 0x61));
				case 3: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x20, 0x61));
            default: break;
            }
            return String();
        }
        
        String Bo_In::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Bo_In::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Bo_In::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Bo_In::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        