
#include "bss.h"
#include <core/lang/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Bss::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
				case 83: return String(CharArray::of(0x41, 0x6B, 0x6F, 0x6F, 0x73, 0x65));
				case 158: return String(CharArray::of(0x41, 0x6B, 0xE1, 0xE1, 0x6C, 0xE9));
				case 177: return String(CharArray::of(0x46, 0x72, 0x025B, 0x6E, 0x73, 0xE9));
            default: break;
            }
            return String();
        }
        
        String Bss::displayScript(gint script) const {
            switch(script) {
				case 92: return String(CharArray::of(0x41, 0x6B, 0x6F, 0x6F, 0x73, 0x65));
            default: break;
            }
            return String();
        }
        
        String Bss::displayCountry(gint region) const {
            switch(region) {

				case 79: return String(CharArray::of(0x4B, 0x61, 0x6D, 0x65, 0x72, 0xFB, 0x6E));
            default: break;
            }
            return String();
        }
        
        String Bss::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Bss::hasVariant() const {
            return false;
        }
        
        gbool Bss::hasRegion() const {
            return false;
        }
        
        gbool Bss::hasScript() const {
            return false;
        }
            
        String Bss::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
				case 269:
					if (count == -1) return String(CharArray::of(0x46, 0x72, 0xE2, 0x6E, 0x6B, 0x65, 0x20, 0x43, 0x46, 0x41));
					break;
            default: break;
            }
            return String();
        }
        
        String Bss::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Bss::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Bss::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Bss::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
            
        String Bss::quotationStart(gbool alt) const {
            return (alt) ? String() : String() ;
        }
            
        String Bss::quotationEnd(gbool alt) const {
            return (alt) ? String() : String() ;
        }
            
        String Bss::decimalSeparator() const {
            return String();
        }
            
        String Bss::groupSeparator() const {
            return String();
        }
            
        String Bss::listSeparator() const {
            return String();
        }
            
        String Bss::plusSign() const {
            return String();
        }
            
        String Bss::minusSign() const {
            return String();
        }
            
        String Bss::exponential() const {
            return String();
        }
            
        String Bss::perMill() const {
            return String();
        }
            
        String Bss::percent() const {
            return String();
        }
            
        String Bss::infinity() const {
            return String();
        }
            
        String Bss::nan() const {
            return String();
        }
            
        String Bss::superScriptingExponent() const {
            return String();
        }
           
        String Bss::decimalPattern() const {
            return String();
        }
            
        String Bss::scientificPattern() const {
            return String();
        }
            
        String Bss::percentPattern() const {
            return String();
        }
            
        String Bss::currencyPattern() const {
            return String();
        }

        String Bss::listPattern(gint type, gint subType) const {
            switch(subType) {

				case 10: 
					if(type == 1) return String(CharArray::of(0x7B, 0x30, 0x7D, 0x20, 0x7B, 0x31, 0x7D));
					break;
            default: break;
            }
            return String();
        }
            
        String Bss::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Bss::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray Bss::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Bss::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Bss::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Bss::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Bss::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Bss::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Bss::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Bss::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Bss::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Bss::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Bss::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        