
#include "de_IT.h"
#include <core/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String De_It::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String De_It::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String De_It::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String De_It::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool De_It::hasVariant() const {
            return false;
        }
        
        gbool De_It::hasRegion() const {
            return true;
        }
        
        gbool De_It::hasScript() const {
            return false;
        }
            
        String De_It::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String De_It::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String De_It::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String De_It::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String De_It::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
            
        String De_It::quotationStart(gbool alt) const {
            return String();
        }
            
        String De_It::quotationEnd(gbool alt) const {
            return String();
        }
            
        String De_It::decimalSeparator() const {
            return String();
        }
            
        String De_It::groupSeparator() const {
            return String();
        }
            
        String De_It::listSeparator() const {
            return String();
        }
            
        String De_It::plusSign() const {
            return String();
        }
            
        String De_It::minusSign() const {
            return String();
        }
            
        String De_It::exponential() const {
            return String();
        }
            
        String De_It::perMill() const {
            return String();
        }
            
        String De_It::percent() const {
            return String();
        }
            
        String De_It::infinity() const {
            return String();
        }
            
        String De_It::nan() const {
            return String();
        }
            
        String De_It::superScriptingExponent() const {
            return String();
        }
           
        String De_It::decimalPattern() const {
            return String();
        }
            
        String De_It::scientificPattern() const {
            return String();
        }
            
        String De_It::percentPattern() const {
            return String();
        }
            
        String De_It::currencyPattern() const {
            return String();
        }

        String De_It::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String De_It::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray De_It::digits() const {
            return CharArray();
        }
        
        StringArray De_It::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray De_It::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 1: return StringArray::of(String(CharArray::of(0x4A, 0xE4, 0x6E, 0x2E)), String(), String(), String(), String(), String(), String(), String(), String(CharArray::of(0x53, 0x65, 0x70, 0x2E)), String(), String(), String());
				case 0: return StringArray::of(String(CharArray::of(0x4A, 0xE4, 0x6E, 0x6E, 0x65, 0x72)), String(), String(), String(), String(), String(), String(), String(), String(), String(), String(), String());
                default: break;
                }
            } else {
                switch(style) {
				case 1: return StringArray::of(String(CharArray::of(0x4A, 0xE4, 0x6E)), String(), String(), String(), String(), String(), String(), String(), String(), String(), String(), String());
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray De_It::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray De_It::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray De_It::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String De_It::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String De_It::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String De_It::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String De_It::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String De_It::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String De_It::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        