
#include "de_LU.h"
#include <core/lang/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String De_Lu::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String De_Lu::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String De_Lu::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String De_Lu::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool De_Lu::hasVariant() const {
            return false;
        }
        
        gbool De_Lu::hasRegion() const {
            return true;
        }
        
        gbool De_Lu::hasScript() const {
            return false;
        }
            
        String De_Lu::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String De_Lu::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String De_Lu::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String De_Lu::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String De_Lu::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 152: return String(CharArray::of(0x46));
            default: break;
            }
            return String();
        }
            
        String De_Lu::quotationStart(gbool alt) const {
            return String();
        }
            
        String De_Lu::quotationEnd(gbool alt) const {
            return String();
        }
            
        String De_Lu::decimalSeparator() const {
            return String();
        }
            
        String De_Lu::groupSeparator() const {
            return String();
        }
            
        String De_Lu::listSeparator() const {
            return String();
        }
            
        String De_Lu::plusSign() const {
            return String();
        }
            
        String De_Lu::minusSign() const {
            return String();
        }
            
        String De_Lu::exponential() const {
            return String();
        }
            
        String De_Lu::perMill() const {
            return String();
        }
            
        String De_Lu::percent() const {
            return String();
        }
            
        String De_Lu::infinity() const {
            return String();
        }
            
        String De_Lu::nan() const {
            return String();
        }
            
        String De_Lu::superScriptingExponent() const {
            return String();
        }
           
        String De_Lu::decimalPattern() const {
            return String();
        }
            
        String De_Lu::scientificPattern() const {
            return String();
        }
            
        String De_Lu::percentPattern() const {
            return String();
        }
            
        String De_Lu::currencyPattern() const {
            return String();
        }

        String De_Lu::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String De_Lu::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray De_Lu::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray De_Lu::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray De_Lu::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray De_Lu::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray De_Lu::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 2: return StringArray::of(String(), String(CharArray::of(0x76, 0x6F, 0x72, 0x6D, 0x2E)), String(), String(CharArray::of(0x6E, 0x61, 0x63, 0x68, 0x6D, 0x2E)), String(), String(), String(), String());
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray De_Lu::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String De_Lu::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String De_Lu::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String De_Lu::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String De_Lu::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String De_Lu::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String De_Lu::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        