
#include "en_AG.h"
#include <core/lang/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String En_Ag::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String En_Ag::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String En_Ag::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String En_Ag::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool En_Ag::hasVariant() const {
            return false;
        }
        
        gbool En_Ag::hasRegion() const {
            return true;
        }
        
        gbool En_Ag::hasScript() const {
            return false;
        }
            
        String En_Ag::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String En_Ag::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_Ag::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_Ag::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_Ag::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 276: return String(CharArray::of(0x24));
            default: break;
            }
            return String();
        }
            
        String En_Ag::quotationStart(gbool alt) const {
            return String();
        }
            
        String En_Ag::quotationEnd(gbool alt) const {
            return String();
        }
            
        String En_Ag::decimalSeparator() const {
            return String();
        }
            
        String En_Ag::groupSeparator() const {
            return String();
        }
            
        String En_Ag::listSeparator() const {
            return String();
        }
            
        String En_Ag::plusSign() const {
            return String();
        }
            
        String En_Ag::minusSign() const {
            return String();
        }
            
        String En_Ag::exponential() const {
            return String();
        }
            
        String En_Ag::perMill() const {
            return String();
        }
            
        String En_Ag::percent() const {
            return String();
        }
            
        String En_Ag::infinity() const {
            return String();
        }
            
        String En_Ag::nan() const {
            return String();
        }
            
        String En_Ag::superScriptingExponent() const {
            return String();
        }
           
        String En_Ag::decimalPattern() const {
            return String();
        }
            
        String En_Ag::scientificPattern() const {
            return String();
        }
            
        String En_Ag::percentPattern() const {
            return String();
        }
            
        String En_Ag::currencyPattern() const {
            return String();
        }

        String En_Ag::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String En_Ag::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray En_Ag::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray En_Ag::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Ag::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Ag::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Ag::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Ag::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String En_Ag::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String En_Ag::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String En_Ag::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String En_Ag::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String En_Ag::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String En_Ag::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        