
#include "en_DK.h"
#include <core/lang/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String En_Dk::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String En_Dk::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String En_Dk::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String En_Dk::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool En_Dk::hasVariant() const {
            return false;
        }
        
        gbool En_Dk::hasRegion() const {
            return true;
        }
        
        gbool En_Dk::hasScript() const {
            return false;
        }
            
        String En_Dk::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String En_Dk::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_Dk::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_Dk::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_Dk::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 81: return String(CharArray::of(0x6B, 0x72, 0x2E));
            default: break;
            }
            return String();
        }
            
        String En_Dk::quotationStart(gbool alt) const {
            return String();
        }
            
        String En_Dk::quotationEnd(gbool alt) const {
            return String();
        }
            
        String En_Dk::decimalSeparator() const {
            return String(CharArray::of(0x2C));
        }
            
        String En_Dk::groupSeparator() const {
            return String(CharArray::of(0x2E));
        }
            
        String En_Dk::listSeparator() const {
            return String();
        }
            
        String En_Dk::plusSign() const {
            return String();
        }
            
        String En_Dk::minusSign() const {
            return String();
        }
            
        String En_Dk::exponential() const {
            return String();
        }
            
        String En_Dk::perMill() const {
            return String();
        }
            
        String En_Dk::percent() const {
            return String();
        }
            
        String En_Dk::infinity() const {
            return String();
        }
            
        String En_Dk::nan() const {
            return String();
        }
            
        String En_Dk::superScriptingExponent() const {
            return String(CharArray::of(0xB7));
        }
           
        String En_Dk::decimalPattern() const {
            return String();
        }
            
        String En_Dk::scientificPattern() const {
            return String();
        }
            
        String En_Dk::percentPattern() const {
            return String(CharArray::of(0x23, 0x2C, 0x23, 0x23, 0x30, 0xA0, 0x25));
        }
            
        String En_Dk::currencyPattern() const {
            return String();
        }

        String En_Dk::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String En_Dk::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray En_Dk::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray En_Dk::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Dk::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Dk::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Dk::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Dk::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String En_Dk::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String En_Dk::timePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x48, 0x48, 0x2E, 0x6D, 0x6D, 0x2E, 0x73, 0x73, 0x20, 0x7A, 0x7A, 0x7A, 0x7A));
				case 1: return String(CharArray::of(0x48, 0x48, 0x2E, 0x6D, 0x6D, 0x2E, 0x73, 0x73, 0x20, 0x7A));
				case 2: return String(CharArray::of(0x48, 0x48, 0x2E, 0x6D, 0x6D, 0x2E, 0x73, 0x73));
				case 3: return String(CharArray::of(0x48, 0x48, 0x2E, 0x6D, 0x6D));
            default: break;
            }
            return String();
        }
        
        String En_Dk::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String En_Dk::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String En_Dk::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String En_Dk::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        