
#include "en_MU.h"
#include <core/lang/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String En_Mu::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String En_Mu::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String En_Mu::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String En_Mu::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool En_Mu::hasVariant() const {
            return false;
        }
        
        gbool En_Mu::hasRegion() const {
            return true;
        }
        
        gbool En_Mu::hasScript() const {
            return false;
        }
            
        String En_Mu::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String En_Mu::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_Mu::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_Mu::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_Mu::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 174: return String(CharArray::of(0x52, 0x73));
            default: break;
            }
            return String();
        }
            
        String En_Mu::quotationStart(gbool alt) const {
            return String();
        }
            
        String En_Mu::quotationEnd(gbool alt) const {
            return String();
        }
            
        String En_Mu::decimalSeparator() const {
            return String();
        }
            
        String En_Mu::groupSeparator() const {
            return String();
        }
            
        String En_Mu::listSeparator() const {
            return String();
        }
            
        String En_Mu::plusSign() const {
            return String();
        }
            
        String En_Mu::minusSign() const {
            return String();
        }
            
        String En_Mu::exponential() const {
            return String();
        }
            
        String En_Mu::perMill() const {
            return String();
        }
            
        String En_Mu::percent() const {
            return String();
        }
            
        String En_Mu::infinity() const {
            return String();
        }
            
        String En_Mu::nan() const {
            return String();
        }
            
        String En_Mu::superScriptingExponent() const {
            return String();
        }
           
        String En_Mu::decimalPattern() const {
            return String();
        }
            
        String En_Mu::scientificPattern() const {
            return String();
        }
            
        String En_Mu::percentPattern() const {
            return String();
        }
            
        String En_Mu::currencyPattern() const {
            return String();
        }

        String En_Mu::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String En_Mu::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray En_Mu::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray En_Mu::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Mu::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Mu::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Mu::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Mu::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String En_Mu::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String En_Mu::timePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x48, 0x48, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x20, 0x7A, 0x7A, 0x7A, 0x7A));
				case 1: return String(CharArray::of(0x48, 0x48, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x20, 0x7A));
				case 2: return String(CharArray::of(0x48, 0x48, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73));
				case 3: return String(CharArray::of(0x48, 0x48, 0x3A, 0x6D, 0x6D));
            default: break;
            }
            return String();
        }
        
        String En_Mu::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String En_Mu::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String En_Mu::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
				case 2: 
				if (style == 4) return String(CharArray::of(0x43, 0x41, 0x54));
					break;
				case 3: 
				if (style == 4) return String(CharArray::of(0x45, 0x41, 0x54));
					break;
				case 4: 
				if (style == 4) return String(CharArray::of(0x53, 0x41, 0x53, 0x54));
					break;
				case 5: 
				if (style == 3) return String(CharArray::of(0x57, 0x41, 0x54));
				if (style == 4) return String(CharArray::of(0x57, 0x41, 0x54));
				if (style == 5) return String(CharArray::of(0x57, 0x41, 0x53, 0x54));
					break;
            default: break;
            }
            return String();
        }
        
        String En_Mu::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        