
#include "en_SX.h"
#include <core/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String En_Sx::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String En_Sx::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String En_Sx::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String En_Sx::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool En_Sx::hasVariant() const {
            return false;
        }
        
        gbool En_Sx::hasRegion() const {
            return true;
        }
        
        gbool En_Sx::hasScript() const {
            return false;
        }
            
        String En_Sx::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String En_Sx::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_Sx::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_Sx::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_Sx::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 7: return String(CharArray::of(0x4E, 0x41, 0x66, 0x2E));
            default: break;
            }
            return String();
        }
            
        String En_Sx::quotationStart(gbool alt) const {
            return String();
        }
            
        String En_Sx::quotationEnd(gbool alt) const {
            return String();
        }
            
        String En_Sx::decimalSeparator() const {
            return String();
        }
            
        String En_Sx::groupSeparator() const {
            return String();
        }
            
        String En_Sx::listSeparator() const {
            return String();
        }
            
        String En_Sx::plusSign() const {
            return String();
        }
            
        String En_Sx::minusSign() const {
            return String();
        }
            
        String En_Sx::exponential() const {
            return String();
        }
            
        String En_Sx::perMill() const {
            return String();
        }
            
        String En_Sx::percent() const {
            return String();
        }
            
        String En_Sx::infinity() const {
            return String();
        }
            
        String En_Sx::nan() const {
            return String();
        }
            
        String En_Sx::superScriptingExponent() const {
            return String();
        }
           
        String En_Sx::decimalPattern() const {
            return String();
        }
            
        String En_Sx::scientificPattern() const {
            return String();
        }
            
        String En_Sx::percentPattern() const {
            return String();
        }
            
        String En_Sx::currencyPattern() const {
            return String();
        }

        String En_Sx::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String En_Sx::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray En_Sx::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray En_Sx::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Sx::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Sx::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Sx::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Sx::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String En_Sx::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String En_Sx::timePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x48, 0x48, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x20, 0x7A, 0x7A, 0x7A, 0x7A));
				case 1: return String(CharArray::of(0x48, 0x48, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x20, 0x7A));
				case 2: return String(CharArray::of(0x48, 0x48, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73));
				case 3: return String(CharArray::of(0x48, 0x48, 0x3A, 0x6D, 0x6D));
            default: break;
            }
            return String();
        }
        
        String En_Sx::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String En_Sx::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String En_Sx::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String En_Sx::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        