
#include "en_TO.h"
#include <core/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String En_To::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String En_To::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String En_To::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String En_To::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool En_To::hasVariant() const {
            return false;
        }
        
        gbool En_To::hasRegion() const {
            return true;
        }
        
        gbool En_To::hasScript() const {
            return false;
        }
            
        String En_To::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String En_To::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_To::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_To::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_To::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 242: return String(CharArray::of(0x54, 0x24));
            default: break;
            }
            return String();
        }
            
        String En_To::quotationStart(gbool alt) const {
            return String();
        }
            
        String En_To::quotationEnd(gbool alt) const {
            return String();
        }
            
        String En_To::decimalSeparator() const {
            return String();
        }
            
        String En_To::groupSeparator() const {
            return String();
        }
            
        String En_To::listSeparator() const {
            return String();
        }
            
        String En_To::plusSign() const {
            return String();
        }
            
        String En_To::minusSign() const {
            return String();
        }
            
        String En_To::exponential() const {
            return String();
        }
            
        String En_To::perMill() const {
            return String();
        }
            
        String En_To::percent() const {
            return String();
        }
            
        String En_To::infinity() const {
            return String();
        }
            
        String En_To::nan() const {
            return String();
        }
            
        String En_To::superScriptingExponent() const {
            return String();
        }
           
        String En_To::decimalPattern() const {
            return String();
        }
            
        String En_To::scientificPattern() const {
            return String();
        }
            
        String En_To::percentPattern() const {
            return String();
        }
            
        String En_To::currencyPattern() const {
            return String();
        }

        String En_To::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String En_To::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray En_To::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray En_To::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_To::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_To::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_To::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_To::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String En_To::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String En_To::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String En_To::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String En_To::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String En_To::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String En_To::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        