
#include "en_VU.h"
#include <core/lang/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String En_Vu::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String En_Vu::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String En_Vu::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String En_Vu::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool En_Vu::hasVariant() const {
            return false;
        }
        
        gbool En_Vu::hasRegion() const {
            return true;
        }
        
        gbool En_Vu::hasScript() const {
            return false;
        }
            
        String En_Vu::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String En_Vu::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_Vu::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_Vu::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_Vu::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 267: return String(CharArray::of(0x56, 0x54));
            default: break;
            }
            return String();
        }
            
        String En_Vu::quotationStart(gbool alt) const {
            return String();
        }
            
        String En_Vu::quotationEnd(gbool alt) const {
            return String();
        }
            
        String En_Vu::decimalSeparator() const {
            return String();
        }
            
        String En_Vu::groupSeparator() const {
            return String();
        }
            
        String En_Vu::listSeparator() const {
            return String();
        }
            
        String En_Vu::plusSign() const {
            return String();
        }
            
        String En_Vu::minusSign() const {
            return String();
        }
            
        String En_Vu::exponential() const {
            return String();
        }
            
        String En_Vu::perMill() const {
            return String();
        }
            
        String En_Vu::percent() const {
            return String();
        }
            
        String En_Vu::infinity() const {
            return String();
        }
            
        String En_Vu::nan() const {
            return String();
        }
            
        String En_Vu::superScriptingExponent() const {
            return String();
        }
           
        String En_Vu::decimalPattern() const {
            return String();
        }
            
        String En_Vu::scientificPattern() const {
            return String();
        }
            
        String En_Vu::percentPattern() const {
            return String();
        }
            
        String En_Vu::currencyPattern() const {
            return String();
        }

        String En_Vu::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String En_Vu::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray En_Vu::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray En_Vu::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Vu::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Vu::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Vu::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Vu::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String En_Vu::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String En_Vu::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String En_Vu::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String En_Vu::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String En_Vu::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String En_Vu::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        