
#include "en_ZM.h"
#include <core/lang/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String En_Zm::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String En_Zm::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String En_Zm::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String En_Zm::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool En_Zm::hasVariant() const {
            return false;
        }
        
        gbool En_Zm::hasRegion() const {
            return true;
        }
        
        gbool En_Zm::hasScript() const {
            return false;
        }
            
        String En_Zm::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String En_Zm::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_Zm::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_Zm::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_Zm::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 300: return String(CharArray::of(0x4B));
            default: break;
            }
            return String();
        }
            
        String En_Zm::quotationStart(gbool alt) const {
            return String();
        }
            
        String En_Zm::quotationEnd(gbool alt) const {
            return String();
        }
            
        String En_Zm::decimalSeparator() const {
            return String();
        }
            
        String En_Zm::groupSeparator() const {
            return String();
        }
            
        String En_Zm::listSeparator() const {
            return String();
        }
            
        String En_Zm::plusSign() const {
            return String();
        }
            
        String En_Zm::minusSign() const {
            return String();
        }
            
        String En_Zm::exponential() const {
            return String();
        }
            
        String En_Zm::perMill() const {
            return String();
        }
            
        String En_Zm::percent() const {
            return String();
        }
            
        String En_Zm::infinity() const {
            return String();
        }
            
        String En_Zm::nan() const {
            return String();
        }
            
        String En_Zm::superScriptingExponent() const {
            return String();
        }
           
        String En_Zm::decimalPattern() const {
            return String();
        }
            
        String En_Zm::scientificPattern() const {
            return String();
        }
            
        String En_Zm::percentPattern() const {
            return String();
        }
            
        String En_Zm::currencyPattern() const {
            return String();
        }

        String En_Zm::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String En_Zm::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray En_Zm::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray En_Zm::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Zm::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Zm::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Zm::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Zm::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String En_Zm::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String En_Zm::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String En_Zm::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String En_Zm::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String En_Zm::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
				case 2: 
				if (style == 4) return String(CharArray::of(0x43, 0x41, 0x54));
					break;
				case 3: 
				if (style == 4) return String(CharArray::of(0x45, 0x41, 0x54));
					break;
				case 4: 
				if (style == 4) return String(CharArray::of(0x53, 0x41, 0x53, 0x54));
					break;
				case 5: 
				if (style == 3) return String(CharArray::of(0x57, 0x41, 0x54));
				if (style == 4) return String(CharArray::of(0x57, 0x41, 0x54));
				if (style == 5) return String(CharArray::of(0x57, 0x41, 0x53, 0x54));
					break;
            default: break;
            }
            return String();
        }
        
        String En_Zm::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        