
#include "en_ZA.h"
#include <core/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String En_Za::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String En_Za::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String En_Za::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String En_Za::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool En_Za::hasVariant() const {
            return false;
        }
        
        gbool En_Za::hasRegion() const {
            return true;
        }
        
        gbool En_Za::hasScript() const {
            return false;
        }
            
        String En_Za::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String En_Za::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_Za::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_Za::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String En_Za::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 298: return String(CharArray::of(0x52));
            default: break;
            }
            return String();
        }
            
        String En_Za::quotationStart(gbool alt) const {
            return String();
        }
            
        String En_Za::quotationEnd(gbool alt) const {
            return String();
        }
            
        String En_Za::decimalSeparator() const {
            return String(CharArray::of(0x2C));
        }
            
        String En_Za::groupSeparator() const {
            return String(CharArray::of(0xA0));
        }
            
        String En_Za::listSeparator() const {
            return String();
        }
            
        String En_Za::plusSign() const {
            return String();
        }
            
        String En_Za::minusSign() const {
            return String();
        }
            
        String En_Za::exponential() const {
            return String();
        }
            
        String En_Za::perMill() const {
            return String();
        }
            
        String En_Za::percent() const {
            return String();
        }
            
        String En_Za::infinity() const {
            return String();
        }
            
        String En_Za::nan() const {
            return String();
        }
            
        String En_Za::superScriptingExponent() const {
            return String();
        }
           
        String En_Za::decimalPattern() const {
            return String();
        }
            
        String En_Za::scientificPattern() const {
            return String();
        }
            
        String En_Za::percentPattern() const {
            return String();
        }
            
        String En_Za::currencyPattern() const {
            return String(CharArray::of(0xA4, 0x23, 0x2C, 0x23, 0x23, 0x30, 0x2E, 0x30, 0x30));
        }

        String En_Za::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String En_Za::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray En_Za::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray En_Za::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Za::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Za::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Za::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray En_Za::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String En_Za::datePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x45, 0x45, 0x45, 0x45, 0x2C, 0x20, 0x64, 0x64, 0x20, 0x4D, 0x4D, 0x4D, 0x4D, 0x20, 0x79));
				case 1: return String(CharArray::of(0x64, 0x64, 0x20, 0x4D, 0x4D, 0x4D, 0x4D, 0x20, 0x79));
				case 2: return String(CharArray::of(0x64, 0x64, 0x20, 0x4D, 0x4D, 0x4D, 0x20, 0x79));
				case 3: return String(CharArray::of(0x79, 0x2F, 0x4D, 0x4D, 0x2F, 0x64, 0x64));
            default: break;
            }
            return String();
        }
        
        String En_Za::timePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x48, 0x48, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x20, 0x7A, 0x7A, 0x7A, 0x7A));
				case 1: return String(CharArray::of(0x48, 0x48, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x20, 0x7A));
				case 2: return String(CharArray::of(0x48, 0x48, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73));
				case 3: return String(CharArray::of(0x48, 0x48, 0x3A, 0x6D, 0x6D));
            default: break;
            }
            return String();
        }
        
        String En_Za::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String En_Za::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String En_Za::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
				case 2: 
				if (style == 4) return String(CharArray::of(0x43, 0x41, 0x54));
					break;
				case 3: 
				if (style == 4) return String(CharArray::of(0x45, 0x41, 0x54));
					break;
				case 4: 
				if (style == 4) return String(CharArray::of(0x53, 0x41, 0x53, 0x54));
					break;
				case 5: 
				if (style == 3) return String(CharArray::of(0x57, 0x41, 0x54));
				if (style == 4) return String(CharArray::of(0x57, 0x41, 0x54));
				if (style == 5) return String(CharArray::of(0x57, 0x41, 0x53, 0x54));
					break;
            default: break;
            }
            return String();
        }
        
        String En_Za::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        