
#include "ff_Adlm_BF.h"
#include <core/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Ff_Adlm_Bf::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Bf::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Bf::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Bf::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Ff_Adlm_Bf::hasVariant() const {
            return false;
        }
        
        gbool Ff_Adlm_Bf::hasRegion() const {
            return true;
        }
        
        gbool Ff_Adlm_Bf::hasScript() const {
            return true;
        }
            
        String Ff_Adlm_Bf::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Bf::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Bf::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Bf::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Bf::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 105: return String(CharArray::of(0x47, 0x4E, 0x46));
            default: break;
            }
            return String();
        }
            
        String Ff_Adlm_Bf::quotationStart(gbool alt) const {
            return String();
        }
            
        String Ff_Adlm_Bf::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Ff_Adlm_Bf::decimalSeparator() const {
            return String();
        }
            
        String Ff_Adlm_Bf::groupSeparator() const {
            return String();
        }
            
        String Ff_Adlm_Bf::listSeparator() const {
            return String();
        }
            
        String Ff_Adlm_Bf::plusSign() const {
            return String();
        }
            
        String Ff_Adlm_Bf::minusSign() const {
            return String();
        }
            
        String Ff_Adlm_Bf::exponential() const {
            return String();
        }
            
        String Ff_Adlm_Bf::perMill() const {
            return String();
        }
            
        String Ff_Adlm_Bf::percent() const {
            return String();
        }
            
        String Ff_Adlm_Bf::infinity() const {
            return String();
        }
            
        String Ff_Adlm_Bf::nan() const {
            return String();
        }
            
        String Ff_Adlm_Bf::superScriptingExponent() const {
            return String();
        }
           
        String Ff_Adlm_Bf::decimalPattern() const {
            return String();
        }
            
        String Ff_Adlm_Bf::scientificPattern() const {
            return String();
        }
            
        String Ff_Adlm_Bf::percentPattern() const {
            return String();
        }
            
        String Ff_Adlm_Bf::currencyPattern() const {
            return String();
        }

        String Ff_Adlm_Bf::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Ff_Adlm_Bf::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Ff_Adlm_Bf::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray Ff_Adlm_Bf::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ff_Adlm_Bf::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ff_Adlm_Bf::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ff_Adlm_Bf::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ff_Adlm_Bf::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Ff_Adlm_Bf::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Bf::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Bf::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Bf::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Bf::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Bf::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        