
#include "ff_Adlm_CM.h"
#include <core/lang/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Ff_Adlm_Cm::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Cm::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Cm::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Cm::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Ff_Adlm_Cm::hasVariant() const {
            return false;
        }
        
        gbool Ff_Adlm_Cm::hasRegion() const {
            return true;
        }
        
        gbool Ff_Adlm_Cm::hasScript() const {
            return true;
        }
            
        String Ff_Adlm_Cm::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Cm::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Cm::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Cm::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Cm::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 105: return String(CharArray::of(0x47, 0x4E, 0x46));
            default: break;
            }
            return String();
        }
            
        String Ff_Adlm_Cm::quotationStart(gbool alt) const {
            return String();
        }
            
        String Ff_Adlm_Cm::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Ff_Adlm_Cm::decimalSeparator() const {
            return String();
        }
            
        String Ff_Adlm_Cm::groupSeparator() const {
            return String();
        }
            
        String Ff_Adlm_Cm::listSeparator() const {
            return String();
        }
            
        String Ff_Adlm_Cm::plusSign() const {
            return String();
        }
            
        String Ff_Adlm_Cm::minusSign() const {
            return String();
        }
            
        String Ff_Adlm_Cm::exponential() const {
            return String();
        }
            
        String Ff_Adlm_Cm::perMill() const {
            return String();
        }
            
        String Ff_Adlm_Cm::percent() const {
            return String();
        }
            
        String Ff_Adlm_Cm::infinity() const {
            return String();
        }
            
        String Ff_Adlm_Cm::nan() const {
            return String();
        }
            
        String Ff_Adlm_Cm::superScriptingExponent() const {
            return String();
        }
           
        String Ff_Adlm_Cm::decimalPattern() const {
            return String();
        }
            
        String Ff_Adlm_Cm::scientificPattern() const {
            return String();
        }
            
        String Ff_Adlm_Cm::percentPattern() const {
            return String();
        }
            
        String Ff_Adlm_Cm::currencyPattern() const {
            return String();
        }

        String Ff_Adlm_Cm::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Ff_Adlm_Cm::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Ff_Adlm_Cm::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray Ff_Adlm_Cm::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ff_Adlm_Cm::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ff_Adlm_Cm::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ff_Adlm_Cm::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ff_Adlm_Cm::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Ff_Adlm_Cm::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Cm::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Cm::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Cm::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Cm::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Cm::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        