
#include "ff_Adlm_NE.h"
#include <core/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Ff_Adlm_Ne::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Ne::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Ne::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Ne::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Ff_Adlm_Ne::hasVariant() const {
            return false;
        }
        
        gbool Ff_Adlm_Ne::hasRegion() const {
            return true;
        }
        
        gbool Ff_Adlm_Ne::hasScript() const {
            return true;
        }
            
        String Ff_Adlm_Ne::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Ne::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Ne::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Ne::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Ne::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 105: return String(CharArray::of(0x47, 0x4E, 0x46));
            default: break;
            }
            return String();
        }
            
        String Ff_Adlm_Ne::quotationStart(gbool alt) const {
            return String();
        }
            
        String Ff_Adlm_Ne::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Ff_Adlm_Ne::decimalSeparator() const {
            return String();
        }
            
        String Ff_Adlm_Ne::groupSeparator() const {
            return String();
        }
            
        String Ff_Adlm_Ne::listSeparator() const {
            return String();
        }
            
        String Ff_Adlm_Ne::plusSign() const {
            return String();
        }
            
        String Ff_Adlm_Ne::minusSign() const {
            return String();
        }
            
        String Ff_Adlm_Ne::exponential() const {
            return String();
        }
            
        String Ff_Adlm_Ne::perMill() const {
            return String();
        }
            
        String Ff_Adlm_Ne::percent() const {
            return String();
        }
            
        String Ff_Adlm_Ne::infinity() const {
            return String();
        }
            
        String Ff_Adlm_Ne::nan() const {
            return String();
        }
            
        String Ff_Adlm_Ne::superScriptingExponent() const {
            return String();
        }
           
        String Ff_Adlm_Ne::decimalPattern() const {
            return String();
        }
            
        String Ff_Adlm_Ne::scientificPattern() const {
            return String();
        }
            
        String Ff_Adlm_Ne::percentPattern() const {
            return String();
        }
            
        String Ff_Adlm_Ne::currencyPattern() const {
            return String();
        }

        String Ff_Adlm_Ne::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Ff_Adlm_Ne::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Ff_Adlm_Ne::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray Ff_Adlm_Ne::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ff_Adlm_Ne::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ff_Adlm_Ne::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ff_Adlm_Ne::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ff_Adlm_Ne::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Ff_Adlm_Ne::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Ne::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Ne::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Ne::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Ne::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ff_Adlm_Ne::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        