
#include "ff_Latn_LR.h"
#include <core/lang/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Ff_Latn_Lr::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Lr::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Lr::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Lr::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Ff_Latn_Lr::hasVariant() const {
            return false;
        }
        
        gbool Ff_Latn_Lr::hasRegion() const {
            return true;
        }
        
        gbool Ff_Latn_Lr::hasScript() const {
            return true;
        }
            
        String Ff_Latn_Lr::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Lr::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Lr::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Lr::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Lr::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 147: return String(CharArray::of(0x24));
            default: break;
            }
            return String();
        }
            
        String Ff_Latn_Lr::quotationStart(gbool alt) const {
            return String();
        }
            
        String Ff_Latn_Lr::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Ff_Latn_Lr::decimalSeparator() const {
            return String();
        }
            
        String Ff_Latn_Lr::groupSeparator() const {
            return String();
        }
            
        String Ff_Latn_Lr::listSeparator() const {
            return String();
        }
            
        String Ff_Latn_Lr::plusSign() const {
            return String();
        }
            
        String Ff_Latn_Lr::minusSign() const {
            return String();
        }
            
        String Ff_Latn_Lr::exponential() const {
            return String();
        }
            
        String Ff_Latn_Lr::perMill() const {
            return String();
        }
            
        String Ff_Latn_Lr::percent() const {
            return String();
        }
            
        String Ff_Latn_Lr::infinity() const {
            return String();
        }
            
        String Ff_Latn_Lr::nan() const {
            return String();
        }
            
        String Ff_Latn_Lr::superScriptingExponent() const {
            return String();
        }
           
        String Ff_Latn_Lr::decimalPattern() const {
            return String();
        }
            
        String Ff_Latn_Lr::scientificPattern() const {
            return String();
        }
            
        String Ff_Latn_Lr::percentPattern() const {
            return String();
        }
            
        String Ff_Latn_Lr::currencyPattern() const {
            return String();
        }

        String Ff_Latn_Lr::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Ff_Latn_Lr::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Ff_Latn_Lr::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray Ff_Latn_Lr::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ff_Latn_Lr::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ff_Latn_Lr::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ff_Latn_Lr::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ff_Latn_Lr::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Ff_Latn_Lr::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Lr::timePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x202F, 0x61, 0x20, 0x7A, 0x7A, 0x7A, 0x7A));
				case 1: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x202F, 0x61, 0x20, 0x7A));
				case 2: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x202F, 0x61));
				case 3: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x202F, 0x61));
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Lr::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Lr::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Lr::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Lr::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        