
#ifndef CORE24_CLDR_FF_LATN_GH
#define CORE24_CLDR_FF_LATN_GH

#include "../Cldr.h"


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    namespace locales {
    
        class Ff_Latn_Gh final : public Cldr {
        public:
            /**
             * Construct new instance of type Ff_Latn_Gh
             */
            CORE_IMPLICIT Ff_Latn_Gh() = default;
            
            /**
             * Return the display name of given language
             */
            String displayLanguage(gint language, gint script, gint region) const override;
            
            /**
             * Return the display name of given script
             */
            String displayScript(gint script) const override;
            
            /**
             * Return the display name of given region
             */
            String displayCountry(gint region) const override;
            
            /**
             * Return the display name of given variant
             */
            String displayVariant(gint variant) const override;
            
            /**
             * Return the display name of given currency in format corresponding
             * to specified number (default if number is -1)
             */
            String displayCurrency(gint currency, gint count) const override;
            
            /**
             * Return the display name of given currency in format corresponding
             * to specified number (default if number is -1)
             */
            String displayUnit(gint unit, gint count) const override;
            
            /**
             * Return the display name of given currency in format corresponding
             * to specified number (default if number is -1)
             */
            String displayShortUnit(gint unit, gint count) const override;
            
            /**
             * Return the display name of given currency in format corresponding
             * to specified number (default if number is -1)
             */
            String displayNarrowUnit(gint unit, gint count) const override;
            
            /**
             * Return the symbol as string of given currency
             */
            String displayCurrencySymbol(gint currency) const override;
            
            /**
             * Return the string representing the quotation start delimiter of this locale
             */
            String quotationStart(gbool alt) const override;
            
            /**
             * Return the string representing the quotation end delimiter of this locale
             */
            String quotationEnd(gbool alt) const override;
            
            /**
             * Return the string representing the decimal separator of this locale
             */
            String decimalSeparator() const override;
            
            /**
             * Return the string representing the group separator of this locale
             */
            String groupSeparator() const override;
            
            /**
             * Return the string representing the list separator of this locale
             */
            String listSeparator() const override;
            
            /**
             * Return the string representing the plus sign of this locale
             */
            String plusSign() const override;
            
            /**
             * Return the string representing the minus sign of this locale
             */
            String minusSign() const override;
            
            /**
             * Return the string representing the exponential symbol of this locale
             */
            String exponential() const override;
            
            /**
             * Return the string representing the per mille symbol of this locale
             */
            String perMill() const override;
            
            /**
             * Return the string representing the percent symbol of this locale
             */
            String percent() const override;
            
            /**
             * Return the string representing the infinity symbol of this locale
             */
            String infinity() const override;
            
            /**
             * Return the string representing the Not-a-Number symbol of this locale
             */
            String nan() const override;
            
            /**
             * Return the string representing the super scripting exponent symbol of this locale
             */
            String superScriptingExponent() const override;
            
            /**
             * Return the array representing the list of digits used in this locale such as
             */
            CharArray digits() const override;
            
            /**
             * Return the strings representing the list of days of week used in this locale (in gregorian calendar)
             * @param style 0: wide, 1: abbreviated, 2: narrow, 3: short
             * @param stand_alone
             */
            StringArray displayDays(gint style, gbool stand_alone) const override;
            
            /**
             * Return the strings representing the list of months used in this locale (in gregorian calendar)
             * @param style 0: wide, 1: abbreviated, 2: narrow, 3: short
             * @param stand_alone
             * @return [monday, tuesday, wednesday, thursday, friday, saturday, sunday]
             */
            StringArray displayMonths(gint style, gbool stand_alone) const override;
            
            /**
             * Return the strings representing the list of quarter used in this locale (in gregorian calendar)
             * @param style 0: wide, 1: abbreviated, 2: narrow, 3: short
             * @param stand_alone
             * @return [1st, 2nd, 3rd, 4th]
             */
            StringArray displayQuarters(gint style, gbool stand_alone) const override;
            
            /**
             * Return the strings representing the list of day periods used in this locale (in gregorian calendar)
             * @param style 0: wide, 1: abbreviated, 2: narrow, 3: short
             * @param stand_alone
             * @return [midnight, am, noon, pm, morning-start, morning-end, afternoon-start, afternoon-end, evening-start, evening-end, night-start, night-end]
             */
            StringArray displayDayPeriods(gint style, gbool stand_alone) const override;
            
            /**
             * Return the strings representing the list of day periods used in this locale (in gregorian calendar)
             * @param style 0: wide, 1: abbreviated, 2: narrow, 3: short
             * @param stand_alone
             * @return [0, 1]
             */
            StringArray displayEras(gint style, gbool stand_alone) const override;
            
            /**
             * Return the string representing the display form of timezone id in this locale.
             * style:
             * 0 = long (generic)
             * 1 = long (standard)
             * 2 = long (daylight)
             * 3 = short (generic)
             * 4 = short (standard)
             * 5 = short (daylight)
             * 6 = city
             */
            String displayTimezone(gint tz, gint style) const override;
            
            /**
             * Return the string representing the display form of timezone id in this locale.
             * style:
             * 0 = long (generic)
             * 1 = long (standard)
             * 2 = long (daylight)
             * 3 = short (generic)
             * 4 = short (standard)
             * 5 = short (daylight)
             */
            String displayGlobalTimezone(gint tz, gint style) const override;
            
            /**
             * Return the string representing the format pattern of timezone in this locale.
             * style:
             * 0 = hourFormat
             * 1 = gmtZeroFormat
             * 2 = gmtFormat
             * 3 = regionFormat
             * 4 = Daylight regionFormat
             * 5 = Standard regionFormat
             * 6 = Fallback
             */
            virtual String timezonePattern(gint type) const override;
            
            /**
             * Return the string representing the format pattern of date in this locale.
             * style:
             * 0 = full
             * 1 = long
             * 2 = medium
             * 3 = short
             */
            String datePattern(gint style) const override;
            
            /**
             * Return the string representing the format pattern of time in this locale.
             * style:
             * 0 = full
             * 1 = long
             * 2 = medium
             * 3 = short
             */
            String timePattern(gint style) const override;
            
            /**
             * Return the string representing the format pattern of date time in this locale.
             * style:
             * 0 = full
             * 1 = long
             * 2 = medium
             * 3 = short
             */
            String datetimePattern(gint style) const override;
            
            /**
             * Return the string representing the decimal format pattern in long format of this locale
             */
            String decimalPattern() const override;
            
            /**
             * Return the string representing the scientific format pattern of this locale
             */
            String scientificPattern() const override;
            
            /**
             * Return the string representing the percent format pattern of this locale
             * ¤ -> symbol
             * # -> digit
             */
            String percentPattern() const override;
            
            /**
             * Return the string representing the currency format pattern of this locale
             * ¤ -> symbol
             * # -> digit
             */
            String currencyPattern() const override;
            
            /**
             * Return the string representing the list pattern in narrow format of this locale
             * type:
             * -1 - start (a, ?)
             * +0 - middle (?, b, ?)
             * +1 - end (?, c)
             * +2 - pair (a, b)
             * subType:
             * 10 - default (and)
             * 11 - or
             * 12 - or-narrow
             * 13 - or-short
             * 14 - standard-narrow
             * 15 - standard-short
             * 16 - unit
             * 17 - unit-narrow
             * 18 - unit-short
             */
            String listPattern(gint type, gint subType) const override;
            
            /**
             * Return the string representing the unit format pattern in narrow format of this locale
             * @param yesOrNo @c true for yes and @c false for no
             */
            String posixMessage(gbool yesOrNo) const override;
            
            gbool hasVariant() const override;
            
            gbool hasRegion() const override;
            
            gbool hasScript() const override;
        };
    }
}
#endif // CORE24_CLDR_FF_LATN_GH
        