
#include "ff_Latn_GM.h"
#include <core/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Ff_Latn_Gm::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Gm::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Gm::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Gm::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Ff_Latn_Gm::hasVariant() const {
            return false;
        }
        
        gbool Ff_Latn_Gm::hasRegion() const {
            return true;
        }
        
        gbool Ff_Latn_Gm::hasScript() const {
            return true;
        }
            
        String Ff_Latn_Gm::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Gm::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Gm::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Gm::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Gm::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 104: return String(CharArray::of(0x44));
            default: break;
            }
            return String();
        }
            
        String Ff_Latn_Gm::quotationStart(gbool alt) const {
            return String();
        }
            
        String Ff_Latn_Gm::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Ff_Latn_Gm::decimalSeparator() const {
            return String();
        }
            
        String Ff_Latn_Gm::groupSeparator() const {
            return String();
        }
            
        String Ff_Latn_Gm::listSeparator() const {
            return String();
        }
            
        String Ff_Latn_Gm::plusSign() const {
            return String();
        }
            
        String Ff_Latn_Gm::minusSign() const {
            return String();
        }
            
        String Ff_Latn_Gm::exponential() const {
            return String();
        }
            
        String Ff_Latn_Gm::perMill() const {
            return String();
        }
            
        String Ff_Latn_Gm::percent() const {
            return String();
        }
            
        String Ff_Latn_Gm::infinity() const {
            return String();
        }
            
        String Ff_Latn_Gm::nan() const {
            return String();
        }
            
        String Ff_Latn_Gm::superScriptingExponent() const {
            return String();
        }
           
        String Ff_Latn_Gm::decimalPattern() const {
            return String();
        }
            
        String Ff_Latn_Gm::scientificPattern() const {
            return String();
        }
            
        String Ff_Latn_Gm::percentPattern() const {
            return String();
        }
            
        String Ff_Latn_Gm::currencyPattern() const {
            return String();
        }

        String Ff_Latn_Gm::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Ff_Latn_Gm::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Ff_Latn_Gm::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray Ff_Latn_Gm::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ff_Latn_Gm::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ff_Latn_Gm::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ff_Latn_Gm::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ff_Latn_Gm::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Ff_Latn_Gm::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Gm::timePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x202F, 0x61, 0x20, 0x7A, 0x7A, 0x7A, 0x7A));
				case 1: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x202F, 0x61, 0x20, 0x7A));
				case 2: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x202F, 0x61));
				case 3: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x202F, 0x61));
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Gm::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Gm::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Gm::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ff_Latn_Gm::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        