
#include "fr_CH.h"
#include <core/lang/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Fr_Ch::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
				case 207: return String(CharArray::of(0x67, 0x6F, 0x75, 0x64, 0x6A, 0x72, 0x61, 0x74, 0x69));
				case 450: return String(CharArray::of(0x61, 0x6C, 0x6C, 0x65, 0x6D, 0x61, 0x6E, 0x64, 0x20, 0x64, 0x65, 0x20, 0x50, 0x65, 0x6E, 0x6E, 0x73, 0x79, 0x6C, 0x76, 0x61, 0x6E, 0x69, 0x65));
				case 503: return String(CharArray::of(0x6B, 0x75, 0x72, 0x64, 0x65, 0x20, 0x6D, 0xE9, 0x72, 0x69, 0x64, 0x69, 0x6F, 0x6E, 0x61, 0x6C));
            default: break;
            }
            return String();
        }
        
        String Fr_Ch::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Fr_Ch::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String Fr_Ch::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Fr_Ch::hasVariant() const {
            return false;
        }
        
        gbool Fr_Ch::hasRegion() const {
            return true;
        }
        
        gbool Fr_Ch::hasScript() const {
            return false;
        }
            
        String Fr_Ch::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Fr_Ch::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Fr_Ch::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Fr_Ch::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Fr_Ch::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
            
        String Fr_Ch::quotationStart(gbool alt) const {
            return (alt) ? String(CharArray::of(0x2039)) : String() ;
        }
            
        String Fr_Ch::quotationEnd(gbool alt) const {
            return (alt) ? String(CharArray::of(0x203A)) : String() ;
        }
            
        String Fr_Ch::decimalSeparator() const {
            return String();
        }
            
        String Fr_Ch::groupSeparator() const {
            return String();
        }
            
        String Fr_Ch::listSeparator() const {
            return String();
        }
            
        String Fr_Ch::plusSign() const {
            return String();
        }
            
        String Fr_Ch::minusSign() const {
            return String();
        }
            
        String Fr_Ch::exponential() const {
            return String();
        }
            
        String Fr_Ch::perMill() const {
            return String();
        }
            
        String Fr_Ch::percent() const {
            return String();
        }
            
        String Fr_Ch::infinity() const {
            return String();
        }
            
        String Fr_Ch::nan() const {
            return String();
        }
            
        String Fr_Ch::superScriptingExponent() const {
            return String();
        }
           
        String Fr_Ch::decimalPattern() const {
            return String();
        }
            
        String Fr_Ch::scientificPattern() const {
            return String();
        }
            
        String Fr_Ch::percentPattern() const {
            return String(CharArray::of(0x23, 0x2C, 0x23, 0x23, 0x30, 0x25));
        }
            
        String Fr_Ch::currencyPattern() const {
            return String();
        }

        String Fr_Ch::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Fr_Ch::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Fr_Ch::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray Fr_Ch::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Fr_Ch::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Fr_Ch::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Fr_Ch::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 1: return StringArray::of(String(CharArray::of(0x6D, 0x69, 0x6E, 0x2E)), String(), String(), String(), String(CharArray::of(0x64, 0x75, 0x20, 0x6D, 0x61, 0x74, 0x2E)), String(CharArray::of(0x64, 0x65, 0x20, 0x6C, 0x2019, 0x61, 0x70, 0x2E, 0x6D, 0x2E)), String(CharArray::of(0x64, 0x75, 0x20, 0x73, 0x6F, 0x69, 0x72)), String(CharArray::of(0x64, 0x75, 0x20, 0x6D, 0x61, 0x74, 0x2E)));
				case 2: return StringArray::of(String(), String(), String(), String(), String(CharArray::of(0x64, 0x75, 0x20, 0x6D, 0x61, 0x74, 0x2E)), String(CharArray::of(0x64, 0x65, 0x20, 0x6C, 0x2019, 0x61, 0x70, 0x2E, 0x6D, 0x2E)), String(), String());
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Fr_Ch::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Fr_Ch::datePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x45, 0x45, 0x45, 0x45, 0x2C, 0x20, 0x64, 0x20, 0x4D, 0x4D, 0x4D, 0x4D, 0x20, 0x79));
				case 3: return String(CharArray::of(0x64, 0x64, 0x2E, 0x4D, 0x4D, 0x2E, 0x79, 0x79));
            default: break;
            }
            return String();
        }
        
        String Fr_Ch::timePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x48, 0x48, 0x2E, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x20, 0x27, 0x68, 0x27, 0x20, 0x7A, 0x7A, 0x7A, 0x7A));
            default: break;
            }
            return String();
        }
        
        String Fr_Ch::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Fr_Ch::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Fr_Ch::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Fr_Ch::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        