
#include "fr_DJ.h"
#include <core/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Fr_Dj::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String Fr_Dj::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Fr_Dj::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String Fr_Dj::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Fr_Dj::hasVariant() const {
            return false;
        }
        
        gbool Fr_Dj::hasRegion() const {
            return true;
        }
        
        gbool Fr_Dj::hasScript() const {
            return false;
        }
            
        String Fr_Dj::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Fr_Dj::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Fr_Dj::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Fr_Dj::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Fr_Dj::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 80: return String(CharArray::of(0x46, 0x64, 0x6A));
            default: break;
            }
            return String();
        }
            
        String Fr_Dj::quotationStart(gbool alt) const {
            return String();
        }
            
        String Fr_Dj::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Fr_Dj::decimalSeparator() const {
            return String();
        }
            
        String Fr_Dj::groupSeparator() const {
            return String();
        }
            
        String Fr_Dj::listSeparator() const {
            return String();
        }
            
        String Fr_Dj::plusSign() const {
            return String();
        }
            
        String Fr_Dj::minusSign() const {
            return String();
        }
            
        String Fr_Dj::exponential() const {
            return String();
        }
            
        String Fr_Dj::perMill() const {
            return String();
        }
            
        String Fr_Dj::percent() const {
            return String();
        }
            
        String Fr_Dj::infinity() const {
            return String();
        }
            
        String Fr_Dj::nan() const {
            return String();
        }
            
        String Fr_Dj::superScriptingExponent() const {
            return String();
        }
           
        String Fr_Dj::decimalPattern() const {
            return String();
        }
            
        String Fr_Dj::scientificPattern() const {
            return String();
        }
            
        String Fr_Dj::percentPattern() const {
            return String();
        }
            
        String Fr_Dj::currencyPattern() const {
            return String();
        }

        String Fr_Dj::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Fr_Dj::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Fr_Dj::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray Fr_Dj::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Fr_Dj::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Fr_Dj::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Fr_Dj::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Fr_Dj::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Fr_Dj::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Fr_Dj::timePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x202F, 0x61, 0x20, 0x7A, 0x7A, 0x7A, 0x7A));
				case 1: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x202F, 0x61, 0x20, 0x7A));
				case 2: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x202F, 0x61));
				case 3: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x202F, 0x61));
            default: break;
            }
            return String();
        }
        
        String Fr_Dj::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Fr_Dj::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Fr_Dj::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Fr_Dj::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        