
#include "kcg.h"
#include <core/lang/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Kcg::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
				case 274: return String(CharArray::of(0x4B, 0x61, 0x74, 0x61, 0x62));
            default: break;
            }
            return String();
        }
        
        String Kcg::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Kcg::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String Kcg::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Kcg::hasVariant() const {
            return false;
        }
        
        gbool Kcg::hasRegion() const {
            return false;
        }
        
        gbool Kcg::hasScript() const {
            return false;
        }
            
        String Kcg::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
				case 186:
					if (count == -1) return String(CharArray::of(0x4E, 0x65, 0x72, 0x61));
					break;
            default: break;
            }
            return String();
        }
        
        String Kcg::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Kcg::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Kcg::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Kcg::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 186: return String(CharArray::of(0x20A6));
            default: break;
            }
            return String();
        }
            
        String Kcg::quotationStart(gbool alt) const {
            return String();
        }
            
        String Kcg::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Kcg::decimalSeparator() const {
            return String();
        }
            
        String Kcg::groupSeparator() const {
            return String();
        }
            
        String Kcg::listSeparator() const {
            return String();
        }
            
        String Kcg::plusSign() const {
            return String();
        }
            
        String Kcg::minusSign() const {
            return String();
        }
            
        String Kcg::exponential() const {
            return String();
        }
            
        String Kcg::perMill() const {
            return String();
        }
            
        String Kcg::percent() const {
            return String();
        }
            
        String Kcg::infinity() const {
            return String();
        }
            
        String Kcg::nan() const {
            return String();
        }
            
        String Kcg::superScriptingExponent() const {
            return String();
        }
           
        String Kcg::decimalPattern() const {
            return String();
        }
            
        String Kcg::scientificPattern() const {
            return String();
        }
            
        String Kcg::percentPattern() const {
            return String();
        }
            
        String Kcg::currencyPattern() const {
            return String();
        }

        String Kcg::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Kcg::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Kcg::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray Kcg::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 1: return StringArray::of(String(CharArray::of(0x54, 0x61, 0x6E)), String(CharArray::of(0x54, 0x61, 0x6C)), String(CharArray::of(0x4C, 0x61, 0x72)), String(CharArray::of(0x4C, 0x61, 0x6D)), String(CharArray::of(0x4A, 0x75, 0x6D)), String(CharArray::of(0x41, 0x73, 0x61)), String(CharArray::of(0x4C, 0x61, 0x64)));
				case 0: return StringArray::of(String(CharArray::of(0x54, 0x61, 0x6E, 0x69, 0x69)), String(CharArray::of(0x54, 0x61, 0x6C, 0x61, 0x74, 0x61)), String(CharArray::of(0x4C, 0x61, 0x72, 0x62, 0x61)), String(CharArray::of(0x4C, 0x61, 0x6D, 0x69, 0x74)), String(CharArray::of(0x4A, 0x75, 0x6D, 0x61)), String(CharArray::of(0x41, 0x73, 0x61, 0x62, 0x61, 0x74)), String(CharArray::of(0x4C, 0x61, 0x64, 0x69)));
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Kcg::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 1: return StringArray::of(String(CharArray::of(0x4A, 0x75, 0x77)), String(CharArray::of(0x53, 0x77, 0x69)), String(CharArray::of(0x54, 0x73, 0x61)), String(CharArray::of(0x4E, 0x79, 0x61)), String(CharArray::of(0x54, 0x73, 0x77)), String(CharArray::of(0x41, 0x74, 0x61)), String(CharArray::of(0x41, 0x6E, 0x61)), String(CharArray::of(0x41, 0x72, 0x69)), String(CharArray::of(0x41, 0x6B, 0x75)), String(CharArray::of(0x53, 0x77, 0x61)), String(CharArray::of(0x4D, 0x61, 0x6E)), String(CharArray::of(0x4D, 0x61, 0x73)));
				case 0: return StringArray::of(String(CharArray::of(0x5A, 0x77, 0x61, 0x74, 0x20, 0x4A, 0x75, 0x77, 0x75, 0x6E, 0x67)), String(CharArray::of(0x5A, 0x77, 0x61, 0x74, 0x20, 0x53, 0x77, 0x69, 0x79, 0x61, 0x6E, 0x67)), String(CharArray::of(0x5A, 0x77, 0x61, 0x74, 0x20, 0x54, 0x73, 0x61, 0x74)), String(CharArray::of(0x5A, 0x77, 0x61, 0x74, 0x20, 0x4E, 0x79, 0x61, 0x69)), String(CharArray::of(0x5A, 0x77, 0x61, 0x74, 0x20, 0x54, 0x73, 0x77, 0x6F, 0x6E)), String(CharArray::of(0x5A, 0x77, 0x61, 0x74, 0x20, 0x41, 0x74, 0x61, 0x61, 0x68)), String(CharArray::of(0x5A, 0x77, 0x61, 0x74, 0x20, 0x41, 0x6E, 0x61, 0x74, 0x61, 0x74)), String(CharArray::of(0x5A, 0x77, 0x61, 0x74, 0x20, 0x41, 0x72, 0x69, 0x6E, 0x61, 0x69)), String(CharArray::of(0x5A, 0x77, 0x61, 0x74, 0x20, 0x41, 0x6B, 0x75, 0x62, 0x75, 0x6E, 0x79, 0x75, 0x6E, 0x67)), String(CharArray::of(0x5A, 0x77, 0x61, 0x74, 0x20, 0x53, 0x77, 0x61, 0x67)), String(CharArray::of(0x5A, 0x77, 0x61, 0x74, 0x20, 0x4D, 0x61, 0x6E, 0x67, 0x6A, 0x75, 0x77, 0x61, 0x6E, 0x67)), String(CharArray::of(0x5A, 0x77, 0x61, 0x74, 0x20, 0x53, 0x77, 0x61, 0x67, 0x2D, 0x4D, 0x61, 0x2D, 0x53, 0x75, 0x79, 0x61, 0x6E, 0x67)));
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Kcg::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Kcg::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Kcg::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 1: return StringArray::of(String(CharArray::of(0x47, 0x4D)), String(CharArray::of(0x4D)));
                default: break;
                }
            } else {
                switch(style) {
				case 1: return StringArray::of(String(CharArray::of(0x47, 0x4D)), String(CharArray::of(0x4D)));
                default: break;
                }
            }
            return StringArray();
        }
        
        String Kcg::datePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x45, 0x45, 0x45, 0x45, 0x2C, 0x20, 0x79, 0x20, 0x4D, 0x4D, 0x4D, 0x4D, 0x20, 0x64, 0x64));
				case 3: return String(CharArray::of(0x79, 0x79, 0x2F, 0x4D, 0x4D, 0x2F, 0x64, 0x64));
            default: break;
            }
            return String();
        }
        
        String Kcg::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Kcg::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Kcg::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Kcg::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Kcg::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        