
#include "kkj.h"
#include <core/lang/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Kkj::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
				case 158: return String(CharArray::of(0x79, 0x61, 0x6D, 0x61, 0x6E));
				case 177: return String(CharArray::of(0x6E, 0x75, 0x6D, 0x62, 0x75, 0x20, 0x62, 0x75, 0x79));
				case 289: return String(CharArray::of(0x6B, 0x61, 0x6B, 0x0254));
            default: break;
            }
            return String();
        }
        
        String Kkj::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Kkj::displayCountry(gint region) const {
            switch(region) {

				case 79: return String(CharArray::of(0x4B, 0x61, 0x6D, 0x025B, 0x72, 0x75, 0x6E));
            default: break;
            }
            return String();
        }
        
        String Kkj::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Kkj::hasVariant() const {
            return false;
        }
        
        gbool Kkj::hasRegion() const {
            return false;
        }
        
        gbool Kkj::hasScript() const {
            return false;
        }
            
        String Kkj::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
				case 269:
					if (count == -1) return String(CharArray::of(0x46, 0x72, 0x61, 0x6E, 0x63, 0x20, 0x43, 0x46, 0x41));
					break;
            default: break;
            }
            return String();
        }
        
        String Kkj::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Kkj::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Kkj::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Kkj::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
            
        String Kkj::quotationStart(gbool alt) const {
            return (alt) ? String(CharArray::of(0x2039)) : String(CharArray::of(0xAB)) ;
        }
            
        String Kkj::quotationEnd(gbool alt) const {
            return (alt) ? String(CharArray::of(0x203A)) : String(CharArray::of(0xBB)) ;
        }
            
        String Kkj::decimalSeparator() const {
            return String(CharArray::of(0x2C));
        }
            
        String Kkj::groupSeparator() const {
            return String(CharArray::of(0x2E));
        }
            
        String Kkj::listSeparator() const {
            return String();
        }
            
        String Kkj::plusSign() const {
            return String();
        }
            
        String Kkj::minusSign() const {
            return String();
        }
            
        String Kkj::exponential() const {
            return String();
        }
            
        String Kkj::perMill() const {
            return String();
        }
            
        String Kkj::percent() const {
            return String();
        }
            
        String Kkj::infinity() const {
            return String();
        }
            
        String Kkj::nan() const {
            return String();
        }
            
        String Kkj::superScriptingExponent() const {
            return String();
        }
           
        String Kkj::decimalPattern() const {
            return String();
        }
            
        String Kkj::scientificPattern() const {
            return String();
        }
            
        String Kkj::percentPattern() const {
            return String();
        }
            
        String Kkj::currencyPattern() const {
            return String();
        }

        String Kkj::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Kkj::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Kkj::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray Kkj::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 0: return StringArray::of(String(CharArray::of(0x6C, 0x75, 0x6E, 0x64, 0x69)), String(CharArray::of(0x6D, 0x61, 0x72, 0x64, 0x69)), String(CharArray::of(0x6D, 0x025B, 0x72, 0x6B, 0x025B, 0x72, 0x025B, 0x64, 0x69)), String(CharArray::of(0x79, 0x65, 0x64, 0x69)), String(CharArray::of(0x76, 0x61, 0x014B, 0x64, 0x025B, 0x72, 0x025B, 0x64, 0x69)), String(CharArray::of(0x6D, 0x0254, 0x6E, 0x0254, 0x20, 0x73, 0x0254, 0x6E, 0x64, 0x69)), String(CharArray::of(0x73, 0x0254, 0x6E, 0x64, 0x69)));
                default: break;
                }
            } else {
                switch(style) {
				case 2: return StringArray::of(String(CharArray::of(0x6C, 0x75)), String(CharArray::of(0x6D, 0x61)), String(CharArray::of(0x6D, 0x025B)), String(CharArray::of(0x79, 0x65)), String(CharArray::of(0x76, 0x61)), String(CharArray::of(0x6D, 0x73)), String(CharArray::of(0x73, 0x6F)));
				case 3: return StringArray::of(String(CharArray::of(0x6C, 0x75)), String(CharArray::of(0x6D, 0x61)), String(CharArray::of(0x6D, 0x025B)), String(CharArray::of(0x79, 0x65)), String(CharArray::of(0x76, 0x61)), String(CharArray::of(0x6D, 0x73)), String(CharArray::of(0x73, 0x6F)));
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Kkj::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 0: return StringArray::of(String(CharArray::of(0x70, 0x61, 0x6D, 0x62, 0x61)), String(CharArray::of(0x77, 0x61, 0x6E, 0x6A, 0x61)), String(CharArray::of(0x6D, 0x62, 0x69, 0x79, 0x0254, 0x20, 0x6D, 0x025B, 0x6E, 0x64, 0x6F, 0x014B, 0x67, 0x0254)), String(CharArray::of(0x4E, 0x79, 0x0254, 0x6C, 0x0254, 0x6D, 0x62, 0x0254, 0x014B, 0x67, 0x0254)), String(CharArray::of(0x4D, 0x0254, 0x6E, 0x0254, 0x20, 0x014B, 0x67, 0x62, 0x61, 0x6E, 0x6A, 0x61)), String(CharArray::of(0x4E, 0x79, 0x61, 0x014B, 0x67, 0x77, 0x025B, 0x20, 0x014B, 0x67, 0x62, 0x61, 0x6E, 0x6A, 0x61)), String(CharArray::of(0x6B, 0x75, 0x014B, 0x67, 0x77, 0x025B)), String(CharArray::of(0x66, 0x025B)), String(CharArray::of(0x6E, 0x6A, 0x61, 0x70, 0x69)), String(CharArray::of(0x6E, 0x79, 0x75, 0x6B, 0x75, 0x6C)), String(), String(CharArray::of(0x0253, 0x75, 0x6C, 0x0253, 0x75, 0x73, 0x025B)));
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Kkj::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Kkj::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Kkj::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Kkj::datePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x45, 0x45, 0x45, 0x45, 0x20, 0x64, 0x64, 0x20, 0x4D, 0x4D, 0x4D, 0x4D, 0x20, 0x79));
				case 1: return String(CharArray::of(0x64, 0x20, 0x4D, 0x4D, 0x4D, 0x4D, 0x20, 0x79));
				case 2: return String(CharArray::of(0x64, 0x20, 0x4D, 0x4D, 0x4D, 0x20, 0x79));
				case 3: return String(CharArray::of(0x64, 0x64, 0x2F, 0x4D, 0x4D, 0x20, 0x79));
            default: break;
            }
            return String();
        }
        
        String Kkj::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Kkj::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Kkj::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Kkj::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Kkj::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        