
#include "ko_KP.h"
#include <core/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Ko_Kp::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String Ko_Kp::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Ko_Kp::displayCountry(gint region) const {
            switch(region) {

				case 161: return String(CharArray::of(0xC870, 0xC120, 0xBBFC, 0xC8FC, 0xC8FC, 0xC758, 0xC778, 0xBBFC, 0xACF5, 0xD654, 0xAD6D));
            default: break;
            }
            return String();
        }
        
        String Ko_Kp::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Ko_Kp::hasVariant() const {
            return false;
        }
        
        gbool Ko_Kp::hasRegion() const {
            return true;
        }
        
        gbool Ko_Kp::hasScript() const {
            return false;
        }
            
        String Ko_Kp::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Ko_Kp::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ko_Kp::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ko_Kp::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ko_Kp::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
            
        String Ko_Kp::quotationStart(gbool alt) const {
            return String();
        }
            
        String Ko_Kp::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Ko_Kp::decimalSeparator() const {
            return String();
        }
            
        String Ko_Kp::groupSeparator() const {
            return String();
        }
            
        String Ko_Kp::listSeparator() const {
            return String();
        }
            
        String Ko_Kp::plusSign() const {
            return String();
        }
            
        String Ko_Kp::minusSign() const {
            return String();
        }
            
        String Ko_Kp::exponential() const {
            return String();
        }
            
        String Ko_Kp::perMill() const {
            return String();
        }
            
        String Ko_Kp::percent() const {
            return String();
        }
            
        String Ko_Kp::infinity() const {
            return String();
        }
            
        String Ko_Kp::nan() const {
            return String();
        }
            
        String Ko_Kp::superScriptingExponent() const {
            return String();
        }
           
        String Ko_Kp::decimalPattern() const {
            return String();
        }
            
        String Ko_Kp::scientificPattern() const {
            return String();
        }
            
        String Ko_Kp::percentPattern() const {
            return String();
        }
            
        String Ko_Kp::currencyPattern() const {
            return String();
        }

        String Ko_Kp::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Ko_Kp::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Ko_Kp::digits() const {
            return CharArray();
        }
        
        StringArray Ko_Kp::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ko_Kp::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ko_Kp::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ko_Kp::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ko_Kp::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Ko_Kp::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ko_Kp::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ko_Kp::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ko_Kp::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ko_Kp::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
				case 86: 
				if (style == 0) return String(CharArray::of(0xC870, 0xC120, 0x20, 0xC2DC, 0xAC04));
				if (style == 1) return String(CharArray::of(0xC870, 0xC120, 0x20, 0xD45C, 0xC900, 0xC2DC));
				if (style == 2) return String(CharArray::of(0xC870, 0xC120, 0x20, 0xD558, 0xACC4, 0x20, 0xD45C, 0xC900, 0xC2DC));
					break;
            default: break;
            }
            return String();
        }
        
        String Ko_Kp::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        