
#include "kok_Latn.h"
#include <core/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Kok_Latn::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
				case 25: return String(CharArray::of(0x41, 0x72, 0x62, 0x69));
				case 156: return String(CharArray::of(0x47, 0x72, 0x69, 0x6B));
				case 158: return String(CharArray::of(0x49, 0x6E, 0x67, 0x6C, 0x69, 0x78));
				case 161: return String(CharArray::of(0x49, 0x73, 0x70, 0x61, 0x6E, 0x68, 0x6F, 0x6C));
				case 177: return String(CharArray::of(0x46, 0x72, 0x61, 0x6E, 0x73, 0x65, 0x7A));
				case 294: return String(CharArray::of(0x4B, 0x6F, 0x6E, 0x2019, 0x6E, 0x6F, 0x64, 0x64));
				case 297: return String(CharArray::of(0x4B, 0x6F, 0x6E, 0x6B, 0x6E, 0x6E, 0x69));
				case 383: return String(CharArray::of(0x4D, 0x6F, 0x72, 0x61, 0x74, 0x74, 0x68, 0x69));
				case 645: return String(CharArray::of(0x43, 0x68, 0x69, 0x6E, 0x69));
            default: break;
            }
            return String();
        }
        
        String Kok_Latn::displayScript(gint script) const {
            switch(script) {
				case 33: return String(CharArray::of(0x44, 0x65, 0x76, 0x61, 0x6E, 0x61, 0x67, 0x61, 0x72, 0x69));
				case 92: return String(CharArray::of(0x52, 0x6F, 0x6D, 0x69));
            default: break;
            }
            return String();
        }
        
        String Kok_Latn::displayCountry(gint region) const {
            switch(region) {

				case 80: return String(CharArray::of(0x43, 0x68, 0x69, 0x6E));

				case 89: return String(CharArray::of(0x53, 0x69, 0x70, 0x72, 0x75, 0x73));

				case 92: return String(CharArray::of(0x4A, 0x65, 0x72, 0x6D, 0x6F, 0x6E));

				case 102: return String(CharArray::of(0x45, 0x6A, 0x69, 0x70, 0x74));

				case 105: return String(CharArray::of(0x49, 0x73, 0x70, 0x61, 0x6E, 0x69, 0x61));

				case 114: return String(CharArray::of(0x46, 0x72, 0x61, 0x6E, 0x73));

				case 128: return String(CharArray::of(0x47, 0x72, 0x65, 0x73));

				case 145: return String(CharArray::of(0x42, 0x68, 0x61, 0x72, 0x6F, 0x74));

				case 150: return String(CharArray::of(0x49, 0x74, 0x61, 0x6C, 0x69, 0x61));

				case 176: return String(CharArray::of(0x4C, 0x69, 0x62, 0x69, 0x61));

				case 184: return String(CharArray::of(0x55, 0x74, 0x2019, 0x74, 0x6F, 0x72, 0x20, 0x4D, 0x61, 0x73, 0x65, 0x64, 0x6F, 0x6E, 0x69, 0x61));

				case 232: return String(CharArray::of(0x52, 0x6F, 0x78, 0x79, 0x61));
            default: break;
            }
            return String();
        }
        
        String Kok_Latn::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Kok_Latn::hasVariant() const {
            return false;
        }
        
        gbool Kok_Latn::hasRegion() const {
            return false;
        }
        
        gbool Kok_Latn::hasScript() const {
            return true;
        }
            
        String Kok_Latn::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Kok_Latn::displayUnit(gint unit, gint count) const {
            switch(unit) { 
				case 45: return String(CharArray::of(0x78, 0x65, 0x6B, 0x64, 0x64, 0x65));
				case 48: return String(CharArray::of(0x64, 0x6F, 0x73, 0x6B, 0x61, 0x6D));
				case 61: return String(CharArray::of(0x76, 0x6F, 0x72, 0x73, 0x61, 0x6D));
				case 57: return String(CharArray::of(0x74, 0x69, 0x6D, 0x68, 0x6F, 0x69, 0x6E, 0x61, 0x6C, 0x6C, 0x65));
				case 53: return String(CharArray::of(0x6D, 0x68, 0x6F, 0x69, 0x6E, 0x65));
				case 59: return String(CharArray::of(0x73, 0x75, 0x6D, 0x61, 0x6E));
				case 46: return String(CharArray::of(0x64, 0x69, 0x73));
				case 49: return String(CharArray::of(0x76, 0x6F, 0x72, 0x61, 0x6D));
				case 52: return String(CharArray::of(0x6D, 0x69, 0x6E, 0x74, 0x61, 0x6D));
				case 58: return String(CharArray::of(0x73, 0x65, 0x6B, 0x6F, 0x6E, 0x64));
				case 51: return String(CharArray::of(0x6D, 0x69, 0x6C, 0x69, 0x73, 0x65, 0x6B, 0x6F, 0x6E, 0x64));
				case 50: return String(CharArray::of(0x6D, 0x61, 0x69, 0x6B, 0x72, 0x6F, 0x73, 0x65, 0x6B, 0x6F, 0x6E, 0x64));
				case 55: return String(CharArray::of(0x6E, 0x61, 0x6E, 0x6F, 0x73, 0x65, 0x6B, 0x6F, 0x6E, 0x64));
				case 56: return String(CharArray::of(0x72, 0x61, 0x74, 0x69));
            default: break;
            }
            return String();
        }
        
        String Kok_Latn::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
				case 45: return String(CharArray::of(0x78));
				case 48: return String(CharArray::of(0x64, 0x6F, 0x73));
				case 61: return String(CharArray::of(0x76, 0x6F, 0x72, 0x73, 0x61, 0x6D));
				case 57: return String(CharArray::of(0x74, 0x69, 0x6D, 0x68, 0x6F));
				case 53: return String(CharArray::of(0x6D, 0x68, 0x6F));
				case 59: return String(CharArray::of(0x73, 0x75, 0x6D, 0x61, 0x6E));
				case 46: return String(CharArray::of(0x64, 0x69, 0x73));
				case 49: return String(CharArray::of(0x76, 0x6F, 0x72, 0x61, 0x6D));
				case 58: return String(CharArray::of(0x73, 0x65, 0x6B));
				case 51: return String(CharArray::of(0x6D, 0x73, 0x65, 0x6B));
				case 50: return String(CharArray::of(0x03BC, 0x73, 0x65, 0x6B));
				case 55: return String(CharArray::of(0x6E, 0x61, 0x6E, 0x6F, 0x73, 0x65, 0x6B));
				case 56: return String(CharArray::of(0x72, 0x61, 0x74, 0x69));
            default: break;
            }
            return String();
        }
        
        String Kok_Latn::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
				case 45: return String(CharArray::of(0x78));
				case 48: return String(CharArray::of(0x64, 0x6F, 0x73));
				case 61: return String(CharArray::of(0x76, 0x6F, 0x72, 0x73, 0x61, 0x6D));
				case 57: return String(CharArray::of(0x74, 0x69, 0x6D, 0x68, 0x6F));
				case 53: return String(CharArray::of(0x6D, 0x68, 0x6F));
				case 59: return String(CharArray::of(0x73, 0x75, 0x6D));
				case 46: return String(CharArray::of(0x64));
				case 49: return String(CharArray::of(0x76, 0x6F, 0x72));
				case 58: return String(CharArray::of(0x73, 0x65, 0x6B));
				case 51: return String(CharArray::of(0x6D, 0x73, 0x65, 0x6B));
				case 50: return String(CharArray::of(0x03BC, 0x73, 0x65, 0x6B));
				case 55: return String(CharArray::of(0x6E, 0x73, 0x65, 0x6B));
				case 56: return String(CharArray::of(0x72, 0x61, 0x74, 0x69));
            default: break;
            }
            return String();
        }
        
        String Kok_Latn::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
            
        String Kok_Latn::quotationStart(gbool alt) const {
            return (alt) ? String() : String() ;
        }
            
        String Kok_Latn::quotationEnd(gbool alt) const {
            return (alt) ? String() : String() ;
        }
            
        String Kok_Latn::decimalSeparator() const {
            return String();
        }
            
        String Kok_Latn::groupSeparator() const {
            return String();
        }
            
        String Kok_Latn::listSeparator() const {
            return String();
        }
            
        String Kok_Latn::plusSign() const {
            return String();
        }
            
        String Kok_Latn::minusSign() const {
            return String();
        }
            
        String Kok_Latn::exponential() const {
            return String();
        }
            
        String Kok_Latn::perMill() const {
            return String();
        }
            
        String Kok_Latn::percent() const {
            return String();
        }
            
        String Kok_Latn::infinity() const {
            return String();
        }
            
        String Kok_Latn::nan() const {
            return String();
        }
            
        String Kok_Latn::superScriptingExponent() const {
            return String();
        }
           
        String Kok_Latn::decimalPattern() const {
            return String(CharArray::of(0x23, 0x2C, 0x23, 0x23, 0x2C, 0x23, 0x23, 0x30, 0x2E, 0x23, 0x23, 0x23));
        }
            
        String Kok_Latn::scientificPattern() const {
            return String();
        }
            
        String Kok_Latn::percentPattern() const {
            return String();
        }
            
        String Kok_Latn::currencyPattern() const {
            return String(CharArray::of(0xA4, 0x23, 0x2C, 0x23, 0x23, 0x2C, 0x23, 0x23, 0x30, 0x2E, 0x30, 0x30));
        }

        String Kok_Latn::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Kok_Latn::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Kok_Latn::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray Kok_Latn::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 1: return StringArray::of(String(CharArray::of(0x53, 0x6F, 0x6D)), String(CharArray::of(0x4D, 0x6F, 0x6E)), String(CharArray::of(0x42, 0x75, 0x64)), String(CharArray::of(0x42, 0x72, 0x65)), String(CharArray::of(0x53, 0x75, 0x6B)), String(CharArray::of(0x53, 0x6F, 0x6E)), String(CharArray::of(0x41, 0x69, 0x74)));
				case 2: return StringArray::of(String(CharArray::of(0x53)), String(CharArray::of(0x4D)), String(CharArray::of(0x42)), String(CharArray::of(0x42)), String(CharArray::of(0x53)), String(), String(CharArray::of(0x41)));
				case 3: return StringArray::of(String(CharArray::of(0x53, 0x6D)), String(CharArray::of(0x4D, 0x67)), String(CharArray::of(0x42, 0x75)), String(CharArray::of(0x42, 0x72)), String(CharArray::of(0x53, 0x75)), String(CharArray::of(0x53, 0x6E)), String(CharArray::of(0x41, 0x69)));
				case 0: return StringArray::of(String(CharArray::of(0x53, 0x6F, 0x6D, 0x61, 0x72)), String(CharArray::of(0x4D, 0x6F, 0x6E, 0x67, 0x6C, 0x6C, 0x61, 0x72)), String(CharArray::of(0x42, 0x75, 0x64, 0x68, 0x76, 0x61, 0x72)), String(CharArray::of(0x42, 0x69, 0x72, 0x65, 0x73, 0x74, 0x61, 0x72)), String(CharArray::of(0x53, 0x75, 0x6B, 0x72, 0x61, 0x72)), String(CharArray::of(0x53, 0x6F, 0x6E, 0x76, 0x61, 0x72)), String(CharArray::of(0x41, 0x69, 0x74, 0x61, 0x72)));
                default: break;
                }
            } else {
                switch(style) {
				case 2: return StringArray::of(String(CharArray::of(0x53)), String(CharArray::of(0x4D)), String(CharArray::of(0x42)), String(CharArray::of(0x42)), String(CharArray::of(0x53)), String(), String(CharArray::of(0x41)));
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Kok_Latn::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 1: return StringArray::of(String(CharArray::of(0x4A, 0x61, 0x6E)), String(CharArray::of(0x46, 0x65, 0x62)), String(CharArray::of(0x4D, 0x61, 0x72)), String(CharArray::of(0x41, 0x62, 0x72)), String(CharArray::of(0x4D, 0x61, 0x69)), String(), String(CharArray::of(0x4A, 0x75, 0x6C)), String(CharArray::of(0x41, 0x67, 0x6F)), String(CharArray::of(0x53, 0x65, 0x74)), String(CharArray::of(0x4F, 0x74, 0x75)), String(CharArray::of(0x4E, 0x6F, 0x76)), String(CharArray::of(0x44, 0x65, 0x7A)));
				case 2: return StringArray::of(String(CharArray::of(0x4A)), String(CharArray::of(0x46)), String(CharArray::of(0x4D)), String(CharArray::of(0x41)), String(CharArray::of(0x4D)), String(CharArray::of(0x4A)), String(CharArray::of(0x4A)), String(CharArray::of(0x41)), String(CharArray::of(0x53)), String(CharArray::of(0x4F)), String(CharArray::of(0x4E)), String(CharArray::of(0x44)));
				case 0: return StringArray::of(String(CharArray::of(0x4A, 0x61, 0x6E, 0x65, 0x72)), String(CharArray::of(0x46, 0x65, 0x62, 0x72, 0x65, 0x72)), String(CharArray::of(0x4D, 0x61, 0x72, 0x73)), String(CharArray::of(0x41, 0x62, 0x72, 0x69, 0x6C)), String(CharArray::of(0x4D, 0x61, 0x69)), String(CharArray::of(0x4A, 0x75, 0x6E)), String(CharArray::of(0x4A, 0x75, 0x6C, 0x61, 0x69)), String(CharArray::of(0x41, 0x67, 0x6F, 0x73, 0x74)), String(CharArray::of(0x53, 0x65, 0x74, 0x65, 0x6D, 0x62, 0x72)), String(CharArray::of(0x4F, 0x74, 0x75, 0x62, 0x72)), String(CharArray::of(0x4E, 0x6F, 0x76, 0x65, 0x6D, 0x62, 0x72)), String(CharArray::of(0x44, 0x65, 0x7A, 0x65, 0x6D, 0x62, 0x72)));
                default: break;
                }
            } else {
                switch(style) {
				case 2: return StringArray::of(String(CharArray::of(0x4A)), String(CharArray::of(0x46)), String(CharArray::of(0x4D)), String(CharArray::of(0x41)), String(CharArray::of(0x4D)), String(CharArray::of(0x4A)), String(CharArray::of(0x4A)), String(CharArray::of(0x41)), String(CharArray::of(0x53)), String(CharArray::of(0x4F)), String(CharArray::of(0x4E)), String(CharArray::of(0x44)));
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Kok_Latn::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 1: return StringArray::of(String(CharArray::of(0x54, 0x69, 0x6D, 0x68, 0x31)), String(CharArray::of(0x54, 0x69, 0x6D, 0x68, 0x32)), String(CharArray::of(0x54, 0x69, 0x6D, 0x68, 0x33)), String(CharArray::of(0x54, 0x69, 0x6D, 0x68, 0x34)));
				case 0: return StringArray::of(String(CharArray::of(0x31, 0x6C, 0x65, 0x6D, 0x20, 0x74, 0x69, 0x6D, 0x68, 0x6F, 0x69, 0x6E, 0x61, 0x6C, 0x6C, 0x65, 0x6D)), String(CharArray::of(0x32, 0x72, 0x65, 0x6D, 0x20, 0x74, 0x69, 0x6D, 0x68, 0x6F, 0x69, 0x6E, 0x61, 0x6C, 0x6C, 0x65, 0x6D)), String(CharArray::of(0x33, 0x72, 0x65, 0x6D, 0x20, 0x74, 0x69, 0x6D, 0x68, 0x6F, 0x69, 0x6E, 0x61, 0x6C, 0x6C, 0x65, 0x6D)), String(CharArray::of(0x34, 0x74, 0x65, 0x6D, 0x20, 0x74, 0x69, 0x6D, 0x68, 0x6F, 0x69, 0x6E, 0x61, 0x6C, 0x6C, 0x65, 0x6D)));
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Kok_Latn::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 0: return StringArray::of(String(), String(CharArray::of(0x73, 0x6F, 0x6B, 0x61, 0x6C, 0x6C, 0x69, 0x6D)), String(), String(CharArray::of(0x73, 0x61, 0x6E, 0x6A, 0x65)), String(), String(), String(), String());
                default: break;
                }
            } else {
                switch(style) {
				case 0: return StringArray::of(String(), String(CharArray::of(0x73, 0x6F, 0x6B, 0x61, 0x6C, 0x6C, 0x69, 0x6D)), String(), String(CharArray::of(0x73, 0x61, 0x6E, 0x6A, 0x65)), String(), String(), String(), String());
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Kok_Latn::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 1: return StringArray::of(String(CharArray::of(0x4B, 0x41)), String(CharArray::of(0x41, 0x44)));
				case 2: return StringArray::of(String(CharArray::of(0x4B)), String(CharArray::of(0x41)));
                default: break;
                }
            } else {
                switch(style) {
				case 1: return StringArray::of(String(CharArray::of(0x4B, 0x41)), String(CharArray::of(0x41, 0x44)));
				case 2: return StringArray::of(String(CharArray::of(0x4B)), String(CharArray::of(0x41)));
                default: break;
                }
            }
            return StringArray();
        }
        
        String Kok_Latn::datePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x45, 0x45, 0x45, 0x45, 0x2C, 0x20, 0x64, 0x20, 0x4D, 0x4D, 0x4D, 0x4D, 0x2C, 0x20, 0x79));
				case 1: return String(CharArray::of(0x64, 0x20, 0x4D, 0x4D, 0x4D, 0x4D, 0x2C, 0x20, 0x79));
				case 2: return String(CharArray::of(0x64, 0x20, 0x4D, 0x4D, 0x4D, 0x2C, 0x20, 0x79));
				case 3: return String(CharArray::of(0x64, 0x2D, 0x4D, 0x2D, 0x79, 0x79));
            default: break;
            }
            return String();
        }
        
        String Kok_Latn::timePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x61, 0x202F, 0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x202F, 0x7A, 0x7A, 0x7A, 0x7A));
				case 1: return String(CharArray::of(0x61, 0x202F, 0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x20, 0x7A));
				case 2: return String(CharArray::of(0x61, 0x202F, 0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73));
				case 3: return String(CharArray::of(0x61, 0x202F, 0x68, 0x3A, 0x6D, 0x6D));
            default: break;
            }
            return String();
        }
        
        String Kok_Latn::datetimePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x7B, 0x31, 0x7D, 0x2C, 0x20, 0x7B, 0x30, 0x7D));
				case 1: return String(CharArray::of(0x7B, 0x31, 0x7D, 0x2C, 0x20, 0x7B, 0x30, 0x7D));
				case 2: return String(CharArray::of(0x7B, 0x31, 0x7D, 0x2C, 0x20, 0x7B, 0x30, 0x7D));
				case 3: return String(CharArray::of(0x7B, 0x31, 0x7D, 0x2C, 0x20, 0x7B, 0x30, 0x7D));
            default: break;
            }
            return String();
        }
        
        String Kok_Latn::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Kok_Latn::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
				case 58: 
				if (style == 1) return String(CharArray::of(0x47, 0x72, 0x65, 0x65, 0x6E, 0x77, 0x69, 0x63, 0x68, 0x20, 0x4D, 0x65, 0x61, 0x6E, 0x20, 0x54, 0x69, 0x6D, 0x65));
					break;
            default: break;
            }
            return String();
        }
        
        String Kok_Latn::timezonePattern(gint type) const {
            switch(type){
				case 3: return String(CharArray::of(0x7B, 0x30, 0x7D, 0x20, 0x56, 0x65, 0x6C, 0x6C));
            default: break;
            }
            return String();
        }
    }
}
        