
#include "mn_Mong.h"
#include <core/lang/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Mn_Mong::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String Mn_Mong::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Mn_Mong::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String Mn_Mong::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Mn_Mong::hasVariant() const {
            return false;
        }
        
        gbool Mn_Mong::hasRegion() const {
            return false;
        }
        
        gbool Mn_Mong::hasScript() const {
            return true;
        }
            
        String Mn_Mong::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
				case 45:
					if (count == -1) return String(CharArray::of(0x0431, 0x0440, 0x0430, 0x0437, 0x0438, 0x043B, 0x20, 0x0440, 0x0435, 0x0430, 0x043B));
					break;
				case 67:
					if (count == -1) return String(CharArray::of(0x044E, 0x0430, 0x043D, 0x044C));
					break;
				case 93:
					if (count == -1) return String(CharArray::of(0x0435, 0x0432, 0x0440, 0x043E));
					break;
				case 98:
					if (count == -1) return String(CharArray::of(0x0444, 0x0443, 0x043D, 0x0442, 0x20, 0x0441, 0x0442, 0x0435, 0x0440, 0x043B, 0x0438, 0x043D, 0x0433));
					break;
				case 124:
					if (count == -1) return String(CharArray::of(0x0440, 0x0443, 0x043F, 0x0438));
					break;
				case 132:
					if (count == -1) return String(CharArray::of(0x0438, 0x0435, 0x043D));
					break;
				case 168:
					if (count == -1) return String(CharArray::of(0x0442, 0x04E9, 0x0433, 0x0440, 0x04E9, 0x0433));
					break;
				case 210:
					if (count == -1) return String(CharArray::of(0x0440, 0x0443, 0x0431, 0x043B, 0x044C));
					break;
				case 253:
					if (count == -1) return String(CharArray::of(0x0430, 0x043C, 0x2E, 0x20, 0x0434, 0x043E, 0x043B, 0x043B, 0x0430, 0x0440));
					break;
            default: break;
            }
            return String();
        }
        
        String Mn_Mong::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Mn_Mong::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Mn_Mong::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Mn_Mong::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 253: return String(CharArray::of(0x24));
            default: break;
            }
            return String();
        }
            
        String Mn_Mong::quotationStart(gbool alt) const {
            return String();
        }
            
        String Mn_Mong::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Mn_Mong::decimalSeparator() const {
            return String();
        }
            
        String Mn_Mong::groupSeparator() const {
            return String();
        }
            
        String Mn_Mong::listSeparator() const {
            return String();
        }
            
        String Mn_Mong::plusSign() const {
            return String();
        }
            
        String Mn_Mong::minusSign() const {
            return String();
        }
            
        String Mn_Mong::exponential() const {
            return String();
        }
            
        String Mn_Mong::perMill() const {
            return String();
        }
            
        String Mn_Mong::percent() const {
            return String();
        }
            
        String Mn_Mong::infinity() const {
            return String();
        }
            
        String Mn_Mong::nan() const {
            return String();
        }
            
        String Mn_Mong::superScriptingExponent() const {
            return String();
        }
           
        String Mn_Mong::decimalPattern() const {
            return String();
        }
            
        String Mn_Mong::scientificPattern() const {
            return String();
        }
            
        String Mn_Mong::percentPattern() const {
            return String();
        }
            
        String Mn_Mong::currencyPattern() const {
            return String();
        }

        String Mn_Mong::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Mn_Mong::posixMessage(gbool yesOrNo) const {
            return (yesOrNo) ? String(CharArray::of(0x0442, 0x0438, 0x0439, 0x043C, 0x3A, 0x0442)) : String(CharArray::of(0x04AF, 0x0433, 0x04AF, 0x0439, 0x3A, 0x04AF));
        }
        
        CharArray Mn_Mong::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray Mn_Mong::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Mn_Mong::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Mn_Mong::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Mn_Mong::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Mn_Mong::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Mn_Mong::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Mn_Mong::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Mn_Mong::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Mn_Mong::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Mn_Mong::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Mn_Mong::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        