
#include "nl_SX.h"
#include <core/lang/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Nl_Sx::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String Nl_Sx::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Nl_Sx::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String Nl_Sx::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Nl_Sx::hasVariant() const {
            return false;
        }
        
        gbool Nl_Sx::hasRegion() const {
            return true;
        }
        
        gbool Nl_Sx::hasScript() const {
            return false;
        }
            
        String Nl_Sx::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Nl_Sx::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Nl_Sx::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Nl_Sx::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Nl_Sx::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 7: return String(CharArray::of(0x4E, 0x41, 0x66, 0x2E));
            default: break;
            }
            return String();
        }
            
        String Nl_Sx::quotationStart(gbool alt) const {
            return String();
        }
            
        String Nl_Sx::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Nl_Sx::decimalSeparator() const {
            return String();
        }
            
        String Nl_Sx::groupSeparator() const {
            return String();
        }
            
        String Nl_Sx::listSeparator() const {
            return String();
        }
            
        String Nl_Sx::plusSign() const {
            return String();
        }
            
        String Nl_Sx::minusSign() const {
            return String();
        }
            
        String Nl_Sx::exponential() const {
            return String();
        }
            
        String Nl_Sx::perMill() const {
            return String();
        }
            
        String Nl_Sx::percent() const {
            return String();
        }
            
        String Nl_Sx::infinity() const {
            return String();
        }
            
        String Nl_Sx::nan() const {
            return String();
        }
            
        String Nl_Sx::superScriptingExponent() const {
            return String();
        }
           
        String Nl_Sx::decimalPattern() const {
            return String();
        }
            
        String Nl_Sx::scientificPattern() const {
            return String();
        }
            
        String Nl_Sx::percentPattern() const {
            return String();
        }
            
        String Nl_Sx::currencyPattern() const {
            return String();
        }

        String Nl_Sx::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Nl_Sx::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Nl_Sx::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray Nl_Sx::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Nl_Sx::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Nl_Sx::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Nl_Sx::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Nl_Sx::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Nl_Sx::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Nl_Sx::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Nl_Sx::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Nl_Sx::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Nl_Sx::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Nl_Sx::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        