
#include "nv.h"
#include <core/lang/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Nv::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
				case 422: return String(CharArray::of(0x44, 0x69, 0x6E, 0xE9, 0x20, 0x42, 0x69, 0x7A, 0x61, 0x61, 0x64));
            default: break;
            }
            return String();
        }
        
        String Nv::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Nv::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String Nv::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Nv::hasVariant() const {
            return false;
        }
        
        gbool Nv::hasRegion() const {
            return false;
        }
        
        gbool Nv::hasScript() const {
            return false;
        }
            
        String Nv::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Nv::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Nv::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Nv::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Nv::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
            
        String Nv::quotationStart(gbool alt) const {
            return String();
        }
            
        String Nv::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Nv::decimalSeparator() const {
            return String();
        }
            
        String Nv::groupSeparator() const {
            return String();
        }
            
        String Nv::listSeparator() const {
            return String();
        }
            
        String Nv::plusSign() const {
            return String();
        }
            
        String Nv::minusSign() const {
            return String();
        }
            
        String Nv::exponential() const {
            return String();
        }
            
        String Nv::perMill() const {
            return String();
        }
            
        String Nv::percent() const {
            return String();
        }
            
        String Nv::infinity() const {
            return String();
        }
            
        String Nv::nan() const {
            return String();
        }
            
        String Nv::superScriptingExponent() const {
            return String();
        }
           
        String Nv::decimalPattern() const {
            return String();
        }
            
        String Nv::scientificPattern() const {
            return String();
        }
            
        String Nv::percentPattern() const {
            return String();
        }
            
        String Nv::currencyPattern() const {
            return String();
        }

        String Nv::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Nv::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Nv::digits() const {
            return CharArray();
        }
        
        StringArray Nv::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Nv::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Nv::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Nv::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Nv::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Nv::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Nv::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Nv::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Nv::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Nv::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Nv::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        