
#include "ru_MD.h"
#include <core/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Ru_Md::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String Ru_Md::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Ru_Md::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String Ru_Md::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Ru_Md::hasVariant() const {
            return false;
        }
        
        gbool Ru_Md::hasRegion() const {
            return true;
        }
        
        gbool Ru_Md::hasScript() const {
            return false;
        }
            
        String Ru_Md::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Ru_Md::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ru_Md::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ru_Md::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ru_Md::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 161: return String(CharArray::of(0x4C));
            default: break;
            }
            return String();
        }
            
        String Ru_Md::quotationStart(gbool alt) const {
            return String();
        }
            
        String Ru_Md::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Ru_Md::decimalSeparator() const {
            return String();
        }
            
        String Ru_Md::groupSeparator() const {
            return String();
        }
            
        String Ru_Md::listSeparator() const {
            return String();
        }
            
        String Ru_Md::plusSign() const {
            return String();
        }
            
        String Ru_Md::minusSign() const {
            return String();
        }
            
        String Ru_Md::exponential() const {
            return String();
        }
            
        String Ru_Md::perMill() const {
            return String();
        }
            
        String Ru_Md::percent() const {
            return String();
        }
            
        String Ru_Md::infinity() const {
            return String();
        }
            
        String Ru_Md::nan() const {
            return String();
        }
            
        String Ru_Md::superScriptingExponent() const {
            return String();
        }
           
        String Ru_Md::decimalPattern() const {
            return String();
        }
            
        String Ru_Md::scientificPattern() const {
            return String();
        }
            
        String Ru_Md::percentPattern() const {
            return String();
        }
            
        String Ru_Md::currencyPattern() const {
            return String();
        }

        String Ru_Md::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Ru_Md::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Ru_Md::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray Ru_Md::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ru_Md::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ru_Md::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ru_Md::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ru_Md::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Ru_Md::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ru_Md::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ru_Md::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ru_Md::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ru_Md::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ru_Md::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        