
#include "sat_Deva.h"
#include <core/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Sat_Deva::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
				case 494: return String(CharArray::of(0x0938, 0x093E, 0x0928, 0x0924, 0x093E, 0x0921, 0x093C, 0x0940));
            default: break;
            }
            return String();
        }
        
        String Sat_Deva::displayScript(gint script) const {
            switch(script) {
				case 33: return String(CharArray::of(0x0926, 0x0947, 0x0935, 0x093E, 0x0928, 0x093E, 0x0917, 0x093E, 0x0930, 0x0940));
				case 128: return String(CharArray::of(0x0905, 0x0932, 0x20, 0x091A, 0x0940, 0x0915, 0x0940));
            default: break;
            }
            return String();
        }
        
        String Sat_Deva::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String Sat_Deva::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Sat_Deva::hasVariant() const {
            return false;
        }
        
        gbool Sat_Deva::hasRegion() const {
            return false;
        }
        
        gbool Sat_Deva::hasScript() const {
            return true;
        }
            
        String Sat_Deva::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Sat_Deva::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Sat_Deva::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Sat_Deva::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Sat_Deva::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
            
        String Sat_Deva::quotationStart(gbool alt) const {
            return String();
        }
            
        String Sat_Deva::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Sat_Deva::decimalSeparator() const {
            return String();
        }
            
        String Sat_Deva::groupSeparator() const {
            return String();
        }
            
        String Sat_Deva::listSeparator() const {
            return String();
        }
            
        String Sat_Deva::plusSign() const {
            return String();
        }
            
        String Sat_Deva::minusSign() const {
            return String();
        }
            
        String Sat_Deva::exponential() const {
            return String();
        }
            
        String Sat_Deva::perMill() const {
            return String();
        }
            
        String Sat_Deva::percent() const {
            return String();
        }
            
        String Sat_Deva::infinity() const {
            return String();
        }
            
        String Sat_Deva::nan() const {
            return String();
        }
            
        String Sat_Deva::superScriptingExponent() const {
            return String();
        }
           
        String Sat_Deva::decimalPattern() const {
            return String();
        }
            
        String Sat_Deva::scientificPattern() const {
            return String();
        }
            
        String Sat_Deva::percentPattern() const {
            return String();
        }
            
        String Sat_Deva::currencyPattern() const {
            return String();
        }

        String Sat_Deva::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Sat_Deva::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Sat_Deva::digits() const {
            return CharArray::of(2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, 2414, 2415);
        }
        
        StringArray Sat_Deva::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Sat_Deva::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Sat_Deva::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Sat_Deva::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Sat_Deva::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Sat_Deva::datePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x45, 0x45, 0x45, 0x45, 0x2C, 0x20, 0x64, 0x20, 0x4D, 0x4D, 0x4D, 0x4D, 0x20, 0x79));
				case 1: return String(CharArray::of(0x64, 0x20, 0x4D, 0x4D, 0x4D, 0x4D, 0x20, 0x79));
				case 2: return String(CharArray::of(0x64, 0x20, 0x4D, 0x4D, 0x4D, 0x20, 0x79));
				case 3: return String(CharArray::of(0x64, 0x2F, 0x4D, 0x2F, 0x79, 0x79));
            default: break;
            }
            return String();
        }
        
        String Sat_Deva::timePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x20, 0x61, 0x20, 0x7A, 0x7A, 0x7A, 0x7A));
				case 1: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x20, 0x61, 0x20, 0x7A));
				case 2: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x20, 0x61));
				case 3: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x20, 0x61));
            default: break;
            }
            return String();
        }
        
        String Sat_Deva::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Sat_Deva::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Sat_Deva::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Sat_Deva::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        