
#include "ss.h"
#include <core/lang/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Ss::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
				case 538: return String(CharArray::of(0x73, 0x69, 0x53, 0x77, 0x61, 0x74, 0x69));
            default: break;
            }
            return String();
        }
        
        String Ss::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Ss::displayCountry(gint region) const {
            switch(region) {

				case 254: return String(CharArray::of(0x65, 0x53, 0x77, 0x61, 0x74, 0x69, 0x6E, 0x69));
            default: break;
            }
            return String();
        }
        
        String Ss::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Ss::hasVariant() const {
            return false;
        }
        
        gbool Ss::hasRegion() const {
            return false;
        }
        
        gbool Ss::hasScript() const {
            return false;
        }
            
        String Ss::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Ss::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ss::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ss::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ss::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 235: return String(CharArray::of(0x45));
				case 298: return String(CharArray::of(0x52));
            default: break;
            }
            return String();
        }
            
        String Ss::quotationStart(gbool alt) const {
            return (alt) ? String(CharArray::of(0x201C)) : String(CharArray::of(0x2018)) ;
        }
            
        String Ss::quotationEnd(gbool alt) const {
            return (alt) ? String(CharArray::of(0x201D)) : String(CharArray::of(0x2019)) ;
        }
            
        String Ss::decimalSeparator() const {
            return String(CharArray::of(0x2C));
        }
            
        String Ss::groupSeparator() const {
            return String(CharArray::of(0xA0));
        }
            
        String Ss::listSeparator() const {
            return String();
        }
            
        String Ss::plusSign() const {
            return String();
        }
            
        String Ss::minusSign() const {
            return String();
        }
            
        String Ss::exponential() const {
            return String();
        }
            
        String Ss::perMill() const {
            return String();
        }
            
        String Ss::percent() const {
            return String();
        }
            
        String Ss::infinity() const {
            return String();
        }
            
        String Ss::nan() const {
            return String();
        }
            
        String Ss::superScriptingExponent() const {
            return String();
        }
           
        String Ss::decimalPattern() const {
            return String();
        }
            
        String Ss::scientificPattern() const {
            return String();
        }
            
        String Ss::percentPattern() const {
            return String();
        }
            
        String Ss::currencyPattern() const {
            return String(CharArray::of(0xA4, 0x23, 0x2C, 0x23, 0x23, 0x30, 0x2E, 0x30, 0x30));
        }

        String Ss::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Ss::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Ss::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray Ss::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 1: return StringArray::of(String(CharArray::of(0x4D, 0x73, 0x6F)), String(CharArray::of(0x42, 0x69, 0x6C)), String(CharArray::of(0x54, 0x73, 0x61)), String(CharArray::of(0x4E, 0x65)), String(CharArray::of(0x48, 0x6C, 0x61)), String(CharArray::of(0x4D, 0x67, 0x63)), String(CharArray::of(0x53, 0x6F, 0x6E)));
				case 0: return StringArray::of(String(CharArray::of(0x75, 0x4D, 0x73, 0x6F, 0x6D, 0x62, 0x75, 0x6C, 0x75, 0x6B, 0x6F)), String(CharArray::of(0x4C, 0x65, 0x73, 0x69, 0x62, 0x69, 0x6C, 0x69)), String(CharArray::of(0x4C, 0x65, 0x73, 0x69, 0x74, 0x73, 0x61, 0x74, 0x66, 0x75)), String(CharArray::of(0x4C, 0x65, 0x73, 0x69, 0x6E, 0x65)), String(CharArray::of(0x4C, 0x65, 0x73, 0x69, 0x68, 0x6C, 0x61, 0x6E, 0x75)), String(CharArray::of(0x75, 0x4D, 0x67, 0x63, 0x69, 0x62, 0x65, 0x6C, 0x6F)), String(CharArray::of(0x4C, 0x69, 0x73, 0x6F, 0x6E, 0x74, 0x66, 0x6F)));
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ss::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 1: return StringArray::of(String(CharArray::of(0x42, 0x68, 0x69)), String(CharArray::of(0x56, 0x61, 0x6E)), String(CharArray::of(0x56, 0x6F, 0x6C)), String(CharArray::of(0x4D, 0x61, 0x62)), String(CharArray::of(0x4E, 0x6B, 0x68)), String(CharArray::of(0x4E, 0x68, 0x6C)), String(CharArray::of(0x4B, 0x68, 0x6F)), String(CharArray::of(0x4E, 0x67, 0x63)), String(CharArray::of(0x4E, 0x79, 0x6F)), String(CharArray::of(0x4D, 0x70, 0x68)), String(CharArray::of(0x4C, 0x77, 0x65)), String(CharArray::of(0x4E, 0x67, 0x6F)));
				case 0: return StringArray::of(String(CharArray::of(0x42, 0x68, 0x69, 0x6D, 0x62, 0x69, 0x64, 0x76, 0x77, 0x61, 0x6E, 0x65)), String(CharArray::of(0x69, 0x4E, 0x64, 0x6C, 0x6F, 0x76, 0x61, 0x6E, 0x61)), String(CharArray::of(0x69, 0x4E, 0x64, 0x6C, 0x6F, 0x76, 0x75, 0x2D, 0x6C, 0x65, 0x6E, 0x6B, 0x68, 0x75, 0x6C, 0x75)), String(CharArray::of(0x4D, 0x61, 0x62, 0x61, 0x73, 0x61)), String(CharArray::of(0x69, 0x4E, 0x6B, 0x68, 0x77, 0x65, 0x6B, 0x68, 0x77, 0x65, 0x74, 0x69)), String(CharArray::of(0x69, 0x4E, 0x68, 0x6C, 0x61, 0x62, 0x61)), String(CharArray::of(0x4B, 0x68, 0x6F, 0x6C, 0x77, 0x61, 0x6E, 0x65)), String(CharArray::of(0x69, 0x4E, 0x67, 0x63, 0x69)), String(CharArray::of(0x69, 0x4E, 0x79, 0x6F, 0x6E, 0x69)), String(CharArray::of(0x69, 0x4D, 0x70, 0x68, 0x61, 0x6C, 0x61)), String(CharArray::of(0x4C, 0x77, 0x65, 0x74, 0x69)), String(CharArray::of(0x69, 0x4E, 0x67, 0x6F, 0x6E, 0x67, 0x6F, 0x6E, 0x69)));
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ss::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ss::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ss::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Ss::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ss::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ss::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ss::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ss::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ss::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        