
#include "sw_CD.h"
#include <core/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Sw_Cd::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
				case 13: return String(CharArray::of(0x4B, 0x69, 0x61, 0x6B, 0x61, 0x6E));
				case 25: 
					if (region == 0) return String(CharArray::of(0x4B, 0x69, 0x61, 0x72, 0x61, 0x62, 0x75, 0x20, 0x63, 0x68, 0x61, 0x20, 0x44, 0x75, 0x6E, 0x69, 0x61, 0x20, 0x4B, 0x69, 0x6C, 0x69, 0x63, 0x68, 0x6F, 0x73, 0x61, 0x6E, 0x69, 0x66, 0x69, 0x73, 0x68, 0x77, 0x61));break;
				case 30: return String(CharArray::of(0x4B, 0x69, 0x61, 0x72, 0x61, 0x62, 0x75, 0x20, 0x63, 0x68, 0x61, 0x20, 0x41, 0x6C, 0x6A, 0x65, 0x72, 0x69, 0x61));
				case 44: return String(CharArray::of(0x4B, 0x69, 0x61, 0x7A, 0x61, 0x62, 0x61, 0x6A, 0x61, 0x6E, 0x69));
				case 211: return String(CharArray::of(0x4B, 0x69, 0x6D, 0x61, 0x6E, 0x6B, 0x73, 0x69));
				case 212: return String(CharArray::of(0x4B, 0x69, 0x67, 0x77, 0x69, 0x63, 0x68, 0x69, 0x69, 0x6E));
				case 232: return String(CharArray::of(0x4B, 0x69, 0x68, 0x75, 0x70, 0x61));
				case 257: return String(CharArray::of(0x4B, 0x69, 0x6C, 0x6F, 0x6A, 0x62, 0x61, 0x6E));
				case 268: return String(CharArray::of(0x4B, 0x69, 0x6B, 0x61, 0x63, 0x68, 0x69, 0x6E));
				case 289: return String(CharArray::of(0x4B, 0x69, 0x6B, 0x61, 0x6B, 0x6F));
				case 296: return String(CharArray::of(0x4B, 0x69, 0x6B, 0x6F, 0x6D, 0x69, 0x70, 0x65, 0x72, 0x6D, 0x79, 0x61, 0x6B));
				case 305: return String(CharArray::of(0x4B, 0x69, 0x6B, 0x75, 0x72, 0x75, 0x6B, 0x68));
				case 311: return String(CharArray::of(0x4B, 0x69, 0x6B, 0x75, 0x6D, 0x79, 0x6B));
				case 317: return String(CharArray::of(0x4B, 0x69, 0x6B, 0x69, 0x72, 0x69, 0x67, 0x69, 0x7A, 0x69));
				case 322: return String(CharArray::of(0x4B, 0x69, 0x6C, 0x61, 0x6D, 0x62, 0x61));
				case 327: return String(CharArray::of(0x4B, 0x69, 0x6C, 0x69, 0x6D, 0x62, 0x75, 0x72, 0x67, 0x69));
				case 361: return String(CharArray::of(0x4B, 0x69, 0x6D, 0x6F, 0x6B, 0x73, 0x68, 0x61));
				case 373: return String(CharArray::of(0x4B, 0x69, 0x6D, 0x69, 0x6B, 0x6D, 0x61, 0x6B, 0x69));
				case 375: return String(CharArray::of(0x4B, 0x69, 0x6D, 0x61, 0x73, 0x65, 0x64, 0x6F, 0x6E, 0x69, 0x61));
				case 381: return String(CharArray::of(0x4B, 0x69, 0x6D, 0x6F, 0x68, 0x6F, 0x6B, 0x69));
				case 382: return String(CharArray::of(0x4B, 0x69, 0x6D, 0x6F, 0x73, 0x73, 0x69));
				case 413: return String(CharArray::of(0x4B, 0x69, 0x6E, 0x67, 0x69, 0x65, 0x6D, 0x62, 0x6F, 0x6F, 0x6E));
				case 418: return String(CharArray::of(0x4B, 0x69, 0x69, 0x6E, 0x6B, 0x6F));
				case 449: return String(CharArray::of(0x50, 0x69, 0x6A, 0x69, 0x6E, 0x69, 0x20, 0x79, 0x61, 0x20, 0x4E, 0x69, 0x6A, 0x65, 0x72, 0x69, 0x61));
				case 467: return String(CharArray::of(0x4B, 0x69, 0x6B, 0x69, 0x69, 0x63, 0x68, 0x65));
				case 516: return String(CharArray::of(0x4B, 0x69, 0x61, 0x72, 0x61, 0x62, 0x75, 0x20, 0x63, 0x68, 0x61, 0x20, 0x43, 0x68, 0x61, 0x64, 0x69));
				case 536: return String(CharArray::of(0x4B, 0x69, 0x74, 0x6F, 0x6E, 0x67, 0x6F, 0x20, 0x63, 0x68, 0x61, 0x20, 0x53, 0x72, 0x61, 0x6E, 0x61, 0x6E));
				case 549: return String(CharArray::of(0x4B, 0x69, 0x6B, 0x6F, 0x6D, 0x6F, 0x72, 0x6F));
				case 551: return String(CharArray::of(0x4B, 0x69, 0x73, 0x69, 0x72, 0x69, 0x61));
				case 598: return String(CharArray::of(0x4B, 0x69, 0x75, 0x64, 0x75, 0x6D, 0x75, 0x72, 0x74, 0x69));
				case 635: return String(CharArray::of(0x4B, 0x69, 0x79, 0x69, 0x64, 0x69));
            default: break;
            }
            return String();
        }
        
        String Sw_Cd::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Sw_Cd::displayCountry(gint region) const {
            switch(region) {

				case 14: return String(CharArray::of(0x41, 0x73, 0x69, 0x61, 0x20, 0x4D, 0x61, 0x73, 0x68, 0x61, 0x72, 0x69, 0x6B, 0x69));

				case 34: return String(CharArray::of(0x41, 0x66, 0x75, 0x67, 0x61, 0x6E, 0x69, 0x73, 0x74, 0x61, 0x6E, 0x69));

				case 47: return String(CharArray::of(0x41, 0x7A, 0x61, 0x62, 0x61, 0x6A, 0x61, 0x6E, 0x69));

				case 56: return String(CharArray::of(0x42, 0x65, 0x6E, 0x69, 0x6E, 0x69));

				case 76: return String(CharArray::of(0x4B, 0x6F, 0x64, 0x69, 0x76, 0x61, 0x61));

				case 88: return String(CharArray::of(0x4B, 0x69, 0x73, 0x69, 0x77, 0x61, 0x20, 0x63, 0x68, 0x61, 0x20, 0x43, 0x68, 0x72, 0x69, 0x73, 0x74, 0x6D, 0x61, 0x73));

				case 137: return String(CharArray::of(0x4B, 0x72, 0x6F, 0x65, 0x73, 0x68, 0x69, 0x61));

				case 153: return String(CharArray::of(0x59, 0x6F, 0x72, 0x64, 0x61, 0x6E, 0x69));

				case 167: return String(CharArray::of(0x4C, 0x65, 0x62, 0x61, 0x6E, 0x6F, 0x6E, 0x69));

				case 169: return String(CharArray::of(0x4C, 0x69, 0x73, 0x68, 0x65, 0x6E, 0x74, 0x65, 0x6E, 0x69));

				case 174: return String(CharArray::of(0x4C, 0x61, 0x73, 0x65, 0x6D, 0x62, 0x61, 0x67, 0x69));

				case 175: return String(CharArray::of(0x4C, 0x61, 0x74, 0x69, 0x76, 0x69, 0x61));

				case 177: return String(CharArray::of(0x4D, 0x6F, 0x72, 0x6F, 0x6B, 0x6F));

				case 186: return String(CharArray::of(0x4D, 0x79, 0x61, 0x6D, 0x61));

				case 202: return String(CharArray::of(0x4E, 0x69, 0x6A, 0x65, 0x72, 0x69));

				case 204: return String(CharArray::of(0x4E, 0x69, 0x6A, 0x65, 0x72, 0x69, 0x61));

				case 207: return String(CharArray::of(0x4E, 0x6F, 0x72, 0x77, 0x65));

				case 208: return String(CharArray::of(0x4E, 0x65, 0x70, 0x61, 0x6C, 0x69));

				case 212: return String(CharArray::of(0x4F, 0x6D, 0x61, 0x6E, 0x69));

				case 222: return String(CharArray::of(0x50, 0x75, 0x65, 0x74, 0x6F, 0x72, 0x69, 0x6B, 0x6F));

				case 227: return String(CharArray::of(0x4B, 0x61, 0x74, 0x61, 0x72, 0x69));

				case 237: return String(CharArray::of(0x53, 0x75, 0x64, 0x61, 0x6E, 0x69));

				case 250: return String(CharArray::of(0x53, 0x61, 0x6F, 0x20, 0x54, 0x6F, 0x6D, 0x65, 0x20, 0x6E, 0x61, 0x20, 0x50, 0x72, 0x69, 0x6E, 0x73, 0x69, 0x70, 0x65));

				case 257: return String(CharArray::of(0x43, 0x68, 0x61, 0x64, 0x69));

				case 263: return String(CharArray::of(0x54, 0x69, 0x6D, 0x6F, 0x72, 0x69, 0x20, 0x79, 0x61, 0x20, 0x4D, 0x61, 0x73, 0x68, 0x61, 0x72, 0x69, 0x6B, 0x69));
            default: break;
            }
            return String();
        }
        
        String Sw_Cd::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Sw_Cd::hasVariant() const {
            return false;
        }
        
        gbool Sw_Cd::hasRegion() const {
            return true;
        }
        
        gbool Sw_Cd::hasScript() const {
            return false;
        }
            
        String Sw_Cd::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
				case 67:
					if (count == -1) return String(CharArray::of(0x59, 0x75, 0x61, 0x6E, 0x20, 0x52, 0x65, 0x6E, 0x6D, 0x69, 0x6E, 0x62, 0x69, 0x20, 0x79, 0x61, 0x20, 0x43, 0x68, 0x69, 0x6E, 0x61));
					break;
				case 92:
					if (count == -1) return String(CharArray::of(0x42, 0x69, 0x72, 0x20, 0x79, 0x61, 0x20, 0x55, 0x68, 0x61, 0x62, 0x65, 0x73, 0x68, 0x69));
					break;
				case 132:
					if (count == -1) return String(CharArray::of(0x53, 0x61, 0x72, 0x61, 0x66, 0x75, 0x20, 0x79, 0x61, 0x20, 0x4B, 0x69, 0x6A, 0x61, 0x70, 0x61, 0x6E, 0x69));
					break;
				case 162:
					if (count == -1) return String(CharArray::of(0x41, 0x72, 0x69, 0x61, 0x72, 0x79, 0x20, 0x79, 0x61, 0x20, 0x42, 0x75, 0x6B, 0x69, 0x6E, 0x69));
					break;
				case 170:
					if (count == -1) return String(CharArray::of(0x55, 0x67, 0x77, 0x69, 0x79, 0x61, 0x20, 0x79, 0x61, 0x20, 0x4D, 0x6F, 0x72, 0x69, 0x74, 0x61, 0x6E, 0x69, 0x61, 0x20, 0x28, 0x31, 0x39, 0x37, 0x33, 0x2013, 0x32, 0x30, 0x31, 0x37, 0x29));
					break;
				case 171:
					if (count == -1) return String(CharArray::of(0x55, 0x67, 0x77, 0x69, 0x79, 0x61, 0x20, 0x79, 0x61, 0x20, 0x4D, 0x6F, 0x72, 0x69, 0x74, 0x61, 0x6E, 0x69, 0x61));
					break;
				case 215:
					if (count == -1) return String(CharArray::of(0x52, 0x75, 0x70, 0x69, 0x61, 0x20, 0x79, 0x61, 0x20, 0x53, 0x68, 0x65, 0x6C, 0x69, 0x73, 0x68, 0x65, 0x6C, 0x69));
					break;
				case 269:
					if (count == -1) return String(CharArray::of(0x46, 0x61, 0x72, 0x61, 0x6E, 0x67, 0x61, 0x20, 0x43, 0x46, 0x41, 0x20, 0x42, 0x45, 0x41, 0x43));
					break;
				case 282:
					if (count == -1) return String(CharArray::of(0x46, 0x61, 0x72, 0x61, 0x6E, 0x67, 0x61, 0x20, 0x43, 0x46, 0x41, 0x20, 0x42, 0x43, 0x45, 0x41, 0x4F));
					break;
            default: break;
            }
            return String();
        }
        
        String Sw_Cd::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Sw_Cd::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Sw_Cd::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Sw_Cd::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 58: return String(CharArray::of(0x46, 0x43));
            default: break;
            }
            return String();
        }
            
        String Sw_Cd::quotationStart(gbool alt) const {
            return String();
        }
            
        String Sw_Cd::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Sw_Cd::decimalSeparator() const {
            return String(CharArray::of(0x2C));
        }
            
        String Sw_Cd::groupSeparator() const {
            return String(CharArray::of(0x2E));
        }
            
        String Sw_Cd::listSeparator() const {
            return String();
        }
            
        String Sw_Cd::plusSign() const {
            return String();
        }
            
        String Sw_Cd::minusSign() const {
            return String();
        }
            
        String Sw_Cd::exponential() const {
            return String();
        }
            
        String Sw_Cd::perMill() const {
            return String();
        }
            
        String Sw_Cd::percent() const {
            return String();
        }
            
        String Sw_Cd::infinity() const {
            return String();
        }
            
        String Sw_Cd::nan() const {
            return String();
        }
            
        String Sw_Cd::superScriptingExponent() const {
            return String();
        }
           
        String Sw_Cd::decimalPattern() const {
            return String();
        }
            
        String Sw_Cd::scientificPattern() const {
            return String();
        }
            
        String Sw_Cd::percentPattern() const {
            return String();
        }
            
        String Sw_Cd::currencyPattern() const {
            return String();
        }

        String Sw_Cd::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Sw_Cd::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Sw_Cd::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray Sw_Cd::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Sw_Cd::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Sw_Cd::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Sw_Cd::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Sw_Cd::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Sw_Cd::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Sw_Cd::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Sw_Cd::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Sw_Cd::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Sw_Cd::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Sw_Cd::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        