
#include "ta_MY.h"
#include <core/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Ta_My::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String Ta_My::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Ta_My::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String Ta_My::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Ta_My::hasVariant() const {
            return false;
        }
        
        gbool Ta_My::hasRegion() const {
            return true;
        }
        
        gbool Ta_My::hasScript() const {
            return false;
        }
            
        String Ta_My::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Ta_My::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ta_My::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ta_My::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ta_My::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 181: return String(CharArray::of(0x52, 0x4D));
				case 220: return String(CharArray::of(0x53, 0x24));
            default: break;
            }
            return String();
        }
            
        String Ta_My::quotationStart(gbool alt) const {
            return String();
        }
            
        String Ta_My::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Ta_My::decimalSeparator() const {
            return String();
        }
            
        String Ta_My::groupSeparator() const {
            return String();
        }
            
        String Ta_My::listSeparator() const {
            return String();
        }
            
        String Ta_My::plusSign() const {
            return String();
        }
            
        String Ta_My::minusSign() const {
            return String();
        }
            
        String Ta_My::exponential() const {
            return String();
        }
            
        String Ta_My::perMill() const {
            return String();
        }
            
        String Ta_My::percent() const {
            return String();
        }
            
        String Ta_My::infinity() const {
            return String();
        }
            
        String Ta_My::nan() const {
            return String();
        }
            
        String Ta_My::superScriptingExponent() const {
            return String();
        }
           
        String Ta_My::decimalPattern() const {
            return String(CharArray::of(0x23, 0x2C, 0x23, 0x23, 0x30, 0x2E, 0x23, 0x23, 0x23));
        }
            
        String Ta_My::scientificPattern() const {
            return String();
        }
            
        String Ta_My::percentPattern() const {
            return String(CharArray::of(0x23, 0x2C, 0x23, 0x23, 0x30, 0x25));
        }
            
        String Ta_My::currencyPattern() const {
            return String(CharArray::of(0xA4, 0xA0, 0x23, 0x2C, 0x23, 0x23, 0x30, 0x2E, 0x30, 0x30));
        }

        String Ta_My::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Ta_My::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Ta_My::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray Ta_My::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ta_My::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ta_My::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ta_My::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ta_My::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Ta_My::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ta_My::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ta_My::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ta_My::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ta_My::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
				case 72: 
				if (style == 4) return String(CharArray::of(0x2205, 0x2205, 0x2205));
					break;
				case 95: 
				if (style == 4) return String(CharArray::of(0x4D, 0x59, 0x54));
					break;
				case 134: 
				if (style == 4) return String(CharArray::of(0x53, 0x47, 0x54));
					break;
            default: break;
            }
            return String();
        }
        
        String Ta_My::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        