
#include "ti_ER.h"
#include <core/lang/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Ti_Er::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
				case 535: return String(CharArray::of(0x1230, 0x122D, 0x1265, 0x129B));
            default: break;
            }
            return String();
        }
        
        String Ti_Er::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Ti_Er::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String Ti_Er::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Ti_Er::hasVariant() const {
            return false;
        }
        
        gbool Ti_Er::hasRegion() const {
            return true;
        }
        
        gbool Ti_Er::hasScript() const {
            return false;
        }
            
        String Ti_Er::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Ti_Er::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ti_Er::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ti_Er::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Ti_Er::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 88: return String(CharArray::of(0x4E, 0x66, 0x6B));
            default: break;
            }
            return String();
        }
            
        String Ti_Er::quotationStart(gbool alt) const {
            return (alt) ? String() : String(CharArray::of(0x2018)) ;
        }
            
        String Ti_Er::quotationEnd(gbool alt) const {
            return (alt) ? String() : String(CharArray::of(0x2019)) ;
        }
            
        String Ti_Er::decimalSeparator() const {
            return String();
        }
            
        String Ti_Er::groupSeparator() const {
            return String();
        }
            
        String Ti_Er::listSeparator() const {
            return String();
        }
            
        String Ti_Er::plusSign() const {
            return String();
        }
            
        String Ti_Er::minusSign() const {
            return String();
        }
            
        String Ti_Er::exponential() const {
            return String();
        }
            
        String Ti_Er::perMill() const {
            return String();
        }
            
        String Ti_Er::percent() const {
            return String();
        }
            
        String Ti_Er::infinity() const {
            return String();
        }
            
        String Ti_Er::nan() const {
            return String();
        }
            
        String Ti_Er::superScriptingExponent() const {
            return String();
        }
           
        String Ti_Er::decimalPattern() const {
            return String();
        }
            
        String Ti_Er::scientificPattern() const {
            return String();
        }
            
        String Ti_Er::percentPattern() const {
            return String();
        }
            
        String Ti_Er::currencyPattern() const {
            return String();
        }

        String Ti_Er::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Ti_Er::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Ti_Er::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray Ti_Er::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ti_Er::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ti_Er::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ti_Er::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Ti_Er::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Ti_Er::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ti_Er::timePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ti_Er::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Ti_Er::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ti_Er::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Ti_Er::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        