
#include "tr_CY.h"
#include <core/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Tr_Cy::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String Tr_Cy::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Tr_Cy::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String Tr_Cy::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Tr_Cy::hasVariant() const {
            return false;
        }
        
        gbool Tr_Cy::hasRegion() const {
            return true;
        }
        
        gbool Tr_Cy::hasScript() const {
            return false;
        }
            
        String Tr_Cy::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Tr_Cy::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Tr_Cy::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Tr_Cy::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Tr_Cy::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
            
        String Tr_Cy::quotationStart(gbool alt) const {
            return String();
        }
            
        String Tr_Cy::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Tr_Cy::decimalSeparator() const {
            return String();
        }
            
        String Tr_Cy::groupSeparator() const {
            return String();
        }
            
        String Tr_Cy::listSeparator() const {
            return String();
        }
            
        String Tr_Cy::plusSign() const {
            return String();
        }
            
        String Tr_Cy::minusSign() const {
            return String();
        }
            
        String Tr_Cy::exponential() const {
            return String();
        }
            
        String Tr_Cy::perMill() const {
            return String();
        }
            
        String Tr_Cy::percent() const {
            return String();
        }
            
        String Tr_Cy::infinity() const {
            return String();
        }
            
        String Tr_Cy::nan() const {
            return String();
        }
            
        String Tr_Cy::superScriptingExponent() const {
            return String();
        }
           
        String Tr_Cy::decimalPattern() const {
            return String();
        }
            
        String Tr_Cy::scientificPattern() const {
            return String();
        }
            
        String Tr_Cy::percentPattern() const {
            return String();
        }
            
        String Tr_Cy::currencyPattern() const {
            return String();
        }

        String Tr_Cy::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Tr_Cy::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Tr_Cy::digits() const {
            return CharArray();
        }
        
        StringArray Tr_Cy::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Tr_Cy::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Tr_Cy::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Tr_Cy::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Tr_Cy::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Tr_Cy::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Tr_Cy::timePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x202F, 0x61, 0x20, 0x7A, 0x7A, 0x7A, 0x7A));
				case 1: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x202F, 0x61, 0x20, 0x7A));
				case 2: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x202F, 0x61));
				case 3: return String(CharArray::of(0x68, 0x3A, 0x6D, 0x6D, 0x202F, 0x61));
            default: break;
            }
            return String();
        }
        
        String Tr_Cy::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Tr_Cy::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Tr_Cy::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Tr_Cy::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        