
#include "uz_Arab.h"
#include <core/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Uz_Arab::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
				case 167: return String(CharArray::of(0x062F, 0x0631, 0x06CC));
				case 464: return String(CharArray::of(0x067E, 0x0634, 0x062A, 0x0648));
				case 605: return String(CharArray::of(0x0627, 0x0648, 0x0632, 0x0628, 0x06CC, 0x06A9));
            default: break;
            }
            return String();
        }
        
        String Uz_Arab::displayScript(gint script) const {
            switch(script) {
				case 4: return String(CharArray::of(0x0639, 0x0631, 0x0628, 0x06CC));
            default: break;
            }
            return String();
        }
        
        String Uz_Arab::displayCountry(gint region) const {
            switch(region) {

				case 34: return String(CharArray::of(0x0627, 0x0641, 0x063A, 0x0627, 0x0646, 0x0633, 0x062A, 0x0627, 0x0646));
            default: break;
            }
            return String();
        }
        
        String Uz_Arab::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Uz_Arab::hasVariant() const {
            return false;
        }
        
        gbool Uz_Arab::hasRegion() const {
            return false;
        }
        
        gbool Uz_Arab::hasScript() const {
            return true;
        }
            
        String Uz_Arab::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
				case 3:
					if (count == -1) return String(CharArray::of(0x0627, 0x0641, 0x063A, 0x0627, 0x0646, 0x06CC));
					break;
            default: break;
            }
            return String();
        }
        
        String Uz_Arab::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Uz_Arab::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Uz_Arab::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Uz_Arab::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
				case 3: return String(CharArray::of(0x060B));
            default: break;
            }
            return String();
        }
            
        String Uz_Arab::quotationStart(gbool alt) const {
            return String();
        }
            
        String Uz_Arab::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Uz_Arab::decimalSeparator() const {
            return String();
        }
            
        String Uz_Arab::groupSeparator() const {
            return String();
        }
            
        String Uz_Arab::listSeparator() const {
            return String();
        }
            
        String Uz_Arab::plusSign() const {
            return String();
        }
            
        String Uz_Arab::minusSign() const {
            return String();
        }
            
        String Uz_Arab::exponential() const {
            return String();
        }
            
        String Uz_Arab::perMill() const {
            return String();
        }
            
        String Uz_Arab::percent() const {
            return String();
        }
            
        String Uz_Arab::infinity() const {
            return String();
        }
            
        String Uz_Arab::nan() const {
            return String();
        }
            
        String Uz_Arab::superScriptingExponent() const {
            return String();
        }
           
        String Uz_Arab::decimalPattern() const {
            return String();
        }
            
        String Uz_Arab::scientificPattern() const {
            return String();
        }
            
        String Uz_Arab::percentPattern() const {
            return String();
        }
            
        String Uz_Arab::currencyPattern() const {
            return String();
        }

        String Uz_Arab::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Uz_Arab::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Uz_Arab::digits() const {
            return CharArray::of(1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785);
        }
        
        StringArray Uz_Arab::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 1: return StringArray::of(String(CharArray::of(0x062F, 0x2E)), String(CharArray::of(0x0633, 0x2E)), String(CharArray::of(0x0686, 0x2E)), String(CharArray::of(0x067E, 0x2E)), String(CharArray::of(0x062C, 0x2E)), String(CharArray::of(0x0634, 0x2E)), String(CharArray::of(0x06CC, 0x2E)));
				case 0: return StringArray::of(String(CharArray::of(0x062F, 0x0648, 0x0634, 0x0646, 0x0628, 0x0647)), String(CharArray::of(0x0633, 0x0647, 0x200C, 0x0634, 0x0646, 0x0628, 0x0647)), String(CharArray::of(0x0686, 0x0647, 0x0627, 0x0631, 0x0634, 0x0646, 0x0628, 0x0647)), String(CharArray::of(0x067E, 0x0646, 0x062C, 0x0634, 0x0646, 0x0628, 0x0647)), String(CharArray::of(0x062C, 0x0645, 0x0639, 0x0647)), String(CharArray::of(0x0634, 0x0646, 0x0628, 0x0647)), String(CharArray::of(0x06CC, 0x06A9, 0x0634, 0x0646, 0x0628, 0x0647)));
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Uz_Arab::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 1: return StringArray::of(String(CharArray::of(0x062C, 0x0646, 0x0648)), String(CharArray::of(0x0641, 0x0628, 0x0631)), String(CharArray::of(0x0645, 0x0627, 0x0631)), String(CharArray::of(0x0627, 0x067E, 0x0631)), String(), String(), String(CharArray::of(0x062C, 0x0648, 0x0644)), String(CharArray::of(0x0627, 0x06AF, 0x0633)), String(CharArray::of(0x0633, 0x067E, 0x062A)), String(CharArray::of(0x0627, 0x06A9, 0x062A)), String(CharArray::of(0x0646, 0x0648, 0x0645)), String(CharArray::of(0x062F, 0x0633, 0x0645)));
				case 0: return StringArray::of(String(CharArray::of(0x062C, 0x0646, 0x0648, 0x0631, 0x06CC)), String(CharArray::of(0x0641, 0x0628, 0x0631, 0x0648, 0x0631, 0x06CC)), String(CharArray::of(0x0645, 0x0627, 0x0631, 0x0686)), String(CharArray::of(0x0627, 0x067E, 0x0631, 0x06CC, 0x0644)), String(CharArray::of(0x0645, 0x06CC)), String(CharArray::of(0x062C, 0x0648, 0x0646)), String(CharArray::of(0x062C, 0x0648, 0x0644, 0x0627, 0x06CC)), String(CharArray::of(0x0627, 0x06AF, 0x0633, 0x062A)), String(CharArray::of(0x0633, 0x067E, 0x062A, 0x0645, 0x0628, 0x0631)), String(CharArray::of(0x0627, 0x06A9, 0x062A, 0x0648, 0x0628, 0x0631)), String(CharArray::of(0x0646, 0x0648, 0x0645, 0x0628, 0x0631)), String(CharArray::of(0x062F, 0x0633, 0x0645, 0x0628, 0x0631)));
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Uz_Arab::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Uz_Arab::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Uz_Arab::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
				case 1: return StringArray::of(String(CharArray::of(0x0642, 0x2E, 0x0645, 0x2E)), String(CharArray::of(0x0645, 0x2E)));
                default: break;
                }
            } else {
                switch(style) {
				case 1: return StringArray::of(String(CharArray::of(0x0642, 0x2E, 0x0645, 0x2E)), String(CharArray::of(0x0645, 0x2E)));
                default: break;
                }
            }
            return StringArray();
        }
        
        String Uz_Arab::datePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x79, 0x20, 0x0646, 0x0686, 0x06CC, 0x20, 0x06CC, 0x06CC, 0x0644, 0x20, 0x64, 0x20, 0x0646, 0x0686, 0x06CC, 0x20, 0x4D, 0x4D, 0x4D, 0x4D, 0x20, 0x45, 0x45, 0x45, 0x45, 0x20, 0x06A9, 0x0648, 0x0646, 0x06CC));
				case 1: return String(CharArray::of(0x64, 0x20, 0x0646, 0x0686, 0x06CC, 0x20, 0x4D, 0x4D, 0x4D, 0x4D, 0x20, 0x79));
				case 2: return String(CharArray::of(0x64, 0x20, 0x4D, 0x4D, 0x4D, 0x20, 0x79));
				case 3: return String(CharArray::of(0x79, 0x2F, 0x4D, 0x2F, 0x64));
            default: break;
            }
            return String();
        }
        
        String Uz_Arab::timePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x48, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x20, 0x28, 0x7A, 0x7A, 0x7A, 0x7A, 0x29));
				case 1: return String(CharArray::of(0x48, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73, 0x20, 0x28, 0x7A, 0x29));
				case 2: return String(CharArray::of(0x48, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73));
				case 3: return String(CharArray::of(0x48, 0x3A, 0x6D, 0x6D));
            default: break;
            }
            return String();
        }
        
        String Uz_Arab::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Uz_Arab::displayTimezone(gint tz, gint style) const {
            switch(tz) {
				case 276: 
					if (style == 6) return String(CharArray::of(0x06A9, 0x0627, 0x0628, 0x0644));
					break;
            default: break;
            }
            return String();
        }
        
        String Uz_Arab::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
				case 1: 
				if (style == 1) return String(CharArray::of(0x0627, 0x0641, 0x063A, 0x0627, 0x0646, 0x0633, 0x062A, 0x0627, 0x0646, 0x20, 0x0648, 0x0642, 0x062A, 0x06CC));
					break;
            default: break;
            }
            return String();
        }
        
        String Uz_Arab::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        