
#include "zh_Hant_MY.h"
#include <core/StringArray.h>


// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// This file has been Generated by CldrGen.py
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


namespace core {
    using namespace util;
    namespace locales {
        
        String Zh_Hant_My::displayLanguage(gint language, gint script, gint region) const {
            switch(language) {
            default: break;
            }
            return String();
        }
        
        String Zh_Hant_My::displayScript(gint script) const {
            switch(script) {
            default: break;
            }
            return String();
        }
        
        String Zh_Hant_My::displayCountry(gint region) const {
            switch(region) {
            default: break;
            }
            return String();
        }
        
        String Zh_Hant_My::displayVariant(gint variant) const {
            switch(variant) {
            default: break;
            }
            return String();
        }
            
        gbool Zh_Hant_My::hasVariant() const {
            return false;
        }
        
        gbool Zh_Hant_My::hasRegion() const {
            return true;
        }
        
        gbool Zh_Hant_My::hasScript() const {
            return true;
        }
            
        String Zh_Hant_My::displayCurrency(gint currency, gint count) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
        
        String Zh_Hant_My::displayUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Zh_Hant_My::displayShortUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Zh_Hant_My::displayNarrowUnit(gint unit, gint count) const {
            switch(unit) { 
            default: break;
            }
            return String();
        }
        
        String Zh_Hant_My::displayCurrencySymbol(gint currency) const {
            switch(currency) { 
            default: break;
            }
            return String();
        }
            
        String Zh_Hant_My::quotationStart(gbool alt) const {
            return String();
        }
            
        String Zh_Hant_My::quotationEnd(gbool alt) const {
            return String();
        }
            
        String Zh_Hant_My::decimalSeparator() const {
            return String();
        }
            
        String Zh_Hant_My::groupSeparator() const {
            return String();
        }
            
        String Zh_Hant_My::listSeparator() const {
            return String();
        }
            
        String Zh_Hant_My::plusSign() const {
            return String();
        }
            
        String Zh_Hant_My::minusSign() const {
            return String();
        }
            
        String Zh_Hant_My::exponential() const {
            return String();
        }
            
        String Zh_Hant_My::perMill() const {
            return String();
        }
            
        String Zh_Hant_My::percent() const {
            return String();
        }
            
        String Zh_Hant_My::infinity() const {
            return String();
        }
            
        String Zh_Hant_My::nan() const {
            return String();
        }
            
        String Zh_Hant_My::superScriptingExponent() const {
            return String();
        }
           
        String Zh_Hant_My::decimalPattern() const {
            return String();
        }
            
        String Zh_Hant_My::scientificPattern() const {
            return String();
        }
            
        String Zh_Hant_My::percentPattern() const {
            return String();
        }
            
        String Zh_Hant_My::currencyPattern() const {
            return String();
        }

        String Zh_Hant_My::listPattern(gint type, gint subType) const {
            switch(subType) {
            default: break;
            }
            return String();
        }
            
        String Zh_Hant_My::posixMessage(gbool yesOrNo) const {
            return String();
        }
        
        CharArray Zh_Hant_My::digits() const {
            return CharArray::of(48, 49, 50, 51, 52, 53, 54, 55, 56, 57);
        }
        
        StringArray Zh_Hant_My::displayDays(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Zh_Hant_My::displayMonths(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Zh_Hant_My::displayQuarters(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Zh_Hant_My::displayDayPeriods(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        StringArray Zh_Hant_My::displayEras(gint style, gbool stand_alone) const {
            if (!stand_alone) { // format
                switch(style) {
                default: break;
                }
            } else {
                switch(style) {
                default: break;
                }
            }
            return StringArray();
        }
        
        String Zh_Hant_My::datePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Zh_Hant_My::timePattern(gint style) const {
            switch(style) {
				case 0: return String(CharArray::of(0x7A, 0x7A, 0x7A, 0x7A, 0x20, 0x61, 0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73));
				case 1: return String(CharArray::of(0x7A, 0x20, 0x61, 0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73));
				case 2: return String(CharArray::of(0x61, 0x68, 0x3A, 0x6D, 0x6D, 0x3A, 0x73, 0x73));
				case 3: return String(CharArray::of(0x61, 0x68, 0x3A, 0x6D, 0x6D));
            default: break;
            }
            return String();
        }
        
        String Zh_Hant_My::datetimePattern(gint style) const {
            switch(style) {
            default: break;
            }
            return String();
        }
        
        String Zh_Hant_My::displayTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Zh_Hant_My::displayGlobalTimezone(gint tz, gint style) const {
            switch(tz) {
            default: break;
            }
            return String();
        }
        
        String Zh_Hant_My::timezonePattern(gint type) const {
            switch(type){
            default: break;
            }
            return String();
        }
    }
}
        