== Docs

.Object
****
La classe *Object* est la racine dans la hierachie des classes definie dans la librarie xref:..\Core24.adoc[*Core24*]
****

=== Inclusion
[source, c++]
--
#include <core/Object>
--

=== Bases
_aucune bases_

=== Constructeurs
_Cette classe n'est pas instantiable._

=== Destructeurs
_Destructeur par defaut definie par le compilateur._

=== Methodes

* Methodes Propres

[#_equals]
[source, c++]
.Equals
--
public:
    Object::equals(Object const& obj) const;
--
_Test et retourne *true* si cet objet est egale à un autre objet donnée._

[#_hash]
[source, c++]
.Hash
--
public:
    Object::hash() const;
--
_Retourne une valeur entiere representant le code de hachage de cet objet._

* Methodes Héritées
_Aucune methodes héritées_

* Methodes Statiques
_Aucune methodes statiques implementées._

=== Sous Types
_Aucun sous types definies_

=== Constantes
_Aucune constantes definies._

=== Macros
_Aucune macro definies_

